from meta.helpers import _m

PROBLEMS = {
    'paradigms/backtracking/core.py::combine': _m(
        "77",
        "组合",
        "给定两个整数 n 和 k，返回 1…n 中所有可能的 k 个数的组合。\n\n组合中元素按升序排列，[1,2] 与 [2,1] 视为同一组合。可使用回溯枚举所有合法选取方案。\n\n约束：1 ≤ k ≤ n ≤ 20。",
        [
            "示例 1：n = 4, k = 2 → [[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]",
            "示例 2：n = 1, k = 1 → [[1]]",
        ],
        [
            "定义 backtracking(n, k, startIndex, path, result)：path 为当前已选数字。",
            "若 len(path) == k，将 path[:] 拷贝追加到 result 并 return。",
            "for i in range(startIndex, n+1)：选 i 入 path，递归 startIndex=i+1（保证升序不重复）。",
            "递归返回后 path.pop() 撤销选择，继续尝试更大起点。",
            "入口 result=[]，调用 backtracking(n,k,1,[],result) 后返回 result。",
        ],
        "回溯",
        code_notes=[
            "startIndex 控制只向后选数，避免 [2,1] 与 [1,2] 重复。",
            "path[:] 拷贝当前路径，防止后续 pop 影响已收集结果。",
            "剪枝优化：for i in range(startIndex, n-(k-len(path))+2) 保证剩余元素够凑 k 个。",
            "终止条件 len(path)==k 而非 startIndex>=n，因需在每层先尝试扩展。",
            "时间 O(C(n,k)·k)，空间 O(k) 递归栈与 path。",
            "经典组合模板：选-递归-撤销。",
        ],
        complexity="时间 O(C(n,k)·k)，空间 O(k)。",
    ),
    'paradigms/backtracking/core.py::generate_parenthesis': _m(
        "22",
        "括号生成",
        "数字 n 代表生成括号的对数，设计函数生成所有可能且有效的括号组合。\n\n有效指每个左括号都有对应右括号，且任意前缀中左括号数不少于右括号数。\n\n约束：1 ≤ n ≤ 8。",
        [
            "示例 1：n = 3 → [\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]",
            "示例 2：n = 1 → [\"()\"]",
        ],
        [
            "维护当前串 S（list）、已用左括号数 left、右括号数 right。",
            "若 len(S) == 2*n，将 ''.join(S) 加入 ans 并 return。",
            "若 left < n，追加 '('，backtrack(left+1, right)，再 pop。",
            "若 right < left，追加 ')'，backtrack(left, right+1)，再 pop。",
            "从 backtrack([],0,0) 开始，返回 ans。",
        ],
        "回溯",
        code_notes=[
            "right < left 保证任意前缀右括号不超过左括号，即始终有效。",
            "left < n 限制左括号最多 n 个。",
            "S 用 list 便于 append/pop，结束时 join 成字符串。",
            "也可 BFS 或 DP 计数，回溯直接构造全部方案。",
            "卡特兰数 C_n 个结果，n=8 时 1430 个。",
            "时间 O(4^n/√n) 量级，空间 O(n) 栈深。",
        ],
        complexity="时间 O(4^n/√n)，空间 O(n)。",
    ),
    'paradigms/backtracking/core.py::letter_combinations': _m(
        "17",
        "电话号码的字母组合",
        "给定仅含数字 2-9 的字符串 digits，返回所有它能表示的字母组合。\n\n映射与电话按键相同；1 不对应任何字母。空串返回空列表。\n\n约束：0 ≤ len(digits) ≤ 4。",
        [
            "示例 1：digits = \"23\" → [\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]",
            "示例 2：digits = \"\" → []",
            "示例 3：digits = \"2\" → [\"a\",\"b\",\"c\"]",
        ],
        [
            "建立 phone_map 将 '2'-'9' 映射到对应字母串。",
            "backtrack(index)：index 为当前处理到 digits 的第几位。",
            "若 index == len(digits)，将 combination join 后追加到 combinations。",
            "否则取 digit=digits[index]，遍历 phone_map[digit] 每个 letter：append、递归 index+1、pop。",
            "digits 为空直接 return []；否则 backtrack(0) 返回 combinations。",
        ],
        "回溯",
        code_notes=[
            "phone_map 静态字典，2→abc, 7→pqrs 等。",
            "combination 为 list 字符，回溯时 pop 撤销。",
            "index 表示深度，与 digits 长度相等时收集答案。",
            "结果顺序任意，题目不要求字典序。",
            "最多 4^4=256 种组合。",
            "时间 O(4^n·n)，空间 O(n) 递归深度。",
        ],
        complexity="时间 O(4^n·n)，空间 O(n)，n=len(digits)。",
    ),
    'paradigms/backtracking/core.py::combination_sum3': _m(
        "216",
        "组合总和 III",
        "找出所有相加之和为 n 的 k 个数的组合，只使用 1 到 9 的数字，每个数字最多使用一次。\n\n返回所有有效组合列表，不可含重复组合，顺序不限。\n\n约束：1 ≤ k ≤ 9，1 ≤ n ≤ 60。",
        [
            "示例 1：k = 3, n = 7 → [[1,2,4]]",
            "示例 2：k = 3, n = 9 → [[1,2,6],[1,3,5],[2,3,4]]",
            "示例 3：k = 4, n = 1 → []",
        ],
        [
            "backtracking(k, n, startIndex, path, result)：从 startIndex 起在 1..9 中选数。",
            "若 len(path)==k：若 sum(path)==n 则收集 path[:]；return。",
            "for i in range(startIndex, 10)：append i，递归 i+1，pop。",
            "入口 backtracking(k,n,1,[],result)，返回 result。",
        ],
        "回溯",
        code_notes=[
            "双重终止：长度 k 时检查和是否为 n，而非和超 n 提前剪枝（可优化 sum> n）。",
            "i+1 保证数字不重复使用且升序。",
            "仅 9 个数字，搜索空间可控。",
            "与 combinationSum 区别：不可重复选、固定 k 个、数字域 1-9。",
            "可在 len(path)<k 时若 sum(path)>n 剪枝。",
            "时间 O(C(9,k))，空间 O(k)。",
        ],
        complexity="时间 O(C(9,k)·k)，空间 O(k)。",
    ),
    'paradigms/backtracking/core.py::combination_sum': _m(
        "39",
        "组合总和",
        "给定无重复元素的整数数组 candidates 和目标 target，找出 candidates 中数字和为 target 的所有不同组合。\n\ncandidates 中同一数字可无限重复选取；至少选数数量不同视为不同组合。\n\n约束：1 ≤ len(candidates) ≤ 30，2 ≤ target ≤ 40，保证解少于 150 个。",
        [
            "示例 1：candidates = [2,3,6,7], target = 7 → [[2,2,3],[7]]",
            "示例 2：candidates = [2,3,5], target = 8 → [[2,2,2,2],[2,3,3],[3,5]]",
        ],
        [
            "backtracking(candidates, target, startIndex, path, result)。",
            "若 sum(path)==target，收集 path[:] 并 return。",
            "若 sum(path)>target，return 剪枝。",
            "for i in range(startIndex, len(candidates))：append candidates[i]，递归 startIndex=i（可重复选），pop。",
            "入口 backtracking(candidates,target,0,[],result)。",
        ],
        "回溯",
        code_notes=[
            "递归传 i 而非 i+1，允许同一元素多次使用。",
            "startIndex 保证组合升序，如 [2,3] 与 [3,2] 不重复。",
            "sum(path) 每次计算，可维护 running_sum 优化。",
            "先判等于 target 再判大于，避免漏解。",
            "与 combinationSum2 区别：可重复、无排序去重。",
            "时间 O(N^(T/min)) 最坏，空间 O(T/min)。",
        ],
        complexity="时间 O(N^(T/min)) 量级，空间 O(target)。",
    ),
    'paradigms/backtracking/core.py::combination_sum2': _m(
        "40",
        "组合总和 II",
        "给定候选人编号集合 candidates（含重复）和目标 target，找出和为 target 的所有组合；每个数字在每个组合中最多用一次。\n\n解集不能包含重复组合。\n\n约束：1 ≤ len(candidates) ≤ 100，1 ≤ target ≤ 500。",
        [
            "示例 1：candidates = [10,1,2,7,6,1,5], target = 8 → [[1,1,6],[1,2,5],[1,7],[2,6]]",
            "示例 2：candidates = [2,5,2,1,2], target = 5 → [[1,2,2],[5]]",
        ],
        [
            "先对 candidates 排序，便于同层去重。",
            "backtracking：sum==target 收集；sum>target 返回。",
            "for i in range(startIndex, len)：若 i>startIndex 且 candidates[i]==candidates[i-1] 则 continue（同层跳过重复）。",
            "append candidates[i]，递归 i+1（每个最多一次），pop。",
        ],
        "回溯",
        code_notes=[
            "candidates.sort() 使相同值相邻，配合同层去重。",
            "i > startIndex and candidates[i]==candidates[i-1] 只跳过同层重复，不同层可各选相同值。",
            "递归 i+1 与 combinationSum 的 i 对比：此处不可重复选。",
            "与 subsets_with_dup 同层去重逻辑一致。",
            "剪枝：排序后可加 candidates[i]>target-break。",
            "时间 O(2^n)，空间 O(n)。",
        ],
        complexity="时间 O(2^n)，空间 O(n)。",
    ),
    'paradigms/backtracking/core.py::subsets': _m(
        "78",
        "子集",
        "给定不含重复元素的整数数组 nums，返回该数组所有可能的子集（幂集）。\n\n解集不能包含重复子集，返回顺序不限。\n\n约束：1 ≤ len(nums) ≤ 10，-10 ≤ nums[i] ≤ 10。",
        [
            "示例 1：nums = [1,2,3] → [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]",
            "示例 2：nums = [0] → [[],[0]]",
        ],
        [
            "backtracking(nums, startIndex, path, result)。",
            "每层递归开始先将 path[:] 追加到 result（收集当前路径，含空集）。",
            "for i in range(startIndex, len(nums))：append nums[i]，递归 i+1，pop。",
            "入口 backtracking(nums,0,[],result)，共 2^n 个子集。",
        ],
        "回溯",
        code_notes=[
            "在 for 循环前收集 path，保证单元素、空集等不遗漏。",
            "startIndex 递增保证子集元素升序索引，避免重复子集。",
            "也可迭代 bitmask 0..2^n-1 生成子集。",
            "与 combine 区别：长度不限，每层都收集。",
            "path[:] 拷贝防止引用污染。",
            "时间 O(n·2^n)，空间 O(n) 栈深。",
        ],
        complexity="时间 O(n·2^n)，空间 O(n)。",
    ),
    'paradigms/backtracking/core.py::subsets_with_dup': _m(
        "90",
        "子集 II",
        "给定可能含重复元素的整数数组 nums，返回该数组所有可能的子集（幂集）。解集不能包含重复子集。\n\n约束：1 ≤ len(nums) ≤ 10，-10 ≤ nums[i] ≤ 10。",
        [
            "示例 1：nums = [1,2,2] → [[],[1],[1,2],[1,2,2],[2],[2,2]]",
            "示例 2：nums = [0] → [[],[0]]",
        ],
        [
            "nums.sort() 排序后回溯。",
            "每层先 result.append(path[:]) 收集当前子集。",
            "for i in range(startIndex, len)：同层若 nums[i]==nums[i-1] 且 i>startIndex 则 skip。",
            "append、递归 i+1、pop。",
        ],
        "回溯",
        code_notes=[
            "同层去重：排序 + i>startIndex and nums[i]==nums[i-1]。",
            "不同层可选相同数值各一次，如 [1,2] 与 [2] 均合法。",
            "与 combinationSum2 去重策略相同。",
            "collect 在 for 前，空集在首层即被收集。",
            "时间 O(n·2^n)，空间 O(n)。",
        ],
        complexity="时间 O(n·2^n)，空间 O(n)。",
    ),
    'paradigms/backtracking/core.py::restore_ip_addresses': _m(
        "93",
        "复原 IP 地址",
        "给定只含数字的字符串 s，复原并返回所有可能的有效 IP 地址格式。\n\n有效 IP 由四个 0-255 的整数组成，用 '.' 分隔，且每段不能有前导零（除非该段就是 \"0\"）。\n\n约束：1 ≤ len(s) ≤ 20。",
        [
            "示例 1：s = \"25525511135\" → [\"255.255.11.135\",\"255.255.111.35\"]",
            "示例 2：s = \"0000\" → [\"0.0.0.0\"]",
            "示例 3：s = \"101023\" → [\"1.0.10.23\",\"1.0.102.3\",\"10.1.0.23\",\"10.10.2.3\",\"101.0.2.3\"]",
        ],
        [
            "backtracking(s, start_index, point_num, current, result)：point_num 为已放逗点数。",
            "若 point_num==3：校验 s[start_index:] 整段合法，合法则 current+s[start_index:] 入 result；return。",
            "for i in range(start_index, len(s))：若 is_valid(s,start_index,i)，取 sub=s[start_index:i+1]，递归 i+1, point_num+1, current+sub+'.'。",
            "若 is_valid 失败则 break（更长段只会更非法，如前导零）。",
        ],
        "回溯",
        code_notes=[
            "is_valid 检查前导零、非数字、值>255。",
            "point_num==3 时不再加点，直接验证第四段到末尾。",
            "break 优化：段不合法时后续更长段含前导零或超 255。",
            "current 累积已确定的 \"a.b.c.\" 前缀。",
            "最多 3 个点分 4 段，每段 1-3 字符。",
            "时间 O(3^4)=O(1) 常数级相对 n，空间 O(1) 除结果。",
        ],
        complexity="时间 O(1)（相对 n 为常数段数），空间 O(1) 栈。",
    ),
    'paradigms/backtracking/core.py::partition': _m(
        "131",
        "分割回文串",
        "给定字符串 s，将 s 分割成若干子串，使每个子串都是回文串，返回 s 的所有可能分割方案。\n\n约束：1 ≤ len(s) ≤ 16。",
        [
            "示例 1：s = \"aab\" → [[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]",
            "示例 2：s = \"a\" → [[\"a\"]]",
        ],
        [
            "backtracking(s, start_index, path, result)。",
            "若 start_index == len(s)，收集 path[:] 并 return。",
            "for i in range(start_index, len(s))：若 s[start_index:i+1] 等于其反序（回文），append 该子串到 path。",
            "递归 backtracking(s, i+1, path, result)，然后 path.pop()。",
        ],
        "回溯",
        code_notes=[
            "s[start_index:i+1][::-1] 判回文，可预处理 DP 优化。",
            "start_index 表示尚未分割的起始位置。",
            "每个回文前缀作为一段，递归处理剩余后缀。",
            "path 存子串列表，非单字符索引。",
            "n=16 时回溯可接受，更大需记忆化。",
            "时间 O(n·2^n) 最坏，空间 O(n) 栈。",
        ],
        complexity="时间 O(n·2^n)，空间 O(n)。",
    ),
    'paradigms/backtracking/core.py::find_sub_sequences': _m(
        "491",
        "递增子序列",
        "给定整数数组 nums，找出并返回所有不同的递增子序列，递增子序列至少包含两个元素。\n\n数组可能含重复元素，出现相等整数也可视为递增的一种情况。顺序不限。\n\n约束：1 ≤ len(nums) ≤ 15，-100 ≤ nums[i] ≤ 100。",
        [
            "示例 1：nums = [4,6,7,7] → [[4,6],[4,6,7],[4,6,7,7],[4,7],[4,7,7],[6,7],[6,7,7],[7,7]]",
            "示例 2：nums = [4,4,3,2,1] → [[4,4]]",
        ],
        [
            "backtracking(nums, startIndex, path, result)。",
            "若 len(path)>=2，收集 path[:]（至少两元素才计入）。",
            "本层 uset=set() 去重：for i in range(startIndex, len)。",
            "若 (path 非空且 nums[i]<path[-1]) 或 nums[i] in uset，continue。",
            "uset.add(nums[i])，append，递归 i+1，pop。",
        ],
        "回溯",
        code_notes=[
            "同层 uset 防止同层选相同值产生重复子序列，如 [4,7] 不重复两次。",
            "path 非空时要求 nums[i]>=path[-1] 保持递增（允许相等）。",
            "len(path)>=2 才收集，单元素不算答案。",
            "不排序数组，靠 startIndex 保证顺序选取。",
            "与 subsets 不同：有递增约束且长度≥2。",
            "时间 O(2^n)，空间 O(n)。",
        ],
        complexity="时间 O(2^n)，空间 O(n)。",
    ),
    'paradigms/backtracking/core.py::permute': _m(
        "46",
        "全排列",
        "给定不含重复数字的数组 nums，返回其所有可能的全排列，顺序不限。\n\n约束：1 ≤ len(nums) ≤ 6，-10 ≤ nums[i] ≤ 10。",
        [
            "示例 1：nums = [1,2,3] → [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]",
            "示例 2：nums = [0,1] → [[0,1],[1,0]]",
        ],
        [
            "backtracking(nums, path, result)：path 存已选元素的下标或值。",
            "若 len(path)==len(nums)，将 [nums[i] for i in path] 追加到 result。",
            "for i in range(len(nums))：若 i in path 则 continue（已使用）。",
            "path.append(i)，递归，path.pop()。",
        ],
        "回溯",
        code_notes=[
            "path 存下标 i，收集时用 nums[i] 还原排列。",
            "也可用 used 布尔数组代替 i in path。",
            "与 combine 区别：使用全部元素、顺序敏感。",
            "n! 个排列，n=6 时 720 个。",
            "交换法 in-place 是另一种 O(1) 额外空间写法。",
            "时间 O(n·n!)，空间 O(n)。",
        ],
        complexity="时间 O(n·n!)，空间 O(n)。",
    ),
    'paradigms/backtracking/core.py::permute_unique': _m(
        "47",
        "全排列 II",
        "给定可含重复数字的序列 nums，按任意顺序返回所有不重复的全排列。\n\n约束：1 ≤ len(nums) ≤ 8，-10 ≤ nums[i] ≤ 10。",
        [
            "示例 1：nums = [1,1,2] → [[1,1,2],[1,2,1],[2,1,1]]",
            "示例 2：nums = [1,2,3] → [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]",
        ],
        [
            "nums.sort() 排序，used 数组标记是否已选。",
            "backtracking(nums, path, used, result)：len(path)==len(nums) 时收集 path[:] 并 return。",
            "for i in range(len(nums))：若 used[i] 则 skip。",
            "若 i>0 且 nums[i]==nums[i-1] 且 not used[i-1]，skip（同层重复值左侧未用则跳过）。",
            "used[i]=True，append nums[i]，递归，pop，used[i]=False。",
        ],
        "回溯",
        code_notes=[
            "not used[i-1] 保证重复值从左到右依次填入，避免 [1a,1b] 与 [1b,1a] 重复。",
            "排序是 dedup 前提。",
            "path 直接存值而非下标。",
            "与 subsets_with_dup 同层去重思想类似但用于排列。",
            "n=8 时最多 40320 排列（无重复时）。",
            "时间 O(n·n!)，空间 O(n)。",
        ],
        complexity="时间 O(n·n!)，空间 O(n)。",
    ),
    'paradigms/backtracking/core.py::word_search_exist': _m(
        "79",
        "单词搜索",
        "给定 m×n 二维字符网格 board 和字符串 word，若 word 存在于网格中返回 true，否则 false。\n\n单词必须按字母顺序通过相邻（水平或垂直）单元格构成，同一单元格不能重复使用。\n\n约束：1 ≤ m,n ≤ 6，1 ≤ len(word) ≤ 15。",
        [
            "示例 1：board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\" → True",
            "示例 2：board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"SEE\" → True",
            "示例 3：board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCB\" → False",
        ],
        [
            "双重循环找 board[r][c]==word[0] 的起点，调用 dfs(r,c,0)。",
            "dfs：index==len(word) 返回 True；越界或 board[r][c]!=word[index] 返回 False。",
            "标记 board[r][c]='*' 防重用，四方向 OR 递归 index+1。",
            "回溯恢复 board[r][c]=word[index]，返回 res。",
            "所有起点均失败则 False。",
        ],
        "回溯",
        code_notes=[
            "原地标记 '*' 代替 visited 数组，回溯时还原。",
            "四方向 or 连接，任一路径成功即 True。",
            "index 表示已匹配 word 前缀长度。",
            "也可 Trie+DFS 多词搜索，单词搜索为特例。",
            "m,n≤6 规模小，回溯足够。",
            "时间 O(m·n·4^L)，空间 O(L) 栈，L=len(word)。",
        ],
        complexity="时间 O(m·n·4^L)，空间 O(L)。",
    ),
    'paradigms/backtracking/core.py::make_square': _m(
        "473",
        "火柴拼正方形",
        "给定整数数组 matchsticks（每根火柴长度），能否用全部火柴拼成一个正方形。不能折断火柴，每根必须使用一次。\n\n约束：1 ≤ len(matchsticks) ≤ 15，1 ≤ matchsticks[i] ≤ 10^8。",
        [
            "示例 1：matchsticks = [1,1,2,2,2] → True（边长 4 的正方形）",
            "示例 2：matchsticks = [3,3,3,3,4] → False",
        ],
        [
            "side = sum(matchsticks)//4；若 side*4!=sum 返回 False。",
            "matchsticks.sort(reverse=True) 大火柴优先，加速剪枝。",
            "sides=[0]*4 表示四条边当前长度，backtracking(i) 尝试放第 i 根。",
            "i==len 时检查 sides[0]==sides[1]==sides[2]==sides[3]==side。",
            "for j in range(4)：若 sides[j]+matchsticks[i]<=side，放入 j，递归 i+1，失败则撤销。",
        ],
        "回溯",
        code_notes=[
            "四条边等价，可固定第一根放 sides[0] 减少对称搜索。",
            "降序排序增强剪枝：大棍先放，失败更早。",
            "side*4!=sum 快速排除不可分情况。",
            "与 partition to k subsets 同模型，k=4。",
            "n=15 时回溯+剪枝可过。",
            "时间 O(4^n) 最坏，空间 O(n) 栈。",
        ],
        complexity="时间 O(4^n) 最坏，空间 O(n)。",
    ),
    'paradigms/greedy/greedy.py::can_jump': _m(
        "55",
        "跳跃游戏",
        "给定非负整数数组 nums，你最初位于数组第一个下标。数组中的每个元素代表你在该位置可以跳跃的最大长度。\n\n判断你是否能够到达最后一个下标。可以假设你总能到达 nums[0]。\n\n约束：1 ≤ len(nums) ≤ 10^4，0 ≤ nums[i] ≤ 10^5。",
        [
            "示例 1：nums = [2,3,1,1,4] → True（跳 1 步到 index 1，再跳 3 步到最后）",
            "示例 2：nums = [3,2,1,0,4] → False",
        ],
        [
            "维护 farthest 表示从起点可达的最远下标。",
            "遍历 index 从 0 到 len-2（最后一个不必跳）：若 farthest < index，说明到不了当前位置，break 失败。",
            "更新 farthest = max(farthest, index + nums[index])。",
            "最后 return farthest >= len(nums)-1。",
        ],
        "贪心",
        code_notes=[
            "farthest 只增不减，记录历史最优可达范围。",
            "farthest < index 时当前位置不可达，后续更不可达。",
            "不必模拟具体跳法，只关心覆盖范围。",
            "O(n) 一遍扫描，O(1) 额外空间。",
            "与 min_jumps 共用 farthest 思想，本题只判可达性。",
            "enumerate(nums[:-1]) 最后一个元素无需再跳。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/greedy/greedy.py::min_jumps': _m(
        "45",
        "跳跃游戏 II",
        "给定长度为 n 的 0 索引整数数组 nums。初始位置为 nums[0]。每个元素 nums[i] 表示从 i 向前最多跳 nums[i] 步。\n\n返回到达 nums[n-1] 的最小跳跃次数。题目保证可以到达。\n\n约束：1 ≤ len(nums) ≤ 10^4，0 ≤ nums[i] ≤ 1000。",
        [
            "示例 1：nums = [2,3,1,1,4] → 2（0→1→4）",
            "示例 2：nums = [2,3,0,1,4] → 2",
        ],
        [
            "jumps 记录步数；current_end 为当前这一步能到达的最远边界；farthest 为扫描中的全局最远。",
            "for i in range(len(nums)-1)：更新 farthest = max(farthest, i+nums[i])。",
            "当 i == current_end，必须再跳一步：jumps += 1，current_end = farthest。",
            "循环结束 return jumps（n=1 时不进入循环，jumps=0 需题设 n>1 或特判）。",
        ],
        "贪心",
        code_notes=[
            "在 current_end 边界「被迫」增加 jumps，等价 BFS 层数。",
            "farthest 在本层内不断更新下一层边界。",
            "range(len-1) 因到达 n-1 即停止，不必从最后位置跳。",
            "与 can_jump 区别：求最少步数而非可达性。",
            "贪心正确性：每步尽量扩展最远边界。",
            "时间 O(n)，空间 O(1)。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/greedy/greedy.py::find_content_children': _m(
        "455",
        "分发饼干",
        "假设你有 g 个孩子和 s 块饼干，g[i] 是第 i 个孩子的胃口，s[j] 是第 j 块饼干的尺寸。\n\n每块饼干最多分给一个孩子，求最多能满足多少孩子（胃口 ≤ 饼干尺寸）。\n\n约束：1 ≤ len(g), len(s) ≤ 3×10^4。",
        [
            "示例 1：g = [1,2,3], s = [1,1] → 1",
            "示例 2：g = [1,2], s = [1,2,3] → 2",
        ],
        [
            "对 g 和 s 升序排序。",
            "child 指针指向当前待满足的最小胃口孩子。",
            "遍历每块 cookie：若 child < len(g) 且 g[child] <= cookie，child += 1（满足一个孩子）。",
            "return child 为满足的孩子数。",
        ],
        "贪心",
        code_notes=[
            "小饼干满足小胃口，排序后双指针线性匹配。",
            "cookie 遍历 s，child 只增不减。",
            "g[child] <= cookie 才 child++，否则换更大 cookie。",
            "未满足的 child 不会被跳过更小 cookie 误满足。",
            "时间 O(n log n + m log m) 排序主导。",
            "空间 O(1) 除排序。",
        ],
        complexity="时间 O(n log n + m log m)，空间 O(log n + log m) 排序栈。",
    ),
    'paradigms/greedy/greedy.py::largest_sum_after_k_negations': _m(
        "1005",
        "K 次取反后最大化的数组和",
        "给定整数数组 nums 和整数 k，按以下规则修改数组：选择下标 i 并将 nums[i] 替换为 -nums[i]，重复 k 次。\n\n返回修改后数组元素和的最大可能值。\n\n约束：1 ≤ len(nums) ≤ 10^4，-100 ≤ nums[i] ≤ 100，1 ≤ k ≤ 10^4。",
        [
            "示例 1：nums = [4,2,3], k = 1 → 5（-4 得 [-4,2,3] 和 1，应反 -4… 实际反 2 或策略：先反负数）",
            "示例 2：nums = [3,-1,0,2], k = 3 → 6",
            "示例 3：nums = [2,-3,-1,5,-4], k = 2 → 13",
        ],
        [
            "按绝对值降序排序 nums.sort(key=abs, reverse=True)。",
            "遍历：若 nums[i]<0 且 k>0，翻转 nums[i]，k -= 1。",
            "若 k 仍有剩余（奇数次），翻转绝对值最小元素 nums[-1]（排序后末尾）。",
            "return sum(nums)。",
        ],
        "贪心",
        code_notes=[
            "绝对值大的负数优先翻转，增益最大。",
            "k 偶数剩余时翻转同一元素两次抵消，奇数则翻最小绝对值损失最小。",
            "sort key=abs reverse=True 一次排序兼顾正负。",
            "全为正数时 k 奇数翻最小元素。",
            "时间 O(n log n)，空间 O(1)。",
            "也可用大根堆维护负数，逻辑等价。",
        ],
        complexity="时间 O(n log n)，空间 O(1)。",
    ),
    'paradigms/greedy/greedy.py::can_complete_circuit': _m(
        "134",
        "加油站",
        "在一条环路上有 n 个加油站，gas[i] 表示第 i 站油量，cost[i] 表示到下一站消耗。从 i 出发能绕一圈当且仅当沿途油量非负。\n\n若存在解，返回唯一起点下标，否则 -1。\n\n约束：n == len(gas) == len(cost)，1 ≤ n ≤ 10^5。",
        [
            "示例 1：gas = [1,2,3,4,5], cost = [3,4,5,1,2] → 3",
            "示例 2：gas = [2,3,4], cost = [3,4,3] → -1",
        ],
        [
            "遍历 i：diff = gas[i]-cost[i]，累加 current 和 total。",
            "若 current < 0，说明从当前 start 到 i 不可行，start = i+1，current 重置 0。",
            "total 为全程净油量；若 total < 0 无解 return -1。",
            "否则 return start。",
        ],
        "贪心",
        code_notes=[
            "total >= 0 则必有解（经典结论）。",
            "current < 0 时 start 必在 i+1 之后，之前起点均不可行。",
            "一次 O(n) 扫描确定起点，无需逐个模拟。",
            "diff 可正可负，current 为从 start 起的累积净油。",
            "环形问题化为线性+重置起点。",
            "时间 O(n)，空间 O(1)。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/greedy/greedy.py::candy': _m(
        "135",
        "分发糖果",
        "n 个孩子站成一排，ratings[i] 为第 i 个孩子评分。相邻孩子中评分高的必须获得更多糖果，每人至少 1 颗。\n\n求最少需要多少糖果。\n\n约束：n == len(ratings)，1 ≤ n ≤ 2×10^4，0 ≤ ratings[i] ≤ 2×10^4。",
        [
            "示例 1：ratings = [1,0,2] → 5（2,1,2 颗）",
            "示例 2：ratings = [1,2,2] → 4（1,2,1 颗）",
        ],
        [
            "candies 初始全 1。",
            "从左到右：若 ratings[i] > ratings[i-1]，candies[i] = candies[i-1]+1。",
            "从右到左：若 ratings[i] > ratings[i+1]，candies[i] = max(candies[i], candies[i+1]+1)。",
            "return sum(candies)。",
        ],
        "贪心",
        code_notes=[
            "两遍扫描分别满足左邻居和右邻居约束。",
            "第二遍 max 保留已满足的左侧约束。",
            "不能只一遍，如 [1,2,2] 需 [1,2,1] 非 [1,2,2]。",
            "O(n) 时间 O(n) 空间 candies 数组。",
            "也可单调栈，两遍更直观。",
            "经典「左右贪心」模板。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    'paradigms/greedy/greedy.py::lemonade_change': _m(
        "860",
        "柠檬水找零",
        "在柠檬水摊上，每杯 5 美元。顾客排队，bills[i] 为第 i 位付的钞票（5/10/20）。\n\n找零规则：20 优先 10+5，否则 3 张 5。判断能否给每位顾客正确找零。\n\n约束：1 ≤ len(bills) ≤ 10^5，bills[i] ∈ {5,10,20}。",
        [
            "示例 1：bills = [5,5,5,10,20] → True",
            "示例 2：bills = [5,5,10,10,20] → False",
        ],
        [
            "维护 five、ten 张数。",
            "bill==5：five += 1。",
            "bill==10：需一张 5 找零；无则 False，否则 five-=1, ten+=1。",
            "bill==20：优先 ten>0 且 five>0 各减 1；否则 five>=3 减 3；否则 False。",
            "全部处理完 return True。",
        ],
        "贪心",
        code_notes=[
            "20 找零优先消耗 10+5 保留 5 给未来 10 顾客。",
            "five 既收 5 元又作找零，是稀缺资源。",
            "无需记录 20 张数（只进不出）。",
            "贪心：大额找零尽量用大面额零钱。",
            "时间 O(n)，空间 O(1)。",
            "模拟题，按题意分支即可。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/greedy/greedy.py::reconstruct_queue': _m(
        "406",
        "根据身高重建队列",
        "people[i] = [h_i, k_i]：h_i 为身高，k_i 为前面不低于 h_i 的人数。重建原始队列。\n\n约束：1 ≤ len(people) ≤ 2000，0 ≤ h_i ≤ 10^6，0 ≤ k_i < len(people)。",
        [
            "示例：people = [[7,0],[4,4],[7,1],[5,0],[6,1],[5,2]] → [[5,0],[7,0],[5,2],[6,1],[4,4],[7,1]]",
        ],
        [
            "people.sort(key=lambda x: (-x[0], x[1]))：按身高降序，同身高 k 升序。",
            "queue 初始 []。",
            "按排序顺序对每个 person：queue.insert(person[1], person)。",
            "return queue。",
        ],
        "贪心",
        code_notes=[
            "先处理高个子，矮个子插入不影响高个子 k 计数。",
            "同身高 k 小先处理，insert 位置更靠前。",
            "insert(k) 即「前面已有 k 个不低于我的」。",
            "O(n^2) insert，n=2000 可过；树状数组可 O(n log n)。",
            "经典「排序+按 k 插入」贪心。",
            "key=(-h, k) 保证处理顺序正确。",
        ],
        complexity="时间 O(n^2)，空间 O(n)。",
    ),
    'paradigms/greedy/greedy.py::find_min_arrow_shots': _m(
        "452",
        "用最少数量的箭引爆气球",
        "二维平面有若干球形气球，points[i]=[x_start,x_end] 为水平直径。箭沿竖直方向射出，可引爆重叠区间。\n\n求引爆所有气球的最少箭数。\n\n约束：1 ≤ len(points) ≤ 10^5，0 ≤ x_start ≤ x_end ≤ 2^31-1。",
        [
            "示例 1：points = [[10,16],[2,8],[1,6],[7,12]] → 2",
            "示例 2：points = [[1,2],[3,4],[5,6],[7,8]] → 4",
        ],
        [
            "空 return 0；按 x_start 升序排序。",
            "arrows=1，end=points[0][1] 为第一箭位置（右端点贪心）。",
            "遍历 i=1..n-1：若 points[i][0] > end，需新箭 arrows++，end=points[i][1]。",
            "否则重叠，end = min(end, points[i][1]) 缩小公共区间。",
            "return arrows。",
        ],
        "贪心",
        code_notes=[
            "按起点排序后，箭打在重叠区间的右端点最优。",
            "points[i][0] > end 表示与当前箭区间无交，必须新箭。",
            "min(end, points[i][1]) 保留更窄重叠，便于后续共享。",
            "与 erase_overlap_intervals 同「按右端点贪心」思想。",
            "也可按右端点排序，逻辑等价。",
            "时间 O(n log n)，空间 O(1)。",
        ],
        complexity="时间 O(n log n)，空间 O(1)。",
    ),
    'paradigms/greedy/greedy.py::erase_overlap_intervals': _m(
        "435",
        "无重叠区间",
        "给定区间集合 intervals，移除最少区间使剩余区间互不重叠。\n\n返回需要移除的区间最小数量。\n\n约束：1 ≤ len(intervals) ≤ 10^5，intervals[i].length==2，-5×10^4 ≤ start < end ≤ 5×10^4。",
        [
            "示例 1：intervals = [[1,2],[2,3],[3,4],[1,3]] → 1（移除 [1,3]）",
            "示例 2：intervals = [[1,2],[1,2],[1,2]] → 2",
        ],
        [
            "按 start 升序排序（也可按 end，本实现按 start）。",
            "kept=1 保留区间数，end=intervals[0][1]。",
            "遍历后续：若 start >= end 不重叠，kept++，end=intervals[i][1]。",
            "否则重叠，end = min(end, intervals[i][1]) 保留右端更小者。",
            "return len(intervals) - kept。",
        ],
        "贪心",
        code_notes=[
            "保留更多区间 = 移除更少；贪心保留右端点小的区间。",
            "start >= end 判定无重叠（闭区间相邻 [1,2],[2,3] 不重叠）。",
            "kept 为最多非重叠区间数，答案 = n - kept。",
            "与活动选择问题等价。",
            "按 end 排序是更常见写法，按 start 需 min(end) 更新。",
            "时间 O(n log n)，空间 O(1)。",
        ],
        complexity="时间 O(n log n)，空间 O(1)。",
    ),
    'paradigms/greedy/greedy.py::partition_labels': _m(
        "763",
        "划分字母区间",
        "字符串 s 由小写字母组成。划分成尽可能多的片段，同一字母最多出现在一个片段中。\n\n返回每个片段的长度。\n\n约束：1 ≤ len(s) ≤ 500，s 仅小写字母。",
        [
            "示例 1：s = \"ababcbacadefegdehijhklij\" → [9,7,8]",
            "示例 2：s = \"eccbbbbdec\" → [10]",
        ],
        [
            "预处理 last[ch] 为字符 ch 最后出现下标。",
            "遍历 i：end = max(end, last[s[i]]) 扩展当前片段右边界。",
            "当 i == end，片段结束，append(end-start+1) 到 result，start=i+1。",
            "return result。",
        ],
        "贪心",
        code_notes=[
            "同一字母最后出现位置决定片段最小右边界。",
            "i 未达 end 前不能切分，否则字母会跨片段。",
            "i==end 时切分最优（尽量早切获得最多片段）。",
            "O(n) 两遍：建 last + 扫描。",
            "与 merge intervals 类似，字符区间为 [first,last]。",
            "时间 O(n)，空间 O(1) 字母表 26。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/greedy/greedy.py::merge_intervals': _m(
        "56",
        "合并区间",
        "以数组 intervals 表示若干区间，其中 intervals[i]=[start_i,end_i]。合并所有重叠区间。\n\n约束：1 ≤ len(intervals) ≤ 10^4，intervals[i].length==2，0 ≤ start_i ≤ end_i ≤ 10^4。",
        [
            "示例 1：intervals = [[1,3],[2,6],[8,10],[15,18]] → [[1,6],[8,10],[15,18]]",
            "示例 2：intervals = [[1,4],[4,5]] → [[1,5]]",
        ],
        [
            "按 start 升序排序 intervals。",
            "merged = [intervals[0]]。",
            "遍历后续 [start,end]：若 merged[-1][1] >= start，重叠，merged[-1][1]=max(merged[-1][1],end)。",
            "否则 append [start,end] 新区间。",
            "return merged。",
        ],
        "贪心",
        code_notes=[
            "排序后只需与 merged 最后一个比较。",
            "merged[-1][1] >= start 含相邻闭区间 [1,4],[4,5]。",
            "max 扩展右端覆盖更大重叠。",
            "O(n log n) 排序 + O(n) 合并。",
            "扫描线或区间贪心基础题。",
            "空 intervals 返回 []。",
        ],
        complexity="时间 O(n log n)，空间 O(n) 结果。",
    ),
    'paradigms/greedy/greedy.py::monotone_increasing_digits': _m(
        "738",
        "单调递增的数字",
        "给定非负整数 n，返回小于等于 n 的最大单调递增整数（各位数字从左到右非严格递增）。\n\n约束：0 ≤ n ≤ 10^9。",
        [
            "示例 1：n = 10 → 9",
            "示例 2：n = 1234 → 1234",
            "示例 3：n = 332 → 299",
        ],
        [
            "digits = list(str(n))。",
            "从低位向高位扫描 i=len-1..1：若 digits[i-1] > digits[i]，下降位在 i-1。",
            "digits[i-1] 减 1；i..末尾全部置 '9'。",
            "return int(''.join(digits))。",
        ],
        "贪心",
        code_notes=[
            "第一个下降位左侧减 1，右侧全 9 得最大合法值。",
            "从右向左保证处理最低下降位（如 332→329→299）。",
            "已是单调则不变。",
            "字符串操作避免整数借位复杂性。",
            "也可逐位贪心从高位，本实现从低位找下降。",
            "时间 O(log n) 位数，空间 O(log n)。",
        ],
        complexity="时间 O(log n)，空间 O(log n)。",
    ),
    'paradigms/greedy/greedy.py::get_kth_magic_number': _m(
        "313",
        "超级丑数",
        "超级丑数是一个正整数，其所有质因数都在 primes=[3,5,7] 中。给定 k，返回第 k 个超级丑数。\n\n约束：1 ≤ k ≤ 440，本实现固定因子 3,5,7。",
        [
            "示例 1：k = 1 → 1",
            "示例 2：k = 5 → 12（序列为 1,3,5,7,9,10,12…）",
            "示例 3：k = 17 → 45",
        ],
        [
            "dp[0]=1；p3=p5=p7=0 三个指针指向各因子最后使用下标。",
            "for i in 1..k-1：dp[i] = min(dp[p3]*3, dp[p5]*5, dp[p7]*7)。",
            "若 dp[i] 等于某乘积，对应指针 += 1（多个相等则都移动，防重复）。",
            "return dp[k-1]。",
        ],
        "贪心",
        code_notes=[
            "多路归并，类似 Ugly Number II。",
            "三指针保证每个丑数只生成一次。",
            "相等时三个 if 独立判断，可能同时 p3,p5,p7++。",
            "dp 长度 k，O(k) 时间。",
            "可推广到 primes 列表可变长度。",
            "时间 O(k)，空间 O(k)。",
        ],
        complexity="时间 O(k)，空间 O(k)。",
    ),
    'paradigms/dynamic_programming/grid_dp.py::unique_paths': _m(
        "62",
        "不同路径",
        "机器人位于 m×n 网格左上角，每次只能向右或向下，到达右下角有多少条不同路径？\n\n约束：1 ≤ m, n ≤ 100。",
        [
            "示例 1：m = 3, n = 7 → 28",
            "示例 2：m = 3, n = 2 → 3",
        ],
        [
            "定义 dp[i][j] 为从 (0,0) 到 (i,j) 的路径数；第一行、第一列边界均为 1。",
            "用一行滚动数组 row 长度 n 代替二维表，初始 row = [1]*n 表示首行全为 1。",
            "外层 for 遍历第 2 行到第 m 行（i=1..m-1），内层 j 从 1 到 n-1 更新。",
            "转移 row[j] += row[j-1]：row[j] 更新前为上方 dp[i-1][j]，row[j-1] 为本行左邻。",
            "全部行处理完毕后 return row[-1]，即右下角 (m-1,n-1) 的路径总数。",
        ],
        "动态规划",
        code_notes=[
            "dp[i][j] = dp[i-1][j] + dp[i][j-1]，边界第一行第一列均为 1。",
            "滚动一行优化空间 O(n)。",
            "组合数学答案 C(m+n-2, m-1) 亦可。",
            "内层 j 从左到右，row[j-1] 已是本行左邻。",
            "经典二维路径计数 DP。",
            "时间 O(m·n)，空间 O(n)。",
        ],
        complexity="时间 O(m·n)，空间 O(n)。",
    ),
    'paradigms/dynamic_programming/grid_dp.py::unique_paths_with_obstacles': _m(
        "63",
        "不同路径 II",
        "m×n 网格，obstacle_grid[i][j]=1 表示障碍。从左上到右下只能右/下，求不同路径数。\n\n约束：1 ≤ m, n ≤ 100，obstacle_grid[0][0] 保证为 0。",
        [
            "示例 1：obstacleGrid = [[0,0,0],[0,1,0],[0,0,0]] → 2",
            "示例 2：obstacleGrid = [[0,1],[0,0]] → 1",
        ],
        [
            "若 obstacle_grid[0][0]==1  return 0。",
            "初始化 dp 第一行：遇 1 则 break 后均为 0，否则 dp[j]=1。",
            "逐行：若 obstacle[i][0]==1 则 dp[0]=0；内层 j 遇障碍 dp[j]=0 否则 dp[j]+=dp[j-1]。",
            "return dp[-1]。",
        ],
        "动态规划",
        code_notes=[
            "障碍格 dp=0，不可达。",
            "第一行/列遇障碍后后续 dp 保持 0（break 或赋值 0）。",
            "滚动数组同 unique_paths。",
            "起点障碍特判 return 0。",
            "时间 O(m·n)，空间 O(n)。",
            "与 62 区别：障碍置零。",
        ],
        complexity="时间 O(m·n)，空间 O(n)。",
    ),
    'paradigms/dynamic_programming/grid_dp.py::min_path_sum': _m(
        "64",
        "最小路径和",
        "给定 m×n 网格 grid，每条路径从左上到右只能右或下，求路径上数字和的最小值。\n\n约束：1 ≤ m, n ≤ 200，-200 ≤ grid[i][j] ≤ 200。",
        [
            "示例 1：grid = [[1,3,1],[1,5,1],[4,2,1]] → 7（1→3→1→1→1）",
            "示例 2：grid = [[1,2,3],[4,5,6]] → 12",
        ],
        [
            "dp[j] 表示到达当前行第 j 列的最小路径和；初始化 dp = [0]*n。",
            "外层遍历每一行 i=0..m-1：先将 grid[i][0] 累加到 dp[0]（处理第一列只能向下）。",
            "内层 j=1..n-1：dp[j] = min(dp[j-1], dp[j]) + grid[i][j]，左邻与本行上方取较小再加当前格。",
            "更新前 dp[j] 存的是上一行同列值，dp[j-1] 已是本行左邻，符合 min(上,左) 转移。",
            "全部行遍历后 return dp[-1]，即到达右下角的最小路径和。",
        ],
        "动态规划",
        code_notes=[
            "dp[i][j] = min(上,左) + grid[i][j]。",
            "第一列 dp[0] 每行 += grid[i][0] 累加。",
            "滚动一行，dp[j] 更新前存的是上方值。",
            "可原地改 grid 省空间。",
            "与 max_path_sum 仅 min/max 不同。",
            "时间 O(m·n)，空间 O(n)。",
        ],
        complexity="时间 O(m·n)，空间 O(n)。",
    ),
    'paradigms/dynamic_programming/grid_dp.py::max_path_sum': _m(
        "",
        "网格最大路径和",
        "给定 m×n 整数网格 grid，从左上角到右下角，每步只能向右或向下移动，求路径上数字和的最大值。\n\n本题为 min_path_sum 的 max 变体，DP 转移取 max 而非 min。\n\n约束：1 ≤ m, n ≤ 200。",
        [
            "示例：grid = [[1,3,1],[1,5,1],[4,2,1]] → 12（走 1→5→4→2→1 等最大路径）",
        ],
        [
            "dp[j] 表示到达当前行第 j 列的最大路径和；初始化 dp = [0]*n。",
            "外层遍历每一行 i=0..m-1：将 grid[i][0] 累加到 dp[0]（第一列只能向下走）。",
            "内层 j=1..n-1：dp[j] = max(dp[j-1], dp[j]) + grid[i][j]，从左边或上方选较大路径再加当前格。",
            "滚动一行时 dp[j] 更新前代表上方值，dp[j-1] 代表本行左邻，与 min_path_sum 仅 min/max 不同。",
            "遍历完所有行后 return dp[-1]，即右下角的最大路径和。",
        ],
        "动态规划",
        code_notes=[
            "与 min_path_sum 结构完全相同，min 改 max。",
            "第一列累加、滚动数组优化 O(n) 空间。",
            "边界：单格即 grid[0][0]。",
            "可用于对比 min/max DP 模板。",
            "时间 O(m·n)，空间 O(n)。",
            "非 LeetCode 原题，为库内扩展练习。",
        ],
        complexity="时间 O(m·n)，空间 O(n)。",
    ),
    'paradigms/dynamic_programming/grid_dp.py::minimal_triangle_path': _m(
        "120",
        "三角形最小路径和",
        "给定三角形 triangle，找出自顶到底的最小路径和。每步只能移动到下一行相邻格子。\n\n约束：1 ≤ triangle.length ≤ 200，-10^4 ≤ triangle[i][j] ≤ 10^4。",
        [
            "示例 1：triangle = [[2],[3,4],[6,5,7],[4,1,8,3]] → 11（2+3+5+1）",
            "示例 2：triangle = [[-10]] → -10",
        ],
        [
            "自底向上：row 从 1 到 len-1 遍历。",
            "对 row 行每个 col：left = 上一行 col-1（边界取 0 或上一行 0），right = 上一行 col。",
            "triangle[row][col] += min(left, right)。",
            "return min(triangle[-1])。",
        ],
        "动态规划",
        code_notes=[
            "原地修改 triangle 省 O(n) 空间。",
            "col==0 时 left 取 triangle[row-1][0]；col 超界时 right 取 [-1]。",
            "自顶向下亦可，自底向上避免额外 dp 表。",
            "最后一行 min 即答案。",
            "时间 O(n^2) 总格子数，空间 O(1) 原地。",
            "边界 triangle 空 return 0。",
        ],
        complexity="时间 O(n^2)，空间 O(1) 原地。",
    ),
    'paradigms/dynamic_programming/grid_dp.py::maximal_square': _m(
        "221",
        "最大正方形",
        "给定 m×n 二进制矩阵 matrix，找出只包含 1 的最大正方形面积。\n\n约束：1 ≤ m, n ≤ 300，matrix[i][j] 为 '0' 或 '1'。",
        [
            "示例 1：matrix = [[\"1\",\"0\",\"1\",\"0\",\"0\"],[\"1\",\"0\",\"1\",\"1\",\"1\"],[\"1\",\"1\",\"1\",\"1\",\"1\"],[\"1\",\"0\",\"0\",\"1\",\"0\"]] → 4",
            "示例 2：matrix = [[\"0\",\"1\"],[\"1\",\"0\"]] → 1",
        ],
        [
            "dp 尺寸 (m+1)×(n+1) 带 padding，dp[i][j] 表示以 (i-1,j-1) 为右下角的最大正方形边长。",
            "若 matrix[i-1][j-1]=='1'：dp[i][j] = min(上,左,左上)+1。",
            "best = max(best, dp[i][j])。",
            "return best * best 为面积。",
        ],
        "动态规划",
        code_notes=[
            "三邻 min+1：正方形需左上、上、左 均至少边长 k-1。",
            "padding 避免边界判零。",
            "matrix 存字符 '0'/'1'，比较用 =='1'。",
            "best 记录最大边长，返回平方为面积。",
            "时间 O(m·n)，空间 O(m·n) 可滚动优化。",
            "histogram+单调栈是 O(mn) 另一解法。",
        ],
        complexity="时间 O(m·n)，空间 O(m·n)。",
    ),
    'paradigms/dynamic_programming/grid_dp.py::min_swap': _m(
        "801",
        "使序列递增的最小交换次数",
        "给定两个等长数组 nums1、nums2，可在同一位置 i 交换 nums1[i] 与 nums2[i]。求使 nums1 严格递增的最小交换次数，无解返回 -1 逻辑由 min 体现。\n\n约束：2 ≤ n ≤ 10^5，0 ≤ nums1[i], nums2[i] ≤ 2×10^9。",
        [
            "示例 1：nums1 = [1,3,5,4], nums2 = [1,2,3,7] → 1",
            "示例 2：nums1 = [0,3,5,8,9,11,14,17,17,18,19,20,22,25,26,29,30,31,32,33], nums2 = [3,5,8,9,11,14,17,17,18,19,20,22,25,26,29,30,31,32,33,0] → 2",
        ],
        [
            "keep=不交换累计次数，swap=交换累计次数；初始 keep=0, swap=1。",
            "i 从 1 遍历：计算 keep2/swap2 为无穷大初值。",
            "若 nums1[i]>nums1[i-1] 且 nums2[i]>nums2[i-1]：keep2=min(keep2,keep)，swap2=min(swap2,swap+1)。",
            "若 nums1[i]>nums2[i-1] 且 nums2[i]>nums1[i-1]：keep2=min(keep2,swap)，swap2=min(swap2,keep+1)。",
            "keep,swap = keep2,swap2；return min(keep,swap)。",
        ],
        "动态规划",
        code_notes=[
            "双状态 DP：位置 i 交换/不交换两种递增方案。",
            "交叉比较 nums1[i] vs nums2[i-1] 处理交换后递增约束。",
            "keep2/swap2 用 n 初值表示不可达，最后 min 取可行最小。",
            "O(n) 时间 O(1) 空间。",
            "与股票状态机类似，两状态转移。",
            "无有效转移时 min 可能很大，题设保证有解或需特判。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/dynamic_programming/grid_dp.py::stone_game': _m(
        "877",
        "石子游戏",
        "Alice 和 Bob 轮流从 piles 两端取石子，Alice 先手。各自得分为自己取的石子数。若 Alice 得分严格大于 Bob 返回 true。\n\n约束：2 ≤ len(piles) ≤ 500，len(piles) 为偶数，1 ≤ piles[i] ≤ 500。",
        [
            "示例 1：piles = [5,3,4,5] → True",
            "示例 2：piles = [3,2,1] → 若长度为偶数题设… [3,2,1,4] → 视具体",
        ],
        [
            "区间 DP：dp[i][j] 表示 piles[i..j] 上当前玩家相对对手的最大净胜分。",
            "初始化 dp[i][i]=piles[i]。",
            "i 从 n-2 到 0，j 从 i+1 到 n-1：dp[i][j]=max(piles[i]-dp[i+1][j], piles[j]-dp[i][j-1])。",
            "return dp[0][n-1] > 0。",
        ],
        "动态规划",
        code_notes=[
            "dp[i][j] 为差值分数，非绝对得分。",
            "取左 piles[i]-dp[i+1][j]：对手在子区间净胜 dp，我取左得 piles[i] 减对手优势。",
            "偶数堆保证先手必胜（LeetCode 结论），DP 通用奇偶长度。",
            "O(n^2) 时间空间。",
            "与 predict_the_winner 同题。",
            "区间 DP 经典模板。",
        ],
        complexity="时间 O(n^2)，空间 O(n^2)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::zero_one_knapsack': _m(
        "",
        "01 背包",
        "有 n 件物品，第 i 件重量 weight[i]、价值 value[i]，每件最多选一次。在容量 capacity 限制下求最大价值。\n\n本实现滚动数组一维 DP，逆序遍历容量。\n\n约束：典型 1 ≤ n ≤ 100，1 ≤ capacity ≤ 10^4。",
        [
            "示例：weight = [1,3,4], value = [15,20,30], capacity = 4 → 35（选物品 1 和 3）",
        ],
        [
            "dp[j] 表示容量 j 的最大价值，初值全 0。",
            "对每个物品 i：for j from capacity down to weight[i]：dp[j] = max(dp[j], dp[j-weight[i]]+value[i])。",
            "逆序保证每件物品只使用一次（01 性质）。",
            "return dp[capacity]。",
        ],
        "动态规划",
        code_notes=[
            "dp[j-weight[i]] 是不含当前物品的子问题。",
            "j 递减防止同一轮重复使用物品 i。",
            "二维 dp[i][j] 可压缩为一维。",
            "many 子问题（划分和、目标和）的基础模型。",
            "时间 O(n·capacity)，空间 O(capacity)。",
            "与完全背包正序遍历对比学习。",
        ],
        complexity="时间 O(n·capacity)，空间 O(capacity)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::complete_knapsack': _m(
        "",
        "完全背包",
        "每种物品重量 weight[i]、价值 value[i]，每种无限次选取，容量 capacity 下求最大价值。\n\n与 01 背包区别：内层 j 正序遍历。\n\n约束：1 ≤ n ≤ 100，1 ≤ capacity ≤ 10^4。",
        [
            "示例：weight = [1,3,4], value = [15,20,30], capacity = 4 → 60（4 个重量 1）",
        ],
        [
            "dp 长度 capacity+1，初值 0。",
            "对每个物品 i：for j from weight[i] to capacity：dp[j] = max(dp[j], dp[j-weight[i]]+value[i])。",
            "正序 j 允许同一物品多次贡献。",
            "return dp[capacity]。",
        ],
        "动态规划",
        code_notes=[
            "正序：dp[j-weight[i]] 可能已含物品 i，再加一次。",
            "coin_change_min、完全平方数等为完全背包变形。",
            "物品顺序无关，常外层物品内层容量。",
            "时间 O(n·capacity)，空间 O(capacity)。",
            "与 01 背包仅遍历方向不同。",
            "二维 dp[i][j]=max(dp[i-1][j], dp[i][j-w]+v) 一维化。",
        ],
        complexity="时间 O(n·capacity)，空间 O(capacity)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::can_partition': _m(
        "416",
        "分割等和子集",
        "给定非空正整数数组 nums，能否将数组分割成两个子集，使两子集元素和相等。\n\n约束：1 ≤ len(nums) ≤ 200，1 ≤ nums[i] ≤ 100。",
        [
            "示例 1：nums = [1,5,11,5] → True（{1,5,5} 与 {11}）",
            "示例 2：nums = [1,2,3,5] → False",
        ],
        [
            "total = sum(nums)；若 total 为奇数 return False。",
            "target = total // 2，01 背包：dp[0..target] 布尔，dp[0]=True。",
            "对每个 num：j 从 target  downto num：dp[j] |= dp[j-num]。",
            "return dp[target]。",
        ],
        "动态规划",
        code_notes=[
            "等价于是否存在子集和为 sum/2。",
            "奇数和直接不可分。",
            "布尔 DP 而非最大价值。",
            "逆序 01 背包，每个 num 用一次。",
            "时间 O(n·target)，空间 O(target)。",
            "与 target_sum_ways 计数版对比。",
        ],
        complexity="时间 O(n·sum)，空间 O(sum)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::last_stone_weight_ii': _m(
        "1049",
        "最后一块石头的重量 II",
        "有一堆石头，每次选两块最重的 smash：同重则都碎，不同重则轻的碎、重的变为差值。求最后最多剩一块石头的最小可能重量。\n\n约束：1 ≤ len(stones) ≤ 30，1 ≤ stones[i] ≤ 100。",
        [
            "示例 1：stones = [2,7,4,1,8,1] → 1",
            "示例 2：stones = [31,26,33,21,40] → 5",
        ],
        [
            "计算 total = sum(stones)，target = total // 2；问题转化为找不超过 target 的最大子集和。",
            "初始化 dp = [0]*(target+1)，dp[j] 表示容量 j 下能装入的最大石头重量和。",
            "对每个 stone 逆序遍历 j=target..stone：dp[j] = max(dp[j], dp[j-stone]+stone)，01 背包每件最多一次。",
            "dp[target] 即为最接近 total/2 的一堆重量；另一堆为 total - dp[target]。",
            "return total - 2*dp[target]，即两堆重量差的最小值，也就是最后剩余石头的重量。",
        ],
        "动态规划",
        code_notes=[
            "等价将石头分成两堆，最小化 |sum1-sum2|。",
            "dp[j] 最大可达和，非布尔。",
            "total - 2*best 为两堆差，即最后石头重量。",
            "与 can_partition 判等不同，此处求最接近一半。",
            "n=30 可 bitset 优化。",
            "时间 O(n·target)，空间 O(target)。",
        ],
        complexity="时间 O(n·sum)，空间 O(sum)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::target_sum_ways': _m(
        "494",
        "目标和",
        "给 nums 每个数前加 + 或 -，使表达式结果等于 target，求方案数。\n\n约束：1 ≤ len(nums) ≤ 20，0 ≤ nums[i] ≤ 1000，0 ≤ sum(nums) ≤ 1000，-1000 ≤ target ≤ 1000。",
        [
            "示例 1：nums = [1,1,1,1,1], target = 3 → 5",
            "示例 2：nums = [1], target = 1 → 1",
        ],
        [
            "若 abs(target)>total 或 (target+total) 为奇数 return 0。",
            "bag_size = (target+total)//2，即正数和子集目标。",
            "dp[0]=1，对每个 num 逆序 j：dp[j]+=dp[j-num]。",
            "return dp[bag_size]。",
        ],
        "动态规划",
        code_notes=[
            "设正部和为 P，负部和为 N，P-N=target，P+N=total → P=(target+total)/2。",
            "转化为和为 bag_size 的子集计数 01 背包。",
            "dp 存方案数非 bool。",
            "奇偶性剪枝提前 return 0。",
            "时间 O(n·bag_size)，空间 O(bag_size)。",
            "与 coin_change_combinations 计数结构类似。",
        ],
        complexity="时间 O(n·sum)，空间 O(sum)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::coin_change_combinations': _m(
        "518",
        "零钱兑换 II",
        "给定不同面额硬币 coins 和总金额 amount，计算凑成总金额的组合数（硬币顺序无关）。\n\n约束：1 ≤ len(coins) ≤ 300，0 ≤ coins[i] ≤ 5000，0 ≤ amount ≤ 5000。",
        [
            "示例 1：amount = 5, coins = [1,2,5] → 4",
            "示例 2：amount = 3, coins = [2] → 0",
        ],
        [
            "dp[0]=1，其余 0。",
            "外层 coin，内层 j 从 coin 到 amount 正序：dp[j]+=dp[j-coin]。",
            "外层物品内层容量 → 组合型完全背包。",
            "return dp[amount]。",
        ],
        "动态规划",
        code_notes=[
            "与 combination_sum4 区别：此处顺序无关（组合），377 为排列。",
            "dp[j]+=dp[j-coin] 累加方案数。",
            "coin 外层保证 [1,2] 与 [2,1] 算一种。",
            "amount=0 时 dp[0]=1 一种空组合。",
            "时间 O(len(coins)·amount)，空间 O(amount)。",
            "完全背包计数模板。",
        ],
        complexity="时间 O(n·amount)，空间 O(amount)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::combination_sum4': _m(
        "377",
        "组合总和 IV",
        "给定不同正整数 nums 和目标 target，nums 元素可重复，顺序不同视为不同组合，求组合数。\n\n约束：1 ≤ len(nums) ≤ 200，1 ≤ nums[i] ≤ 1000，1 ≤ target ≤ 1000。",
        [
            "示例 1：nums = [1,2,3], target = 4 → 7",
            "示例 2：nums = [9], target = 3 → 0",
        ],
        [
            "dp[0]=1。",
            "外层 i 从 1 到 target（目标和），内层 num in nums：若 i>=num 则 dp[i]+=dp[i-num]。",
            "目标和外层 → 排列型完全背包。",
            "return dp[target]。",
        ],
        "动态规划",
        code_notes=[
            "i 外层 num 内层：先定总和再选最后数字，顺序敏感。",
            "与 518 内外层对调是组合/排列核心区别。",
            "dp[i] 为凑 i 的方案数。",
            "完全背包计数，正整数 nums。",
            "时间 O(target·n)，空间 O(target)。",
            "可记忆化 DFS 等价。",
        ],
        complexity="时间 O(target·n)，空间 O(target)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::coin_change_min': _m(
        "322",
        "零钱兑换",
        "给定 coins 不同面额和 amount，凑总金额所需最少硬币数；无法凑成 return -1。\n\n约束：1 ≤ len(coins) ≤ 12，1 ≤ coins[i] ≤ 2^31-1，0 ≤ amount ≤ 10^4。",
        [
            "示例 1：coins = [1,2,5], amount = 11 → 3（5+5+1）",
            "示例 2：coins = [2], amount = 3 → -1",
        ],
        [
            "dp[0]=0，其余 inf。",
            "每个 coin：j 从 coin 到 amount：dp[j]=min(dp[j], dp[j-coin]+1)。",
            "完全背包求 min。",
            "return -1 if dp[amount]==inf else dp[amount]。",
        ],
        "动态规划",
        code_notes=[
            "dp[j-coin]+1 表示最后一枚 coin 面额。",
            "初值 inf 表示不可达。",
            "BFS 也可求最短步数。",
            "coin 外层或内层均可（min 问题）。",
            "时间 O(n·amount)，空间 O(amount)。",
            "amount=0 返回 0。",
        ],
        complexity="时间 O(n·amount)，空间 O(amount)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::num_squares': _m(
        "279",
        "完全平方数",
        "给定 n，返回和为 n 的完全平方数的最少数量。\n\n约束：1 ≤ n ≤ 10^4。",
        [
            "示例 1：n = 12 → 3（4+4+4）",
            "示例 2：n = 13 → 2（4+9）",
        ],
        [
            "dp[0]=0，其余 inf。",
            "i 从 1 到 n：j=1 while j*j<=i：dp[i]=min(dp[i], dp[i-j*j]+1)。",
            "每个完全平方 j*j 视为物品，无限次。",
            "return dp[n]。",
        ],
        "动态规划",
        code_notes=[
            "完全背包 min，物品为平方数。",
            "j*j 内层循环枚举平方因子。",
            "Lagrange 四平方定理：答案最多 4，但 DP 通用。",
            "BFS 层数亦可行。",
            "时间 O(n·√n)，空间 O(n)。",
            "dp[i-j*j]+1 最后一项为 j²。",
        ],
        complexity="时间 O(n·√n)，空间 O(n)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::word_break': _m(
        "139",
        "单词拆分",
        "给定字符串 s 和字典 wordDict，能否将 s 拆分为空格分隔的若干字典单词。\n\n约束：1 ≤ len(s) ≤ 300，1 ≤ len(wordDict) ≤ 1000，单词可重复使用。",
        [
            "示例 1：s = \"leetcode\", wordDict = [\"leet\",\"code\"] → True",
            "示例 2：s = \"applepenapple\", wordDict = [\"apple\",\"pen\"] → True",
            "示例 3：s = \"catsandog\", wordDict = [\"cats\",\"dog\",\"sand\",\"and\",\"cat\"] → False",
        ],
        [
            "dp[0]=True，dp[j] 表示 s[:j] 可否拆分。",
            "j 从 1 到 len(s)：遍历 word in wordDict。",
            "若 j>=len(word) 且 dp[j-len(word)] 且 s[j-len: j]==word，则 dp[j]=True，break。",
            "return dp[len(s)]。",
        ],
        "动态规划",
        code_notes=[
            "dp[j-len(word)] 为前缀可拆分，当前 word 为后缀。",
            "words=set(wordDict) 可 O(1) 查，本实现遍历 wordDict。",
            "找到一种拆分即 break 内层。",
            "与 word_break II 求所有拆分对比。",
            "时间 O(n^2·字典大小) 或 Trie 优化。",
            "完全背包「字符串划分」模型。",
        ],
        complexity="时间 O(n^2·|wordDict|)，空间 O(n)。",
    ),
    'paradigms/dynamic_programming/knapsack.py::find_max_form': _m(
        "474",
        "一和零",
        "给定二进制字符串数组 strs 和 m、n，从数组选子集，最多 m 个 0、n 个 1，求子集最大个数。\n\n约束：1 ≤ len(strs) ≤ 600，1 ≤ strs[i].length ≤ 100，1 ≤ m,n ≤ 100。",
        [
            "示例 1：strs = [\"10\",\"0001\",\"111001\",\"1\",\"0\"], m = 5, n = 3 → 4",
            "示例 2：strs = [\"10\",\"0\",\"1\"], m = 1, n = 1 → 2",
        ],
        [
            "二维 01 背包 dp[i][j]：i 个 0、j 个 1 时最多选几个串。",
            "对每个 s：zeros=s.count('0'), ones=s.count('1')。",
            "i 从 m downto zeros，j 从 n downto ones：dp[i][j]=max(dp[i][j], dp[i-zeros][j-ones]+1)。",
            "return dp[m][n]。",
        ],
        "动态规划",
        code_notes=[
            "价值恒为 1（选一个串），重量二维 (0 数, 1 数)。",
            "逆序 i,j 保证每个 str 最多用一次。",
            "zeros/ones 预处理每串代价。",
            "二维费用 01 背包模板。",
            "时间 O(len(strs)·m·n)，空间 O(m·n)。",
            "可滚动一维需 careful 二维逆序。",
        ],
        complexity="时间 O(len(strs)·m·n)，空间 O(m·n)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::longest_common_subsequence': _m(
        "1143",
        "最长公共子序列",
        "给定两个字符串 text1 和 text2，返回二者最长公共子序列长度。子序列不要求连续。\n\n约束：1 ≤ len(text1), len(text2) ≤ 1000。",
        [
            "示例 1：text1 = \"abcde\", text2 = \"ace\" → 3（\"ace\"）",
            "示例 2：text1 = \"abc\", text2 = \"abc\" → 3",
        ],
        [
            "dp[i][j] 为 text1[:i] 与 text2[:j] 的 LCS 长度，表尺寸 (len1+1)×(len2+1)。",
            "若 text1[i-1]==text2[j-1]：dp[i][j]=dp[i-1][j-1]+1。",
            "否则 dp[i][j]=max(dp[i-1][j], dp[i][j-1])。",
            "return dp[-1][-1]。",
        ],
        "动态规划",
        code_notes=[
            "经典双串 DP，匹配则斜角+1，否则 max(上,左)。",
            "空串一行一列初值 0。",
            "可滚动一行优化空间 O(min(m,n))。",
            "LCS 是许多题基础（583 删除操作、1035 不相交线）。",
            "时间 O(m·n)，空间 O(m·n)。",
            "回溯可构造具体 LCS。",
        ],
        complexity="时间 O(m·n)，空间 O(m·n)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::longest_common_subarray': _m(
        "718",
        "最长重复子数组",
        "给两个整数数组 nums1、nums2，返回两个数组中公共的、长度最长的连续子数组长度。\n\n约束：1 ≤ len(nums1), len(nums2) ≤ 1000，0 ≤ nums[i] ≤ 100。",
        [
            "示例 1：nums1 = [1,2,3,2,1], nums2 = [3,2,1,4,7] → 3（[3,2,1]）",
            "示例 2：nums1 = [0,0,0,0,0], nums2 = [0,0,0,0,0] → 5",
        ],
        [
            "dp[i][j] 表示以 nums1[i-1]、nums2[j-1] 结尾的最长公共子数组长度。",
            "相等时 dp[i][j]=dp[i-1][j-1]+1，否则 0（必须连续）。",
            "best 记录全局最大 dp[i][j]。",
            "return best。",
        ],
        "动态规划",
        code_notes=[
            "与 LCS 区别：不等时置 0 而非 max(上,左)。",
            "best 因 dp 值会重置需全局 max。",
            "可压缩为一维 rolling。",
            "时间 O(m·n)，空间 O(m·n)。",
            "滑动窗口+哈希另解。",
            "连续子数组必须末尾同时匹配。",
        ],
        complexity="时间 O(m·n)，空间 O(m·n)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::max_uncrossed_lines': _m(
        "1035",
        "不相交的线",
        "给定 nums1、nums2，在两条水平线上各画点，相等值可连线。线不相交的最大条数。\n\n约束：1 ≤ len(nums1), len(nums2) ≤ 500，1 ≤ nums[i] ≤ 2000。",
        [
            "示例 1：nums1 = [1,4,2], nums2 = [1,2,4] → 2",
            "示例 2：nums1 = [2,5,1,2,5], nums2 = [10,5,2,1,5,2] → 3",
        ],
        [
            "等价 LCS：dp 同 longest_common_subsequence。",
            "相等 nums1[i-1]==nums2[j-1]：dp[i][j]=dp[i-1][j-1]+1。",
            "不等 max(上,左)。",
            "return dp[-1][-1]。",
        ],
        "动态规划",
        code_notes=[
            "不相交连线 ⟺ 按序配对 ⟺ LCS 长度。",
            "直接复用 LCS DP 代码。",
            "值相等才可连线，顺序保持。",
            "时间 O(m·n)，空间 O(m·n)。",
            "贪心错误，必须 DP。",
            "与 1143 同转移方程。",
        ],
        complexity="时间 O(m·n)，空间 O(m·n)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::is_subsequence': _m(
        "392",
        "判断子序列",
        "给定字符串 s 和 t，判断 s 是否为 t 的子序列（不要求连续）。\n\n约束：0 ≤ len(s) ≤ 100，0 ≤ len(t) ≤ 10^4。",
        [
            "示例 1：s = \"abc\", t = \"ahbgdc\" → True",
            "示例 2：s = \"axc\", t = \"ahbgdc\" → False",
        ],
        [
            "初始化 i=0 指向 s 中待匹配的字符下标；s 为空串时可直接返回 True。",
            "顺序扫描 t 的每个字符 ch，尝试与 s[i] 匹配。",
            "若 i < len(s) 且 s[i] == ch，说明 s 的下一个字符匹配成功，令 i += 1。",
            "i 只增不减，t 扫描一遍即可；未匹配的 t 字符直接跳过。",
            "扫描结束后 return i == len(s)，当且仅当 s 全部字符按序出现在 t 中。",
        ],
        "动态规划",
        code_notes=[
            "O(n) 双指针，无需显式 DP 表。",
            "i 只增不减，t 扫描一遍。",
            "s 空串恒 True。",
            "也可 DP dp[i][j] 判前缀，但双指针更优。",
            "与 LCS 相关：s 为 t 子序列 ⟺ LCS(s,t)=len(s)。",
            "时间 O(len(t))，空间 O(1)。",
        ],
        complexity="时间 O(len(t))，空间 O(1)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::num_distinct': _m(
        "115",
        "不同的子序列",
        "给定 s 和 t，统计 s 的子序列中等于 t 的不同个数。\n\n约束：1 ≤ len(s), len(t) ≤ 1000，s 和 t 仅英文字母。",
        [
            "示例 1：s = \"rabbbit\", t = \"rabbit\" → 3",
            "示例 2：s = \"babgbag\", t = \"bag\" → 5",
        ],
        [
            "dp[i][j] 为 s[:i] 中 t[:j] 的子序列个数。",
            "dp[i][0]=1（空 t 一种删法）；j>0 初值 0。",
            "s[i-1]==t[j-1]：dp[i][j]=dp[i-1][j-1]+dp[i-1][j]（用/不用 s[i-1]）。",
            "不等：dp[i][j]=dp[i-1][j]。",
        ],
        "动态规划",
        code_notes=[
            "匹配时 +dp[i-1][j-1] 用当前字符，+dp[i-1][j] 跳过 s[i-1]。",
            "dp[i][0]=1 全删 s 得空串。",
            "答案可能很大，Python 整数无限。",
            "与编辑距离同表形状不同转移。",
            "时间 O(m·n)，空间 O(m·n) 可滚动。",
            "经典子序列计数 DP。",
        ],
        complexity="时间 O(m·n)，空间 O(m·n)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::min_delete_distance': _m(
        "583",
        "两个字符串的删除操作",
        "给定 word1、word2，使两串相等所需最少删除步数（每步删一字符）。\n\n约束：1 ≤ len(word1), len(word2) ≤ 500，仅小写字母。",
        [
            "示例 1：word1 = \"sea\", word2 = \"eat\" → 2（删 \"s\" 和 \"t\"）",
            "示例 2：word1 = \"leetcode\", word2 = \"etco\" → 4",
        ],
        [
            "只允许删除、不允许插入，使两串相等的最少步数等价于「各删去非公共部分」。",
            "调用 longest_common_subsequence(word1, word2) 求最长公共子序列长度 lcs。",
            "word1 需删除 len(word1)-lcs 个字符，word2 需删除 len(word2)-lcs 个字符。",
            "总删除次数 = (len(word1)-lcs) + (len(word2)-lcs) = len(word1)+len(word2)-2*lcs。",
            "return len(word1) + len(word2) - 2*lcs。",
        ],
        "动态规划",
        code_notes=[
            "保留 LCS 长度，其余字符各删一次。",
            "删除数 = (len1-lcs) + (len2-lcs) = len1+len2-2*lcs。",
            "直接复用 LCS 函数。",
            "只允许删除不允许插入，与编辑距离不同。",
            "时间 O(m·n)  dominated by LCS。",
            "空间 O(m·n) 或 LCS 滚动优化。",
        ],
        complexity="时间 O(m·n)，空间 O(m·n)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::min_edit_distance': _m(
        "72",
        "编辑距离",
        "给定 word1、word2，将 word1 转换成 word2 的最少操作数；操作：插入、删除、替换一个字符。\n\n约束：0 ≤ len(word1), len(word2) ≤ 500，小写英文字母。",
        [
            "示例 1：word1 = \"horse\", word2 = \"ros\" → 3",
            "示例 2：word1 = \"intention\", word2 = \"execution\" → 5",
        ],
        [
            "dp[i][0]=i，dp[0][j]=j（删/插到空串）。",
            "i,j 双重循环：字符相等 dp[i][j]=dp[i-1][j-1]。",
            "不等 dp[i][j]=min(替换,删,插)+1 = min(dp[i-1][j-1], dp[i-1][j], dp[i][j-1])+1。",
            "return dp[-1][-1]。",
        ],
        "动态规划",
        code_notes=[
            "三操作对应斜角、上、左+1。",
            "首行首列初始化单串全删/全插代价。",
            "经典 Wagner-Fischer 算法。",
            "可滚动一行 O(n) 空间。",
            "与 LCS、583 同属双串 DP 家族。",
            "时间 O(m·n)，空间 O(m·n)。",
        ],
        complexity="时间 O(m·n)，空间 O(m·n)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::longest_palindrome_subseq': _m(
        "516",
        "最长回文子序列",
        "给定字符串 s，找出其中最长的回文子序列长度。子序列不要求连续。\n\n约束：1 ≤ len(s) ≤ 1000，s 仅小写英文字母。",
        [
            "示例 1：s = \"bbbab\" → 4（\"bbbb\"）",
            "示例 2：s = \"cbbd\" → 2（\"bb\"）",
        ],
        [
            "区间 DP：dp[i][i]=1；i 从 n-1 到 0，j 从 i+1 到 n-1。",
            "s[i]==s[j]：dp[i][j]=dp[i+1][j-1]+2。",
            "else dp[i][j]=max(dp[i+1][j], dp[i][j-1])。",
            "return dp[0][n-1]。",
        ],
        "动态规划",
        code_notes=[
            "i 递减保证 dp[i+1][j-1] 已计算。",
            "两端匹配则中间回文 +2。",
            "与最长回文子串（连续）不同。",
            "O(n^2) 区间 DP。",
            "也可 n 行滚动。",
            "时间 O(n^2)，空间 O(n^2)。",
        ],
        complexity="时间 O(n^2)，空间 O(n^2)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::longest_palindrome': _m(
        "5",
        "最长回文子串",
        "给定 s，返回 s 中最长回文子串（连续）。\n\n约束：1 ≤ len(s) ≤ 1000，s 仅数字和英文字母。",
        [
            "示例 1：s = \"babad\" → \"bab\" 或 \"aba\"",
            "示例 2：s = \"cbbd\" → \"bb\"",
        ],
        [
            "dp[i][j] 表示 s[i..j] 是否回文；i 从 n-1 到 0，j 从 i 到 n-1。",
            "s[i]==s[j] 且 (j-i<=1 或 dp[i+1][j-1]) 则 dp[i][j]=True。",
            "更新 best_start, best_len 记录最长回文。",
            "return s[best_start:best_start+best_len]。",
        ],
        "动态规划",
        code_notes=[
            "j-i<=1 处理单字符和双字符回文。",
            "中心扩展 O(n^2) 常数更小，本实现 DP。",
            "Manacher O(n) 更优但实现复杂。",
            "best 在 dp[i][j] True 时更新。",
            "时间 O(n^2)，空间 O(n^2)。",
            "与 647 计数共用 dp 表。",
        ],
        complexity="时间 O(n^2)，空间 O(n^2)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::count_substrings': _m(
        "647",
        "回文子串",
        "给定字符串 s，统计 s 中回文子串数目。具有不同开始或结束位置的子串即使内容相同也统计。\n\n约束：1 ≤ len(s) ≤ 1000，s 小写英文字母。",
        [
            "示例 1：s = \"abc\" → 3（\"a\",\"b\",\"c\"）",
            "示例 2：s = \"aaa\" → 6",
        ],
        [
            "初始化 count=0，dp[i][j] 表示子串 s[i:j+1] 是否为回文；与 longest_palindrome 相同构造。",
            "i 从 n-1 递减到 0，j 从 i 递增到 n-1，保证内层较短子串先计算。",
            "若 s[i]==s[j] 且 (j-i<=1 或 dp[i+1][j-1] 已为 True)，则 dp[i][j]=True。",
            "每当 dp[i][j] 为 True，count += 1，统计一个回文子串（含单字符与更长子串）。",
            "全部 (i,j) 对处理完毕后 return count。",
        ],
        "动态规划",
        code_notes=[
            "每个 True 的 dp[i][j] 对应一个回文子串。",
            "与第 5 题 dp 构造相同，累加计数。",
            "中心扩展可 O(n^2) 计数。",
            "单字符 j==i 时 count 增 1。",
            "时间 O(n^2)，空间 O(n^2)。",
            "aaa 得 6：三个 a、两个 aa、一个 aaa。",
        ],
        complexity="时间 O(n^2)，空间 O(n^2)。",
    ),
    'paradigms/dynamic_programming/sequence_dp.py::num_decodings': _m(
        "91",
        "解码方法",
        "一条包含 A-Z 消息用非零 digit 编码：'A'→1 … 'Z'→26。给定只含数字的 s，计算解码方法总数。\n\n约束：1 ≤ len(s) ≤ 100，s 只含数字，可能含前导零。",
        [
            "示例 1：s = \"12\" → 2（\"AB\" 或 \"L\"）",
            "示例 2：s = \"226\" → 3",
            "示例 3：s = \"06\" → 0",
        ],
        [
            "若 s 空或 s[0]=='0' return 0。",
            "dp[0]=dp[1]=1；i 从 2 到 len(s)。",
            "若 s[i-1]!='0'：dp[i]+=dp[i-1]（单字符解码）。",
            "two_digit=int(s[i-2:i])，若 10<=two_digit<=26：dp[i]+=dp[i-2]。",
            "return dp[-1]。",
        ],
        "动态规划",
        code_notes=[
            "dp[i] 为 s[:i] 解码方案数。",
            "前导零导致 dp[1]=0 或首字符 0 return 0。",
            "两位 01-09 非法（除单独 0），10-26 合法。",
            "线性 DP O(n)。",
            "可压缩 dp 为两变量。",
            "时间 O(n)，空间 O(n)。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    'paradigms/dynamic_programming/stock.py::max_profit_once': _m(
        "121",
        "买卖股票的最佳时机",
        "给定数组 prices，prices[i] 为第 i 天股价。最多完成一笔交易（买一次卖一次），求最大利润。\n\n约束：1 ≤ len(prices) ≤ 10^5，0 ≤ prices[i] ≤ 10^4。",
        [
            "示例 1：prices = [7,1,5,3,6,4] → 5（1 买 6 卖）",
            "示例 2：prices = [7,6,4,3,1] → 0",
        ],
        [
            "min_price = prices[0]，best = 0。",
            "遍历 price in prices[1:]：min_price = min(min_price, price)。",
            "best = max(best, price - min_price)。",
            "return best。",
        ],
        "动态规划",
        code_notes=[
            "等价 min 前缀 + max 差值。",
            "必须先买后卖，min_price 为历史最低买价。",
            "O(n) 一遍，O(1) 空间。",
            "也可 dp[i] 第 i 天最大利润 dp[i]=max(dp[i-1], price-min_so_far)。",
            "股票系列基础题。",
            "全跌时 best=0。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/dynamic_programming/stock.py::max_profit_unlimited': _m(
        "122",
        "买卖股票的最佳时机 II",
        "prices 数组，可多次买卖（同一时刻最多持一股），求最大利润。\n\n约束：1 ≤ len(prices) ≤ 3×10^4，0 ≤ prices[i] ≤ 10^4。",
        [
            "示例 1：prices = [7,1,5,3,6,4] → 7（1→5 + 3→6）",
            "示例 2：prices = [1,2,3,4,5] → 4",
        ],
        [
            "定义 hold 为持有一股时的最大净收益状态，cash 为不持股时的最大现金；初始 hold=-prices[0], cash=0。",
            "从第二个价格开始遍历 prices[1:] 的每个 price。",
            "更新 hold = max(hold, cash - price)：要么继续持有，要么从 cash 状态今日买入。",
            "更新 cash = max(cash, hold + price)：要么继续空仓，要么从 hold 状态今日卖出。",
            "遍历结束 return cash，最终不持股时的最大利润即为答案。",
        ],
        "动态规划",
        code_notes=[
            "hold 持有一股最大「负成本」，cash 不持股最大现金。",
            "贪心累加上升段等价于本 DP。",
            "无限次交易无冷却无手续费。",
            "两状态转移股票模板。",
            "时间 O(n)，空间 O(1)。",
            "最终 return cash 而非 hold。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/dynamic_programming/stock.py::max_profit_twice': _m(
        "123",
        "买卖股票的最佳时机 III",
        "最多完成两笔交易（买入-卖出算一笔），求最大利润。\n\n约束：1 ≤ len(prices) ≤ 10^5，0 ≤ prices[i] ≤ 10^5。",
        [
            "示例 1：prices = [3,3,5,0,0,3,1,4] → 6",
            "示例 2：prices = [1,2,3,4,5] → 4",
        ],
        [
            "prices 为空时 return 0；否则初始化 dp=[0,-prices[0],0,-prices[0],0] 五状态。",
            "dp[0] 无操作；dp[1] 第一次买入后；dp[2] 第一次卖出后；dp[3] 第二次买入后；dp[4] 第二次卖出后。",
            "遍历 prices[1:] 每个 price，按顺序更新五状态（每态取「保持」与「转移」较大值）。",
            "dp[1]=max(dp[1],dp[0]-price)；dp[2]=max(dp[2],dp[1]+price)；dp[3]=max(dp[3],dp[2]-price)；dp[4]=max(dp[4],dp[3]+price)。",
            "return dp[4]，即最多两笔交易完成后的最大利润。",
        ],
        "动态规划",
        code_notes=[
            "dp[0]=0 无操作；奇数态买入(-price)，偶数态卖出(+price)。",
            "五元组压缩两笔交易状态机。",
            "可推广到 k 笔见 max_profit_k_transactions。",
            "prices 空 return 0。",
            "时间 O(n)，空间 O(1) 五变量。",
            "比分割数组为四段更简洁。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/dynamic_programming/stock.py::max_profit_k_transactions': _m(
        "188",
        "买卖股票的最佳时机 IV",
        "最多 k 笔交易，求最大利润。\n\n约束：0 ≤ k ≤ 100，0 ≤ len(prices) ≤ 1000，0 ≤ prices[i] ≤ 1000。",
        [
            "示例 1：k = 2, prices = [2,4,1] → 2",
            "示例 2：k = 2, prices = [3,2,6,5,0,3] → 7",
        ],
        [
            "若 prices 空或 k==0 return 0。",
            "dp[i][j]：第 i 天，状态 j（0..2k-1，偶数卖奇数买）最大利润。",
            "dp[0][奇数]=-prices[0]；i 循环更新 dp[i][j+1]=max(持有, 卖买)，dp[i][j+2]=max(卖, 买后卖)。",
            "return dp[-1][2*k]。",
        ],
        "动态规划",
        code_notes=[
            "2k+1 状态：k 次买卖交替。",
            "k 很大时可退化为 unlimited 贪心 O(n)。",
            "j 偶数为不持股或刚卖，奇数为持股。",
            "二维 dp 可压一维。",
            "时间 O(n·k)，空间 O(n·k) 或 O(k)。",
            "股票系列通用框架。",
        ],
        complexity="时间 O(n·k)，空间 O(k) 可优化。",
    ),
    'paradigms/dynamic_programming/stock.py::max_profit_with_cooldown': _m(
        "309",
        "最佳买卖股票时机含冷冻期",
        "可多次买卖，但卖出后第二天为冷冻期不能买入，求最大利润。\n\n约束：1 ≤ len(prices) ≤ 5000，0 ≤ prices[i] ≤ 1000。",
        [
            "示例 1：prices = [1,2,3,0,2] → 3",
            "示例 2：prices = [1] → 0",
        ],
        [
            "hold, sold, rest 三状态：持股市值、刚卖、冷冻/休息最大现金。",
            "首日 hold=-prices[0], sold=0, rest=0。",
            "每日：hold=max(hold, rest-price)；sold=hold+price；rest=max(rest,sold)。",
            "return max(sold, rest)。",
        ],
        "动态规划",
        code_notes=[
            "rest 可来自昨日 rest 或 sold（冷冻结束）。",
            "买入只能从 rest 非 hold/sold。",
            "sold 必须来自昨日 hold+price。",
            "三状态股票 DP 经典。",
            "时间 O(n)，空间 O(1)。",
            "与 714 手续费对比学习。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    'paradigms/dynamic_programming/stock.py::max_profit_with_fee': _m(
        "714",
        "买卖股票的最佳时机含手续费",
        "prices 数组，每笔卖出付 fee 手续费，可多次买卖，求最大利润。\n\n约束：1 ≤ len(prices) ≤ 5×10^4，0 ≤ prices[i] ≤ 10^4，0 ≤ fee ≤ 10^4。",
        [
            "示例 1：prices = [1,3,2,8,4,9], fee = 2 → 8",
            "示例 2：prices = [1,3,7,5,10,3], fee = 3 → 6",
        ],
        [
            "hold=-prices[0], cash=0。",
            "遍历 price：hold=max(hold, cash-price)；cash=max(cash, hold+price-fee)。",
            "卖出时扣 fee。",
            "return cash。",
        ],
        "动态规划",
        code_notes=[
            "与 122 区别：cash 更新时 hold+price-fee。",
            "fee 可在买或卖扣，等价调整。",
            "两状态 O(n) O(1)。",
            "hold 表示持股的净成本状态。",
            "无限次交易。",
            "时间 O(n)，空间 O(1)。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
}
