"""Catalog metadata: stack_queue, strings, foundations."""

from meta.helpers import _m

PROBLEMS: dict[str, dict] = {
    "data_structures/stack_queue/stack_queue.py::is_valid_parentheses": _m(
        "20",
        "有效的括号",
        "给定一个只包括 '('、')'、'{'、'}'、'['、']' 的字符串 s，判断字符串是否有效。\n\n有效字符串需满足：左括号必须用相同类型的右括号闭合；左括号必须以正确的顺序闭合；每个右括号都有一个对应的相同类型的左括号。\n\n约束：1 ≤ s.length ≤ 10⁴；s 仅由括号 '()[]{}' 组成。",
        [
            "示例 1：s = \"()\" → True",
            "示例 2：s = \"()[]{}\" → True",
            "示例 3：s = \"(]\" → False",
        ],
        [
            "遇到左括号（不在 pairs 映射键中的字符）直接入栈，等待后续右括号匹配。",
            "遇到右括号时，若栈空或栈顶与当前右括号不匹配（pairs[ch]），立即返回 False。",
            "匹配成功则 pop 栈顶，继续扫描下一个字符。",
            "全部扫描完毕后，栈必须为空才表示所有左括号均已闭合，返回 True。",
        ],
        "栈",
        code_notes=[
            "pairs = {')': '(', ']': '[', '}': '{'} — 右括号到左括号的映射，便于 O(1) 查匹配。",
            "stack: list[str] — 尚未闭合的左括号栈，后进先出符合嵌套结构。",
            "if ch not in pairs — 左括号分支，直接 append 入栈。",
            "elif not stack or stack.pop() != pairs[ch] — 右括号时栈空或类型不匹配均无效。",
            "return not stack — 结束时栈空才有效；残留左括号说明未闭合。",
        ],
        complexity="时间 O(n)，空间 O(n)，n 为字符串长度。",
    ),
    "data_structures/stack_queue/stack_queue.py::remove_adjacent_duplicates": _m(
        "1047",
        "删除字符串中的所有相邻重复项",
        "给出由小写字母组成的字符串 s，重复删除相邻且相同的字母，直到无法继续删除，返回最终得到的字符串。\n\n约束：1 ≤ s.length ≤ 10⁵；s 由小写英文字母组成。",
        [
            "示例 1：s = \"abbaca\" → \"ca\"。先删 \"bb\" 得 \"aaca\"，再删 \"aa\" 得 \"ca\"。",
            "示例 2：s = \"azxxzy\" → \"ay\"",
        ],
        [
            "用栈模拟反复删除相邻重复项的过程，避免多次扫描字符串。",
            "遍历每个字符 ch：若栈非空且栈顶等于 ch，说明形成相邻重复，pop 删除一对。",
            "否则将 ch 压入栈，表示当前保留的字符序列。",
            "遍历结束后，栈中自左向右即为答案，用 join 拼接返回。",
        ],
        "栈",
        code_notes=[
            "stack: list[str] — 当前删除相邻重复后的字符序列，栈顶即末尾字符。",
            "if stack and stack[-1] == ch — 检测到相邻相同字符，触发删除（pop）。",
            "else: stack.append(ch) — 无法删除时保留该字符。",
            "return \"\".join(stack) — 栈内顺序即最终字符串顺序。",
            "每个字符最多入栈、出栈各一次，等价于一次线性扫描完成全部删除。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "data_structures/stack_queue/stack_queue.py::eval_rpn": _m(
        "150",
        "逆波兰表达式求值",
        "根据逆波兰表达式（后缀表达式）求值。有效算符包括 +、-、*、/。\n\n约束：1 ≤ tokens.length ≤ 10⁴；tokens[i] 为整数或 +、-、*、/ 之一；除法向零截断。每个运算对象可以是整数或另一个表达式。",
        [
            "示例 1：tokens = [\"2\",\"1\",\"+\",\"3\",\"*\"] → 9。((2+1)*3)=9。",
            "示例 2：tokens = [\"4\",\"13\",\"5\",\"/\",\"+\"] → 6。(4+(13/5))=6。",
        ],
        [
            "逆波兰表达式从左到右扫描，遇数字入栈，遇运算符弹出两个操作数计算后再入栈。",
            "维护整数栈 stack，逐个处理 token。",
            "若 token 是运算符，先 pop 第二个操作数 b，再 pop 第一个操作数 a（顺序不可颠倒）。",
            "用 ops 字典映射运算符到函数，注意除法用 int(a/b) 实现向零截断。",
            "扫描结束后栈中仅剩一个元素，即为表达式值。",
        ],
        "栈",
        code_notes=[
            "ops = {\"+\": add, \"-\": sub, \"*\": mul, \"/\": lambda x, y: int(x / y)} — 运算符表。",
            "stack: list[int] — 操作数栈，后缀表达式求值的标准结构。",
            "b, a = stack.pop(), stack.pop() — 先 pop 的是右操作数 b，后 pop 的是左操作数 a。",
            "ops[token](a, b) — 按 a op b 顺序计算，保证减法、除法方向正确。",
            "int(x / y) — Python 3 中 / 为浮点除法，int() 截断实现 LeetCode 向零取整。",
            "return stack.pop() — 合法输入下栈中最终只剩结果。",
        ],
        complexity="时间 O(n)，空间 O(n)，n 为 token 个数。",
    ),
    "data_structures/stack_queue/stack_queue.py::decode_string": _m(
        "394",
        "字符串解码",
        "给定一个经过编码的字符串，返回解码后的字符串。\n\n编码规则为 k[encoded_string]，表示方括号内部的 encoded_string 重复 k 次。k 为正整数，1 ≤ k ≤ 300；encoded_string 仅含小写字母。\n\n约束：1 ≤ s.length ≤ 30；s 由小写字母、数字和方括号组成。",
        [
            "示例 1：s = \"3[a]2[bc]\" → \"aaabcbc\"",
            "示例 2：s = \"3[a2[c]]\" → \"accaccacc\"",
        ],
        [
            "从左到右扫描，普通字符直接入栈；遇到 ']' 触发一次解码。",
            "遇到 ']' 时，从栈顶弹出字符直到 '['，逆序拼接得到 repeat_str。",
            "弹出 '[' 后，继续从栈顶弹出数字字符，逆序拼接得到 repeat_count。",
            "将 repeat_str * int(repeat_count) 压回栈，作为已解码片段。",
            "全部扫描完成后，栈中元素自左向右拼接即为最终字符串。",
        ],
        "栈",
        code_notes=[
            "stack: list[str | int] — 混合存储普通字符、数字字符与已解码子串。",
            "if ch == ']' — 仅在右括号处触发解码，左括号与数字随扫描入栈。",
            "while stack and stack[-1] != '[' — 弹出 repeat_str 的字符，注意逆序拼接。",
            "isinstance(stack[-1], str) and stack[-1].isdigit() — 从栈顶读取重复次数数字。",
            "stack.append(repeat_str * int(repeat_count)) — 解码结果作为整体压栈。",
            "return \"\".join(str(x) for x in stack) — 栈中剩余元素即为最终串。",
        ],
        complexity="时间 O(n × max_k)，空间 O(n + m)，n 为编码串长度，m 为解码结果长度。",
    ),
    "data_structures/stack_queue/stack_queue.py::MonotonicQueue.__init__": _m(
        "239",
        "单调队列初始化",
        "滑动窗口最大值问题中，MonotonicQueue 负责维护窗口内候选最大值的单调递减序列。初始化时需创建空的双端队列，后续 push/pop/front 均在此结构上操作。\n\n单调队列的核心不变式：队首元素始终是当前窗口内的最大值，队尾到队首元素严格单调递减。\n\n约束：窗口大小 1 ≤ k ≤ nums.length；nums.length 在 [1, 10⁵] 范围内。",
        [
            "示例：MonotonicQueue() 后 queue 为空 deque，可立即 push 元素。",
            "示例：push(3), push(1) → 内部 queue 为 deque([3, 1])。",
        ],
        [
            "创建 MonotonicQueue 实例，无需传入参数。",
            "self.queue 初始化为空 deque[int]，支持 O(1) 两端操作。",
            "后续通过 push 入队、pop 移除过期元素、front 查询队首最大值。",
            "空队列状态下不可调用 front，需由 max_sliding_window 保证窗口已形成。",
        ],
        "单调队列",
        code_notes=[
            "self.queue: deque[int] — 双端队列，存储当前窗口内可能成为最大值的候选值。",
            "deque() — collections.deque 支持 O(1) 的 append/pop/popleft。",
            "__init__ 仅初始化空队列，不预分配容量。",
            "与 push/pop/front 配合构成完整单调队列 ADT。",
            "本实现存值而非下标，pop 时由外部传入滑出值判断是否过期。",
        ],
        complexity="时间 O(1)，空间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::MonotonicQueue.push": _m(
        "239",
        "单调队列入队",
        "滑动窗口最大值问题中，MonotonicQueue 在队尾入队 value 时，需维护队列内元素单调递减，以保证队首始终是当前窗口最大值。\n\n约束：与滑动窗口最大值（LC 239）配合使用；窗口大小 1 ≤ k ≤ nums.length。",
        [
            "示例：当前队列 [5, 3]，入队 value=4 → 弹出 3 后队列为 [5, 4]。",
            "示例：当前队列 [5, 3]，入队 value=2 → 直接 append，队列为 [5, 3, 2]。",
        ],
        [
            "单调递减队列：队首最大，队尾最小；新元素入队可能使队尾若干较小元素永不可能成为窗口最大值。",
            "入队前，从队尾向前比较：若队尾元素小于 value，则 pop 丢弃。",
            "重复上述过程直到队尾为空或队尾 ≥ value。",
            "将 value append 到队尾，完成入队。",
        ],
        "单调队列",
        code_notes=[
            "self.queue: deque[int] — 双端队列，存储当前窗口内「可能成为最大值」的候选值。",
            "while self.queue and value > self.queue[-1] — 队尾更小元素不可能再成为最大值。",
            "self.queue.pop() — 从队尾移除被支配的元素。",
            "self.queue.append(value) — 新元素入队，保持单调递减。",
            "本实现存值而非下标，pop 时需配合外部传入的滑出值判断是否过期。",
        ],
        complexity="均摊时间 O(1) 每次 push，空间 O(k)，k 为窗口大小。",
    ),
    "data_structures/stack_queue/stack_queue.py::MonotonicQueue.pop": _m(
        "239",
        "单调队列出队",
        "滑动窗口右移时，窗口左端元素 value 滑出窗口。\n\n约束：传入的 value 为窗口左端刚滑出的元素；与 push/front 配合使用。若该值恰为单调队列队首（当前窗口最大值），则需将其从队首移除。",
        [
            "示例：队列 [5, 3, 2]，滑出 value=5 → 队首等于 5，popleft 后队列为 [3, 2]。",
            "示例：队列 [5, 3, 2]，滑出 value=1 → 队首不等于 1，队列不变。",
        ],
        [
            "窗口左边界右移时，调用 pop 传入刚滑出的元素 value。",
            "仅当队首元素等于 value 时，说明该最大值已离开窗口，执行 popleft。",
            "若队首不等于 value，说明 value 在入队时已被更大元素「淘汰」，无需操作。",
            "此方法与 push 配合，保证队首始终是当前窗口内的最大值。",
        ],
        "单调队列",
        code_notes=[
            "if self.queue and self.queue[0] == value — 队首等于滑出值才需要移除。",
            "self.queue.popleft() — 从队首删除过期最大值。",
            "若 value 不在队列中（已被 pop 掉），则不执行任何操作。",
            "与 max_sliding_window 中 queue.pop(nums[i-k+1]) 配合使用。",
            "lazy 删除策略：只在队首匹配时才 popleft，均摊 O(1)。",
        ],
        complexity="均摊时间 O(1) 每次 pop。",
    ),
    "data_structures/stack_queue/stack_queue.py::MonotonicQueue.front": _m(
        "239",
        "单调队列队首",
        "返回单调递减队列的队首元素，即当前滑动窗口内的最大值。\n\n约束：调用前队列非空；窗口已形成后方可读取最大值。",
        [
            "示例：队列 [6, 5, 3]，front() → 6。",
            "示例：窗口 [3, -1, -3] 对应队列 [3, -1, -3]，front() → 3。",
        ],
        [
            "单调递减队列的不变式：队首元素 ≥ 队列中所有其他元素。",
            "经过 push 维护单调性、pop 移除过期队首后，queue[0] 即为窗口最大值。",
            "调用 front 前需保证队列非空，通常由 max_sliding_window 在窗口形成后调用。",
            "直接返回 self.queue[0]，O(1) 查询，无需遍历整个窗口。",
        ],
        "单调队列",
        code_notes=[
            "return self.queue[0] — 队首即当前窗口最大值。",
            "调用时机：窗口长度达到 k 后，每轮扩展窗口时读取 front 写入结果。",
            "deque 支持 O(1) 访问两端，front 与 popleft 均操作队首。",
            "需与 push/pop 配合使用，单独调用无法保证正确性。",
            "队列为 deque[int]，存值而非下标，过期判断依赖 pop 传入的滑出值。",
        ],
        complexity="时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::max_sliding_window": _m(
        "239",
        "滑动窗口最大值",
        "给定整数数组 nums 和整数 k，有一个大小为 k 的滑动窗口从数组最左侧移动到最右侧，返回滑动窗口中的最大值组成的数组。\n\n约束：1 ≤ nums.length ≤ 10⁵；-10⁴ ≤ nums[i] ≤ 10⁴；1 ≤ k ≤ nums.length。",
        [
            "示例 1：nums = [1,3,-1,-3,5,3,6,7], k = 3 → [3,3,5,5,6,7]",
            "示例 2：nums = [1], k = 1 → [1]",
        ],
        [
            "使用 MonotonicQueue 维护窗口内单调递减的候选最大值。",
            "遍历 nums，对每个 value 调用 queue.push(value) 入队。",
            "当索引 i ≥ k-1 时，窗口 [i-k+1, i] 已形成，将 queue.front() 加入结果。",
            "随后调用 queue.pop(nums[i-k+1]) 移除窗口左端滑出的元素。",
            "遍历结束，result 即为每个窗口的最大值序列。",
        ],
        "单调队列",
        code_notes=[
            "queue = MonotonicQueue() — 封装单调递减双端队列。",
            "for i, value in enumerate(nums) — i 为窗口右边界下标。",
            "queue.push(value) — 每个新元素入队并维护单调性。",
            "if i >= k - 1 — 窗口长度达到 k 时开始收集答案。",
            "result.append(queue.front()) — 队首即当前窗口最大值。",
            "queue.pop(nums[i - k + 1]) — 移除刚滑出窗口左端的元素。",
        ],
        complexity="时间 O(n)，空间 O(k)。",
    ),
    "data_structures/stack_queue/stack_queue.py::top_k_frequent": _m(
        "347",
        "前 K 个高频元素",
        "给定整数数组 nums 和整数 k，返回出现频率前 k 高的元素。\n\n约束：1 ≤ nums.length ≤ 10⁵；k 的取值范围为 [1, 不同元素个数]；-10⁴ ≤ nums[i] ≤ 10⁴。返回的答案顺序不限。",
        [
            "示例 1：nums = [1,1,1,2,2,3], k = 2 → [1,2]",
            "示例 2：nums = [1], k = 1 → [1]",
        ],
        [
            "先用哈希表 counts 统计每个元素的出现频率。",
            "维护大小为 k 的最小堆 heap，堆元素为 (freq, num) 元组。",
            "遍历 counts：将 (freq, num) 入堆，若堆大小超过 k 则 heappop 弹出频率最小的。",
            "遍历结束后，堆中保留频率最高的 k 个元素。",
            "按频率降序排序后提取 num 返回（题目允许任意顺序，排序仅为可读性）。",
        ],
        "堆",
        code_notes=[
            "counts: dict[int, int] — 元素到频次的映射。",
            "heap: list[tuple[int, int]] — 最小堆，堆顶为当前 k 个候选中频率最低的。",
            "heapq.heappush(heap, (freq, num)) — 按 freq 比较，freq 相同时按 num 比较。",
            "if len(heap) > k: heapq.heappop(heap) — 保持堆大小不超过 k。",
            "sorted(heap, reverse=True) — 按频率降序排列后取 num。",
            "[num for _, num in ...] — 提取元素值作为答案。",
        ],
        complexity="时间 O(n log k)，空间 O(n)。",
    ),
    "data_structures/stack_queue/stack_queue.py::find_kth_largest": _m(
        "215",
        "数组中的第 K 个最大元素",
        "给定整数数组 nums 和整数 k，返回数组中第 k 个最大的元素。\n\n约束：1 ≤ k ≤ nums.length ≤ 10⁵；-10⁴ ≤ nums[i] ≤ 10⁴。注意是排序后的第 k 大，不是第 k 个不同元素。",
        [
            "示例 1：nums = [3,2,1,5,6,4], k = 2 → 5",
            "示例 2：nums = [3,2,3,1,2,4,5,5,6], k = 4 → 4",
        ],
        [
            "第 k 大等价于升序排序后倒数第 k 个，可用大小为 k 的最小堆维护。",
            "遍历 nums，将每个 num 入堆。",
            "若堆大小超过 k，heappop 弹出堆顶（当前最小的），保证堆内是最大的 k 个元素。",
            "遍历结束后，堆顶 heap[0] 即为第 k 大元素。",
        ],
        "堆",
        code_notes=[
            "heap: list[int] — 最小堆，堆顶为当前保留的 k 个元素中最小的。",
            "heapq.heappush(heap, num) — 将元素加入候选集。",
            "if len(heap) > k: heapq.heappop(heap) — 超出 k 个则丢弃最小者。",
            "return heap[0] — 堆顶是 k 个最大元素中的最小值，即第 k 大。",
            "也可用快速选择 O(n) 平均，本实现为 O(n log k) 堆解法。",
        ],
        complexity="时间 O(n log k)，空间 O(k)。",
    ),
    "data_structures/stack_queue/stack_queue.py::asteroid_collision": _m(
        "735",
        "小行星碰撞",
        "给定整数数组 asteroids，表示在同一行上的小行星。正数向右飞，负数向左飞。每颗小行星以相同速度移动，碰撞时较小者爆炸；大小相等则同归于尽。返回碰撞后剩余的小行星。\n\n约束：2 ≤ asteroids.length ≤ 10⁴；-1000 ≤ asteroids[i] ≤ 1000；asteroids[i] ≠ 0。",
        [
            "示例 1：asteroids = [5,10,-5] → [5,10]",
            "示例 2：asteroids = [8,-8] → []",
            "示例 3：asteroids = [10,2,-5] → [10]",
        ],
        [
            "用栈模拟从左到右的碰撞过程，栈中存尚未爆炸的小行星。",
            "若当前 asteroid 向右（>0），或栈空，或栈顶向左（<0），无碰撞，直接入栈。",
            "若当前向左且栈顶向右，进入碰撞循环：比较绝对值大小。",
            "栈顶 + asteroid > 0：当前小行星爆炸，break 不入栈。",
            "栈顶 + asteroid < 0：栈顶爆炸 pop，继续与新的栈顶碰撞；相等则双方 pop 后 break。",
            "循环结束后若当前小行星仍存活则 append。",
        ],
        "栈",
        code_notes=[
            "stack: list[int] — 碰撞后仍存活的小行星，自左向右排列。",
            "if asteroid > 0 or not stack or stack[-1] < 0 — 无碰撞条件，直接 append。",
            "while stack and stack[-1] > 0 — 栈顶向右、当前向左，持续碰撞。",
            "stack[-1] + asteroid > 0 — 栈顶更大，当前小行星爆炸。",
            "stack[-1] + asteroid < 0 — 栈顶爆炸，pop 后继续循环。",
            "else: stack.append(asteroid) — for-else：未被 break 时当前小行星入栈。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "data_structures/stack_queue/stack_queue.py::QueueUsingStack.__init__": _m(
        "232",
        "用栈实现队列-初始化",
        "设计一个用两个栈实现队列的数据结构 QueueUsingStack。初始化时创建空的入队栈 in_stack 和出队栈 out_stack。\n\n双栈队列的经典设计：push 只写 in_stack，pop/peek 从 out_stack 读取；当 out_stack 为空时将 in_stack 全部倒栈到 out_stack，实现 FIFO 顺序。\n\n约束：push、pop、peek、empty 操作均需在均摊 O(1) 时间内完成；pop 和 peek 操作仅在队列非空时调用。",
        [
            "示例：q = QueueUsingStack() 后 empty() → True。",
            "示例：push(1), push(2) 后 in_stack = [1, 2]，out_stack 仍为空。",
        ],
        [
            "创建 QueueUsingStack 实例，无需参数。",
            "self.in_stack 初始化为空 list，负责接收所有 push 操作。",
            "self.out_stack 初始化为空 list，负责 pop/peek 的 FIFO 出队。",
            "两栈均为空时表示队列为空。",
        ],
        "栈",
        code_notes=[
            "self.in_stack: list[int] — 入队栈，push 时直接 append。",
            "self.out_stack: list[int] — 出队栈，元素倒序存放，pop 时 LIFO 变 FIFO。",
            "初始两栈皆空，empty() 返回 True。",
            "不在 __init__ 中做预分配，按需增长。",
            "倒栈逻辑延迟到 _move()，由 pop/peek 触发。",
        ],
        complexity="时间 O(1)，空间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::QueueUsingStack.push": _m(
        "232",
        "用栈实现队列-入队",
        "实现队列的 push 操作：将元素 x 放到队列的末尾。\n\n约束：LeetCode 232；pop/peek 仅在队列非空时调用；均摊 O(1)。本设计用两个栈 in_stack 和 out_stack 模拟队列。",
        [
            "示例：依次 push(1), push(2) 后，队列顺序为 [1, 2]（1 在队首）。",
            "示例：push(5) 后 in_stack 栈顶为 5，out_stack 仍为空。",
        ],
        [
            "入队操作只需将元素压入 in_stack，O(1) 完成。",
            "不在 push 时做倒栈，延迟到 pop/peek 时再转移，均摊更高效。",
            "in_stack 负责接收所有入队元素，out_stack 负责出队顺序。",
            "两栈分工：入栈只写 in_stack，读操作才触发 in→out 转移。",
        ],
        "栈",
        code_notes=[
            "self.in_stack: list[int] — 入队栈，所有 push 的元素先进入此栈。",
            "self.out_stack: list[int] — 出队栈，元素倒序存放，pop 时 LIFO 变 FIFO。",
            "self.in_stack.append(x) — push 仅操作 in_stack，O(1)。",
            "倒栈逻辑在 _move() 中，push 不触发。",
            "均摊 O(1)：每个元素最多转移一次到 out_stack。",
        ],
        complexity="时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::QueueUsingStack.pop": _m(
        "232",
        "用栈实现队列-出队",
        "实现队列的 pop 操作：从队列首部移除并返回元素。\n\n约束：pop 仅在队列非空时调用；返回队首元素。",
        [
            "示例：push(1), push(2), pop() → 1；再 pop() → 2。",
            "示例：push(3), pop() → 3。",
        ],
        [
            "出队前先调用 _move()，确保 out_stack 有元素可出。",
            "_move()：若 out_stack 为空，将 in_stack 全部 pop 并压入 out_stack，顺序反转。",
            "从 out_stack pop 栈顶，即队列的队首元素（FIFO）。",
            "每个元素最多入栈、出栈各两次，均摊 O(1)。",
        ],
        "栈",
        code_notes=[
            "self._move() — 懒转移：仅当 out_stack 空时才倒 in_stack。",
            "return self.out_stack.pop() — 出队栈顶即队首。",
            "while self.in_stack: self.out_stack.append(self.in_stack.pop()) — 倒栈反转顺序。",
            "in_stack 后进先出 + out_stack 后进先出 = 队列先进先出。",
            "LeetCode 232 经典双栈实现队列。",
        ],
        complexity="均摊时间 O(1)，最坏 O(n)。",
    ),
    "data_structures/stack_queue/stack_queue.py::QueueUsingStack.peek": _m(
        "232",
        "用栈实现队列-队首",
        "实现队列的 peek 操作：返回队列首部元素但不移除。\n\n约束：peek 仅在队列非空时调用；不修改队列内容。",
        [
            "示例：push(1), push(2), peek() → 1；pop() 后 peek() → 2。",
            "示例：仅 push(7) 时 peek() → 7。",
        ],
        [
            "与 pop 相同，先调用 _move() 保证 out_stack 非空（队列非空时）。",
            "返回 out_stack[-1]，即栈顶/队首元素，不执行 pop。",
            "peek 不改变队列内容，可多次调用返回相同值。",
            "若队列为空，_move 后 out_stack 仍空，访问会 IndexError（题目保证非空）。",
        ],
        "栈",
        code_notes=[
            "self._move() — 与 pop 共享倒栈逻辑。",
            "return self.out_stack[-1] — 读栈顶而不弹出。",
            "peek 与 pop 的区别仅在于是否 pop。",
            "均摊 O(1)，与 pop 共享倒栈代价。",
            "out_stack 栈顶对应队列队首（FIFO 顺序）。",
        ],
        complexity="均摊时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::QueueUsingStack.empty": _m(
        "232",
        "用栈实现队列-判空",
        "实现队列的 empty 操作：若队列为空返回 True，否则 False。\n\n约束：LeetCode 232 四个接口之一；O(1) 判断。",
        [
            "示例：初始 empty() → True；push(1) 后 empty() → False。",
            "示例：pop 至两栈皆空后 empty() → True。",
        ],
        [
            "队列为空当且仅当 in_stack 与 out_stack 均为空。",
            "两个栈都空说明没有任何待出队或待转移的元素。",
            "in_stack 有元素但 out_stack 空时，队列仍非空（元素待转移）。",
            "O(1) 判断，无需遍历或计数。",
        ],
        "栈",
        code_notes=[
            "return not self.in_stack and not self.out_stack — 双栈皆空才为空队列。",
            "out_stack 有元素或 in_stack 有元素均表示队列非空。",
            "empty 不触发 _move，仅检查两栈状态。",
            "push 后 in_stack 非空则 empty 为 False。",
            "pop 至两栈皆空后 empty 为 True。",
        ],
        complexity="时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::QueueUsingStack._move": _m(
        "232",
        "用栈实现队列-元素转移",
        "_move 是双栈队列的核心辅助方法：当 out_stack 为空时，将 in_stack 全部元素依次 pop 并 append 到 out_stack，反转顺序后 out_stack 栈顶即为最早入队元素。\n\n延迟转移策略使 push 均摊 O(1)，pop/peek 调用 _move 后才从 out_stack 取元素，实现先进先出语义。\n\n约束：LeetCode 232 内部辅助方法；仅在 out_stack 为空时执行；均摊 O(1)。",
        [
            "示例：in_stack=[1,2], out_stack=[] → _move 后 out_stack 栈顶为 1（最早入队）。",
            "示例：out_stack 非空时不执行任何操作，避免破坏已有 FIFO 顺序。",
        ],
        [
            "若 out_stack 非空，直接返回（已有可出队元素）。",
            "若 out_stack 为空且 in_stack 非空，进入 while 循环。",
            "每次从 in_stack pop 一个元素 append 到 out_stack。",
            "转移完成后 out_stack 栈顶为最早入队元素，供 pop/peek 使用。",
        ],
        "栈",
        code_notes=[
            "def _move(self) -> None — 私有方法，in→out 批量转移。",
            "if not self.out_stack — 仅 out_stack 为空时才转移。",
            "while self.in_stack — 逐个 pop in_stack 元素。",
            "self.out_stack.append(self.in_stack.pop()) — 压入 out_stack 反转顺序。",
            "pop/peek 前调用，均摊每个元素 O(1)。",
            "in_stack 与 out_stack 分工：入队 vs 出队。",
        ],
        complexity="均摊时间 O(1)，最坏单次 O(n)。",
    ),
    "data_structures/stack_queue/stack_queue.py::StackUsingQueue.__init__": _m(
        "225",
        "用队列实现栈-初始化",
        "设计一个用单个队列（deque）实现栈的数据结构 StackUsingQueue。初始化时创建空的双端队列。\n\n单队列实现栈的思路：push 直接 append 到队尾；pop 时将前 n-1 个元素轮转到底部，最后 popleft 队首即为栈顶。top 直接读队尾，O(1) 完成。\n\n约束：pop 和 top 操作仅在栈非空时调用；push 均摊 O(1)，pop 时间 O(n)。",
        [
            "示例：s = StackUsingQueue() 后 empty() → True。",
            "示例：push(1), push(2) 后 queue = deque([1, 2])，top() → 2。",
        ],
        [
            "创建 StackUsingQueue 实例，无需参数。",
            "self.queue 初始化为空 deque[int]。",
            "push 时 append 到队尾；pop 时轮转后 popleft 队首。",
            "空 deque 表示栈为空。",
        ],
        "队列",
        code_notes=[
            "self.queue: deque[int] — 单队列存储所有栈元素，队尾即栈顶。",
            "deque() — 支持 O(1) 的 append/popleft/索引访问。",
            "初始为空，empty() 返回 True。",
            "push 直接 append，不改变已有元素顺序。",
            "pop 依赖 len(self.queue) 决定轮转次数。",
        ],
        complexity="时间 O(1)，空间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::StackUsingQueue.push": _m(
        "225",
        "用队列实现栈-入栈",
        "实现栈的 push 操作：将元素 x 放到栈顶。\n\n约束：LeetCode 225；push 时间 O(1)。本设计用单个 deque 模拟栈。",
        [
            "示例：push(1), push(2) 后，top() → 2（2 在栈顶）。",
            "示例：push(3) 后 top() → 3。",
        ],
        [
            "直接将 x append 到 deque 末尾。",
            "配合 pop 时的轮转，使末尾元素始终为栈顶。",
            "push 本身 O(1)，pop 时 O(n) 调整顺序。",
            "单队列实现：新元素先入队尾，pop 前通过轮转将其移到队首。",
        ],
        "队列",
        code_notes=[
            "self.queue: deque[int] — 单队列存储所有元素。",
            "self.queue.append(x) — 新元素加到队尾，暂为队列末尾。",
            "pop 时会轮转使最新 push 的元素移到队首以便 popleft。",
            "LeetCode 225 用队列实现栈的标准写法。",
            "push 不修改已有元素顺序。",
        ],
        complexity="push 时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::StackUsingQueue.pop": _m(
        "225",
        "用队列实现栈-出栈",
        "实现栈的 pop 操作：移除并返回栈顶元素。\n\n约束：pop 仅在栈非空时调用；空栈返回 None。",
        [
            "示例：push(1), push(2), push(3), pop() → 3。",
            "示例：push(10), pop() → 10。",
        ],
        [
            "若队列为空，返回 None。",
            "将队列前 n-1 个元素依次 popleft 再 append 到队尾，完成轮转。",
            "最后 popleft 队首，即为最近 push 的元素（栈顶）。",
            "轮转 n-1 次使最后入队的元素移到队首。",
        ],
        "队列",
        code_notes=[
            "if not self.queue: return None — 空栈保护。",
            "for _ in range(len(self.queue) - 1) — 轮转前 n-1 个元素。",
            "self.queue.append(self.queue.popleft()) — 队首移到队尾。",
            "return self.queue.popleft() — 弹出栈顶（最后 push 的元素）。",
            "n 次 push + 1 次 pop 总代价 O(n)，均摊可接受。",
        ],
        complexity="时间 O(n)，n 为栈中元素个数。",
    ),
    "data_structures/stack_queue/stack_queue.py::StackUsingQueue.top": _m(
        "225",
        "用队列实现栈-栈顶",
        "实现栈的 top 操作：返回栈顶元素但不移除。\n\n约束：top 仅在栈非空时调用；空栈返回 None。",
        [
            "示例：push(1), push(2), top() → 2；pop() 后 top() → 1。",
            "示例：空栈 top() → None。",
        ],
        [
            "本实现中，每次 push 后最新元素在 deque 末尾。",
            "pop 前的轮转不改变「末尾即栈顶」的不变式（push 后直接读末尾）。",
            "队列为空时返回 None，否则返回 queue[-1]。",
            "top 为 O(1)，无需像 pop 那样轮转 n-1 次。",
        ],
        "队列",
        code_notes=[
            "return self.queue[-1] if self.queue else None — deque 末尾即栈顶。",
            "无需轮转即可 O(1) 读取栈顶。",
            "与 pop 配合：pop 依赖轮转，top 直接读末尾。",
            "空栈返回 None 而非抛异常。",
            "deque 支持 O(1) 访问两端。",
        ],
        complexity="时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::StackUsingQueue.empty": _m(
        "225",
        "用队列实现栈-判空",
        "实现栈的 empty 操作：若栈为空返回 True，否则 False。\n\n约束：LeetCode 225 四个接口之一；O(1) 判断。",
        [
            "示例：初始 empty() → True；push(1) 后 empty() → False。",
            "示例：pop 至两栈皆空后 empty() → True。",
        ],
        [
            "检查 deque 是否为空即可。",
            "not self.queue 等价于栈中无任何元素。",
            "empty 为 O(1)，不触发 pop 的轮转逻辑。",
            "push 后立即 empty() 返回 False。",
        ],
        "队列",
        code_notes=[
            "return not self.queue — deque 空则栈空。",
            "len(self.queue) == 0 等价判断。",
            "与 pop 返回 None 的边界一致。",
            "单 deque 实现，无辅助结构。",
            "LeetCode 225 要求实现的四个接口之一。",
        ],
        complexity="时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::MinStack.__init__": _m(
        "155",
        "最小栈-初始化",
        "设计一个支持 push、pop、top 操作，并在 O(1) 时间内检索最小元素的栈 MinStack。初始化时创建空的主栈 stack 和带哨兵的辅助最小值栈 min_stack。\n\n辅助栈 min_stack 与主栈同步 push/pop，栈顶始终记录对应时刻 stack 中所有元素的最小值。哨兵 float('inf') 保证首次 push 时 min(val, inf) == val 正确。\n\n约束：-2³¹ ≤ val ≤ 2³¹-1；pop、top、getMin 操作仅在栈非空时调用；最多调用 3×10⁴ 次 push/pop/top/getMin。",
        [
            "示例：s = MinStack() 后 stack = []，min_stack = [inf]。",
            "示例：push(-2) 后 stack = [-2]，min_stack = [inf, -2]。",
        ],
        [
            "创建 MinStack 实例，无需参数。",
            "self.stack 初始化为空 list[int]，存储所有入栈元素。",
            "self.min_stack 初始化为 [float('inf')]，哨兵保证首次 min 比较正确。",
            "后续 push 同步更新两栈，pop 同步弹出，getMin 读 min_stack 栈顶。",
        ],
        "栈",
        code_notes=[
            "self.stack: list[int] — 主栈，存所有元素，正常 LIFO 操作。",
            "self.min_stack: list[int] — 辅助栈，min_stack[i] 为 stack 前 i+1 个元素的最小值。",
            "self.min_stack = [float('inf')] — 哨兵值，使 min(val, inf) == val。",
            "两栈长度始终一致（除哨兵外 min_stack 比 stack 多 1 个哨兵）。",
            "空间换时间：额外 O(n) 空间实现 O(1) getMin。",
        ],
        complexity="时间 O(1)，空间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::MinStack.push": _m(
        "155",
        "最小栈-入栈",
        "设计一个支持 push、pop、top 操作，并在 O(1) 时间内检索最小元素的栈 MinStack。\n\n约束：-2³¹ ≤ val ≤ 2³¹-1；最多 3×10⁴ 次操作；getMin 均摊 O(1)。push 时将 val 压入主栈，并同步更新最小值辅助栈。",
        [
            "示例：push(-2), push(0), push(-3) 后 getMin() → -3。",
            "示例：push(5), getMin() → -3（最小值未变）。",
        ],
        [
            "维护两个栈：stack 存所有元素，min_stack 存对应时刻的历史最小值。",
            "每次 push(val) 时，stack 正常 append(val)。",
            "min_stack 压入 min(val, min_stack[-1])，记录 push 后当前最小值。",
            "min_stack 初始为 [inf]，保证首次 push 时 min 比较正确。",
        ],
        "栈",
        code_notes=[
            "self.stack: list[int] — 主栈，存所有元素。",
            "self.min_stack: list[int] — 辅助栈，min_stack[i] 为 stack 前 i+1 个元素的最小值。",
            "self.min_stack = [float('inf')] — 哨兵，使 min(val, inf) == val。",
            "self.min_stack.append(min(val, self.min_stack[-1])) — 同步压入当前最小值。",
            "两栈同步 push，保证 getMin 时 min_stack 栈顶有效。",
        ],
        complexity="时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::MinStack.pop": _m(
        "155",
        "最小栈-出栈",
        "弹出栈顶元素，同时同步弹出 min_stack 栈顶。\n\n约束：pop 仅在栈非空时调用；主栈与 min_stack 同步弹出。",
        [
            "示例：push(3), push(1), pop() 后 getMin() → 3。",
            "示例：push(2), push(1), pop(), pop() 后栈空。",
        ],
        [
            "pop 时主栈与 min_stack 必须同步弹出，保持两栈长度一致。",
            "弹出后 min_stack 新栈顶即为剩余元素的最小值。",
            "无需重新扫描 stack 求最小值。",
            "题目保证 pop 时栈非空。",
        ],
        "栈",
        code_notes=[
            "self.stack.pop() — 移除栈顶元素。",
            "self.min_stack.pop() — 同步移除对应的最小值记录。",
            "两栈始终等长，pop 后 getMin() 仍 O(1)。",
            "顺序：先 pop stack 再 pop min_stack（或同时，须成对）。",
            "LeetCode 155 MinStack 核心不变式。",
        ],
        complexity="时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::MinStack.top": _m(
        "155",
        "最小栈-栈顶",
        "返回栈顶元素，不弹出。\n\n约束：top 仅在栈非空时调用；返回栈顶元素。",
        [
            "示例：push(1), push(2), top() → 2。",
            "示例：push(-1), top() → -1。",
        ],
        [
            "直接返回 stack 栈顶元素 stack[-1]。",
            "题目保证 top 前栈非空。",
            "top 不修改 min_stack，仅读主栈。",
            "O(1) 查询栈顶。",
        ],
        "栈",
        code_notes=[
            "return self.stack[-1] — 主栈末尾即栈顶。",
            "与 getMin 独立，不访问 min_stack。",
            "pop 会改变 stack，top 仅读取。",
            "list 末尾 append/pop 均 O(1)。",
            "LeetCode 155 四个接口之一。",
        ],
        complexity="时间 O(1)。",
    ),
    "data_structures/stack_queue/stack_queue.py::MinStack.getMin": _m(
        "155",
        "最小栈-最小值",
        "在 O(1) 时间内返回栈中最小元素。\n\n约束：getMin 仅在栈非空时调用；O(1) 返回当前最小值。",
        [
            "示例：push(3), push(1), push(2), getMin() → 1。",
            "示例：push(0), getMin() → 0。",
        ],
        [
            "min_stack 栈顶始终记录当前 stack 中所有元素的最小值。",
            "每次 push 时同步更新，pop 时同步移除，无需遍历。",
            "直接返回 min_stack[-1]。",
            "O(1) 时间，额外 O(n) 空间存储历史最小值。",
        ],
        "栈",
        code_notes=[
            "return self.min_stack[-1] — 辅助栈顶即当前最小值。",
            "与 stack 同步 push/pop，保证 min_stack 与 stack 状态一致。",
            "空间换时间：额外 O(n) 空间实现 O(1) getMin。",
            "也可用差值编码或单栈存 (val, min) 元组。",
            "LeetCode 155 设计题核心接口。",
        ],
        complexity="时间 O(1)，额外空间 O(n)。",
    ),
    "strings/operations.py::reverse_string": _m(
        "344",
        "反转字符串",
        "编写一个函数，其作用是将输入的字符数组 s 原地反转。\n\n约束：1 ≤ s.length ≤ 10⁵；s[i] 为可打印 ASCII 字符；必须原地修改。",
        [
            "示例 1：s = [\"h\",\"e\",\"l\",\"l\",\"o\"] → [\"o\",\"l\",\"l\",\"e\",\"h\"]",
            "示例 2：s = [\"H\",\"a\",\"n\",\"n\",\"a\",\"h\"] → [\"h\",\"a\",\"n\",\"n\",\"a\",\"H\"]",
        ],
        [
            "原地反转用双指针 left、right 分别指向首尾。",
            "当 left < right 时，交换 s[left] 与 s[right]。",
            "left 右移、right 左移，向中间收敛。",
            "循环结束，整个数组完成反转。",
        ],
        "双指针",
        code_notes=[
            "left, right = 0, len(s) - 1 — 首尾双指针。",
            "while left < right — 未相遇时继续交换。",
            "s[left], s[right] = s[right], s[left] — Python 元组交换。",
            "left += 1; right -= 1 — 指针向中间移动。",
            "无返回值，原地修改 s。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    "strings/operations.py::reverse_str": _m(
        "541",
        "反转字符串 II",
        "给定字符串 s 和整数 k，从字符串开头起，每计数至 2k 个字符，就反转这 2k 字符中的前 k 个字符。若剩余字符少于 k 个，则反转剩余全部；若少于 2k 但 ≥ k，则反转前 k 个。\n\n约束：1 ≤ s.length ≤ 10⁴；s 由小写字母组成；1 ≤ k ≤ 10⁴。",
        [
            "示例 1：s = \"abcdefg\", k = 2 → \"bacdfeg\"",
            "示例 2：s = \"abcd\", k = 2 → \"bacd\"",
        ],
        [
            "将 s 转为字符列表 chars 便于切片赋值。",
            "以步长 2*k 遍历起始位置 start：0, 2k, 4k, …",
            "每段反转区间为 [start, min(start+k, len))，即前 k 个字符。",
            "chars[start:end] = reversed(chars[start:end]) 原地反转子段。",
            "最后 join 返回字符串。",
        ],
        "字符串",
        code_notes=[
            "chars = list(s) — 字符串转可变列表。",
            "for start in range(0, len(chars), 2 * k) — 每 2k 一段。",
            "end = min(start + k, len(chars)) — 反转长度最多 k。",
            "chars[start:end] = reversed(chars[start:end]) — 切片反转赋值。",
            "return \"\".join(chars) — 拼回字符串。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "strings/operations.py::reverse_words": _m(
        "151",
        "反转字符串中的单词",
        "给定一个字符串 s，逐个单词反转其中单词的顺序，并返回反转后的字符串。\n\n约束：1 ≤ s.length ≤ 10⁴；s 含英文大小写字母和空格；无多余空格。单词由非空格字符组成，单词间以单个空格分隔，不含前导或尾随空格。",
        [
            "示例 1：s = \"the sky is blue\" → \"blue is sky the\"",
            "示例 2：s = \"  hello world  \" → \"world hello\"（需 trim 多余空格）",
        ],
        [
            "s.split() 按空白分割得到单词列表，自动去除多余空格。",
            "reversed(words) 反转单词顺序。",
            "用单个空格 \" \".join 拼接成结果字符串。",
            "无需手动 trim 首尾空格，split 已处理。",
        ],
        "字符串",
        code_notes=[
            "return \" \".join(reversed(s.split())) — 一行解法。",
            "split() 无参时按任意空白分割并丢弃空串。",
            "reversed 返回迭代器，join 消费之。",
            "时间 O(n)，空间 O(n) 存储单词列表。",
            "LeetCode 151 经典字符串处理。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "strings/operations.py::length_of_last_word": _m(
        "58",
        "最后一个单词的长度",
        "给定一个字符串 s，返回 s 中最后一个单词的长度。\n\n约束：1 ≤ s.length ≤ 10⁴；s 由英文字母和空格组成；末尾至少有一个单词。单词是指仅由字母组成、不含空格的最大子串。",
        [
            "示例 1：s = \"Hello World\" → 5（最后一个单词 \"World\"）",
            "示例 2：s = \"   fly me   to   the moon  \" → 4（\"moon\"）",
        ],
        [
            "end 从 len(s)-1 开始，跳过尾部空格直到遇到非空格字符。",
            "start 从 end 继续向左，直到遇到空格或越界，定位单词左边界。",
            "单词长度为 end - start（start 停在空格处，不含空格本身）。",
            "单次从右向左扫描，O(n) 完成。",
        ],
        "双指针",
        code_notes=[
            "end = len(s) - 1 — 从字符串末尾开始。",
            "while end >= 0 and s[end] == ' ' — 跳过尾随空格。",
            "start = end; while start >= 0 and s[start] != ' ' — 向左扩展单词。",
            "return end - start — 单词字符数为 end - start。",
            "LeetCode 58 从尾部找最后一个单词。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    "strings/operations.py::replace_space": _m(
        "",
        "替换空格",
        "请实现一个函数，把字符串 s 中的每个空格替换成 \"%20\"。\n\nPython 可直接用 str.replace 完成；若需原地修改字符数组，可先统计空格数扩展数组，再从后向前填充。\n\n约束：0 ≤ s.length ≤ 10⁵；s 由英文字母、数字和空格组成。",
        [
            "示例：s = \"We are happy.\" → \"We%20are%20happy.\"",
            "示例：s = \" \" → \"%20\"。",
        ],
        [
            "将每个空格字符替换为 URL 编码 \"%20\"。",
            "Python 可直接用 str.replace(' ', '%20') 完成。",
            "若需原地修改（字符数组），可先统计空格数扩展数组，再从后向前填充。",
            "替换后长度增加，每个空格变为三个字符。",
        ],
        "字符串",
        code_notes=[
            "return s.replace(' ', '%20') — 内置 replace 逐空格替换。",
            "replace 返回新字符串，原 s 不变。",
            "剑指 Offer 05 / 剑指 Offer II 016 同类题。",
            "原地版：双指针从后向前填 '%20' 三个字符。",
            "时间 O(n)，空间 O(n) 或原地 O(1) 额外。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "strings/operations.py::minimum_deletion": _m(
        "1249",
        "移除无效的括号",
        "给你一个由 '(' 和 ')' 组成的字符串 s，在删除最少数目的括号后，使剩余括号字符串有效。本函数返回需要删除的最少括号数目。\n\n约束：1 ≤ s.length ≤ 10⁵；s 仅由 '(' 和 ')' 组成。",
        [
            "示例 1：s = \"lee(t(c)o)de)\" → 删除 2 个括号，返回 2",
            "示例 2：s = \"a)b(c)d\" → 删除 1 个，返回 1",
            "示例 3：s = \"))((\" → 删除 4 个，返回 4",
        ],
        [
            "从左到右扫描，用 balance 记录当前未匹配的 '(' 数量。",
            "遇 '('：balance++ 并保留该字符到 result。",
            "遇 ')'：仅当 balance > 0 时保留（有 '(' 可匹配），balance--；否则丢弃该 ')'。",
            "扫描结束后 result 中可能有多余 '('，但本实现只统计删除总数。",
            "删除数 = len(s) - len(result)，即被丢弃的括号个数。",
        ],
        "栈",
        code_notes=[
            "balance = 0 — 当前未闭合左括号计数。",
            "result: list[str] — 贪心保留的字符序列。",
            "if ch == '(': balance += 1; result.append(ch) — 左括号直接保留。",
            "elif ch == ')' and balance > 0 — 有左括号可匹配才保留右括号。",
            "return len(s) - len(result) — 原长减保留长即为删除数。",
            "本实现一次从左扫描，无需二次删除多余 '('（删除数已含在内）。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "strings/operations.py::longest_valid_parentheses": _m(
        "32",
        "最长有效括号",
        "给定只包含 '(' 和 ')' 的字符串 s，找出最长有效（格式正确且连续）括号子串的长度。\n\n约束：0 ≤ s.length ≤ 3×10⁴；s 仅由 '(' 和 ')' 组成。",
        [
            "示例 1：s = \"(()\" → 2（\"()\"）",
            "示例 2：s = \")()())\" → 4（\"()()\"）",
            "示例 3：s = \"\" → 0",
        ],
        [
            "栈存下标而非字符：初始压入 -1 作为「分隔符」，便于计算长度。",
            "遇 '(' 将下标 i 入栈。",
            "遇 ')' 先 pop 栈顶（匹配或移除分隔符）。",
            "若 pop 后栈空，将当前 i 作为新分隔符入栈（无效段起点）。",
            "否则有效长度 = i - stack[-1]，更新 best。",
        ],
        "栈",
        code_notes=[
            "stack = [-1] — 初始分隔符，有效段长度 = i - stack[-1]。",
            "stack.append(i) — '(' 记录下标等待匹配。",
            "stack.pop() — ')' 尝试与栈顶 '(' 下标匹配。",
            "if not stack: stack.append(i) — 多余 ')' 后重置分隔符。",
            "best = max(best, i - stack[-1]) — 当前有效括号子串长度。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "strings/operations.py::is_palindrome": _m(
        "125",
        "验证回文串",
        "如果在将所有大写字符转换为小写字符后，删除所有非字母数字字符后，字符串能正着读和倒着读一致，则该字符串为回文串。给定字符串 s，判断是否为回文串。\n\n约束：1 ≤ s.length ≤ 2×10⁵；s 由可打印 ASCII 字符组成。",
        [
            "示例 1：s = \"A man, a plan, a canal: Panama\" → True",
            "示例 2：s = \"race a car\" → False",
            "示例 3：s = \" \" → True（空串视为回文）",
        ],
        [
            "双指针 left、right 从两端向中间移动。",
            "跳过非字母数字字符：isalnum() 为 False 则指针继续移动。",
            "比较 s[left].lower() 与 s[right].lower()，不等则返回 False。",
            "相等则两指针内移，继续比较。",
            "left >= right 时返回 True。",
        ],
        "双指针",
        code_notes=[
            "left, right = 0, len(s) - 1 — 首尾双指针。",
            "while left < right and not s[left].isalnum() — 跳过左侧非字母数字。",
            "while left < right and not s[right].isalnum() — 跳过右侧非字母数字。",
            "s[left].lower() != s[right].lower() — 忽略大小写比较。",
            "left += 1; right -= 1 — 匹配成功，指针内收。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    "strings/operations.py::longest_common_prefix": _m(
        "14",
        "最长公共前缀",
        "编写一个函数来查找字符串数组 strs 中的最长公共前缀。\n\n约束：1 ≤ strs.length ≤ 200；0 ≤ strs[i].length ≤ 200；strs[i] 由小写英文字母组成。如果不存在公共前缀，返回空字符串 \"\"。",
        [
            "示例 1：strs = [\"flower\",\"flow\",\"flight\"] → \"fl\"",
            "示例 2：strs = [\"dog\",\"racecar\",\"car\"] → \"\"",
        ],
        [
            "若 strs 为空，直接返回空串。",
            "zip(*strs) 纵向对齐各字符串同位置字符，得到多组字符元组。",
            "逐组检查：若 set(group) 长度为 1，说明该位所有字符串相同，加入 prefix。",
            "一旦出现不同字符，break 停止扩展。",
            "return \"\".join(prefix) 得到公共前缀。",
        ],
        "字符串",
        code_notes=[
            "zip(*strs) — 解压转置，第 j 组为各串第 j 个字符。",
            "if len(set(group)) == 1 — 该列字符全部相同。",
            "prefix.append(group[0]) — 公共字符加入结果。",
            "else: break — 首次不匹配即停止。",
            "空 strs 返回 \"\" — 边界处理。",
        ],
        complexity="时间 O(n × m)，n 为字符串个数，m 为最短串长。",
    ),
    "strings/operations.py::shortest_distance_to_char": _m(
        "821",
        "字符的最短距离",
        "给定字符串 s 和字符 c，返回 s 中每个字符到 c 的最短距离。\n\n约束：1 ≤ s.length ≤ 10⁴；s 和 c 均为小写英文字母；s 中至少含一个 c。距离定义为两个下标之差的绝对值。",
        [
            "示例：s = \"loveleetcode\", c = \"e\" → [3,2,1,0,1,0,1,2,2,1,0,1]",
            "示例：s = \"aaab\", c = \"b\" → [3,2,1,0]",
        ],
        [
            "第一遍从左到右：维护 prev 为最近 c 的下标，ans[i] = i - prev。",
            "初始 prev = -n，保证 c 左侧距离足够大。",
            "第二遍从右到左：更新 prev 为右侧最近 c，ans[i] = min(ans[i], prev - i)。",
            "两遍扫描得到每个位置到最近 c 的最短距离。",
        ],
        "字符串",
        code_notes=[
            "ans = [0] * n — 距离数组。",
            "prev = -n — 左扫描哨兵，c 左侧初始距离很大。",
            "if ch == c: prev = i; ans[i] = i - prev — 左向距离。",
            "prev = 2 * n — 右扫描哨兵。",
            "for i in range(n-1, -1, -1) — 右向更新 min(ans[i], prev - i)。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "strings/operations.py::remove_palindrome_sub": _m(
        "1332",
        "删除回文子串",
        "给定字符串 s，可通过删除若干回文子串使 s 为空。返回需要删除的最少次数。\n\n约束：1 ≤ s.length ≤ 1000；s 仅由小写英文字母组成。",
        [
            "示例 1：s = \"ababa\" → 1（删整个回文 \"ababa\"）",
            "示例 2：s = \"abb\" → 2（如先删 \"a\" 再删 \"bb\"）",
        ],
        [
            "关键观察：任意字符串最多删 2 次即可清空。",
            "若 s 本身是回文（s == s[::-1]），删 1 次即可，返回 1。",
            "否则返回 2（先删一个字符，剩余必为回文，再删一次）。",
            "空串返回 0。",
        ],
        "字符串",
        code_notes=[
            "if not s: return 0 — 空串无需删除。",
            "if s == s[::-1]: return 1 — 整串回文一次删完。",
            "return 2 — 非回文串最多两次（经典结论）。",
            "s[::-1] — Python 切片反转判断回文。",
            "证明：删首或尾字符后，剩余串必为回文。",
        ],
        complexity="时间 O(n)，空间 O(1)（切片可能 O(n)）。",
    ),
    "strings/operations.py::reverse_integer": _m(
        "7",
        "整数反转",
        "给你一个 32 位有符号整数 x，返回将 x 中的数字部分反转后的结果。\n\n约束：-2³¹ ≤ x ≤ 2³¹-1；溢出时返回 0。若反转后整数溢出 32 位有符号整数范围 [-2³¹, 2³¹-1]，则返回 0。",
        [
            "示例 1：x = 123 → 321",
            "示例 2：x = -123 → -321",
            "示例 3：x = 120 → 21（末尾 0 不保留）",
        ],
        [
            "记录符号 sign = -1 if x < 0 else 1。",
            "对 abs(x) 的各位数字字符串反转：int(str(abs(x))[::-1])。",
            "乘以 sign 恢复符号。",
            "检查是否超出 32 位范围，溢出则返回 0。",
        ],
        "字符串",
        code_notes=[
            "sign = -1 if x < 0 else 1 — 单独处理符号。",
            "int(str(abs(x))[::-1]) — 转字符串反转再转整数，自动去前导零。",
            "value *= sign — 恢复正负。",
            "if value < -(2**31) or value > 2**31 - 1: return 0 — 溢出检查。",
            "也可用逐位 mod 10 构建，避免字符串。",
        ],
        complexity="时间 O(log x)，空间 O(log x)。",
    ),
    "strings/operations.py::convert_zigzag": _m(
        "6",
        "Z 字形变换",
        "将一个给定字符串 s 根据给定的行数 numRows，以 Z 字形排列后按行读取，返回新的字符串。\n\n约束：1 ≤ s.length ≤ 1000；s 由英文字母、逗号、句号组成；1 ≤ numRows ≤ 1000。",
        [
            "示例 1：s = \"PAYPALISHIRING\", numRows = 3 → \"PAHNAPLSIIGYIR\"",
            "示例 2：s = \"PAYPALISHIRING\", numRows = 4 → \"PINALSIGYAHRPI\"",
            "示例 3：s = \"A\", numRows = 1 → \"A\"",
        ],
        [
            "numRows <= 1 时直接返回 s。",
            "创建 numRows 个空列表 rows，模拟各行字符。",
            "遍历 index, ch：计算 cycle = index % (2*numRows-2)。",
            "row = cycle if cycle < numRows else 2*numRows-2-cycle，映射到对应行。",
            "将 ch 加入 rows[row]，最后按行 join 拼接。",
        ],
        "字符串",
        code_notes=[
            "rows: list[list[str]] — 每行一个字符列表。",
            "cycle = index % (2 * num_rows - 2) — Z 字周期长度。",
            "row = cycle if cycle < num_rows else 2 * num_rows - 2 - cycle — 行号映射。",
            "rows[row].append(ch) — 字符归入对应行。",
            "return \"\".join(\"\".join(row) for row in rows) — 按行拼接。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "strings/operations.py::repeated_string_match": _m(
        "686",
        "重复叠加字符串匹配",
        "给定两个字符串 a 和 b，返回 b 在 a 中重复叠加后的字符串中第一次出现所需的最少重复次数。\n\n约束：1 ≤ a.length, b.length ≤ 10⁴；a 和 b 由小写英文字母组成。若 b 不是 a 重复叠加的子串，返回 -1。",
        [
            "示例 1：a = \"abcd\", b = \"cdabcdab\" → 3",
            "示例 2：a = \"a\", b = \"aa\" → 2",
        ],
        [
            "若 b 中有 a 不含的字符，直接返回 -1。",
            "重复拼接 a，最多重复到长度 2*len(a)+len(b) 即可覆盖所有可能匹配。",
            "每次检查 b in repeated，找到则返回当前重复次数 count。",
            "循环结束仍未找到则返回 -1。",
        ],
        "字符串",
        code_notes=[
            "if not set(b).issubset(set(a)): return -1 — 字符集不匹配则无解。",
            "repeated = a; count = 1 — 初始为 a 重复 1 次。",
            "limit = 2 * len(a) + len(b) — 上界：最多再叠两圈 a 必能判定。",
            "while len(repeated) < limit — 控制拼接长度。",
            "if b in repeated: return count — 子串匹配成功。",
            "repeated += a; count += 1 — 继续叠加 a。",
        ],
        complexity="时间 O(n × m)，n 为 a 长，m 为 b 长（子串搜索）。",
    ),
    "strings/pattern_matching.py::repeat_substring_pattern": _m(
        "459",
        "重复的子字符串",
        "给定非空字符串 s，判断 s 能否由某个子串重复多次构成。\n\n约束：1 ≤ s.length ≤ 10⁴；s 由小写英文字母组成。",
        [
            "示例 1：s = \"abab\" → True（\"ab\" 重复 2 次）",
            "示例 2：s = \"aba\" → False",
            "示例 3：s = \"abcabcabcabc\" → True（\"abc\" 重复 4 次）",
        ],
        [
            "经典技巧：若 s 由子串重复构成，则 s 必为 (s+s) 去掉首尾字符后的子串。",
            "构造 t = (s + s)[1:-1]，即 s+s 去掉第一个和最后一个字符。",
            "若 s in t，说明 s 在「两个 s 拼接」的内部出现，存在周期结构。",
            "否则返回 False。",
        ],
        "字符串",
        code_notes=[
            "return s in (s + s)[1:-1] — 一行拼接判定法。",
            "(s + s)[1:-1] — 去掉首尾各一个字符，避免 trivial 匹配整个 s+s。",
            "原理：周期串 s 在 s+s 中至少出现两次，且第二次起点在 (1, len(s)) 内。",
            "时间 O(n)，KMP 或 Z 算法可优化，本实现依赖 Python in 的底层算法。",
            "False 例：s=\"aba\" 在 t 中无匹配。",
        ],
        complexity="时间 O(n) 均摊（KMP 实现），空间 O(n)。",
    ),
    "strings/pattern_matching.py::repeat_substring_pattern_by_kmp": _m(
        "459",
        "重复的子字符串（KMP）",
        "给定非空字符串 s，判断 s 能否由某个子串重复多次构成。\n\n约束：1 ≤ s.length ≤ 10⁴；s 由小写英文字母组成；使用 KMP border 性质。",
        [
            "示例 1：s = \"abab\" → True",
            "示例 2：s = \"aba\" → False",
        ],
        [
            "对 s 调用 build_next 得到 LPS 数组 nxt。",
            "border = nxt[-1] 为整个串的最长相同前后缀长度。",
            "若 border == 0，无重复结构，返回 False。",
            "重复单元长度 period = len(s) - border。",
            "若 len(s) % period == 0，则 s 由长度为 period 的子串重复构成。",
        ],
        "KMP",
        code_notes=[
            "nxt = build_next(s) — 调用公共 KMP 模块构建 LPS 数组。",
            "border = nxt[-1] — 整串最长 border 长度。",
            "border != 0 — 存在非平凡前后缀才可能有周期。",
            "len(s) % (len(s) - border) == 0 — 串长能被周期整除。",
            "period = len(s) - border — 最小重复子串长度。",
        ],
        complexity="时间 O(n)，空间 O(n)。",
    ),
    "foundations/bit_manipulation.py::single_number": _m(
        "136",
        "只出现一次的数字",
        "给定非空整数数组 nums，除某个元素只出现一次外，其余每个元素均出现两次。找出只出现一次的那个元素。\n\n约束：1 ≤ nums.length ≤ 3×10⁴；-3×10⁴ ≤ nums[i] ≤ 3×10⁴；除一个元素外均出现两次。",
        [
            "示例 1：nums = [2,2,1] → 1",
            "示例 2：nums = [4,1,2,1,2] → 4",
        ],
        [
            "异或性质：a ^ a = 0，a ^ 0 = a，且满足交换律、结合律。",
            "将所有元素依次异或，成对相同的数异或为 0 抵消。",
            "最终 result 即为只出现一次的数字。",
            "适用于除一个数外其余均出现偶数次的一般化场景（本题为 2 次）。",
        ],
        "位运算",
        code_notes=[
            "result = 0 — 异或累加初始值。",
            "for num in nums: result ^= num — 逐个异或。",
            "相同数字异或为 0，最后剩余单次出现的数。",
            "无需额外哈希表，O(1) 空间。",
            "LeetCode 136 经典位运算题。",
        ],
        complexity="时间 O(n)，空间 O(1)。",
    ),
    "foundations/bit_manipulation.py::hamming_weight": _m(
        "191",
        "位1的个数",
        "编写一个函数，输入无符号整数 n，返回其二进制表达式中数字位数为 '1' 的个数（也被称为汉明重量）。\n\n约束：输入为 32 位无符号整数；0 ≤ n ≤ 2³²-1。",
        [
            "示例 1：n = 11（二进制 1011）→ 3",
            "示例 2：n = 128（10000000）→ 1",
        ],
        [
            "Brian Kernighan 算法：n & (n-1) 清除 n 的最低位 1。",
            "循环：while n 非零，执行 n &= n-1 并 count++。",
            "循环次数等于 1 的个数。",
            "比逐位 n>>1 更高效，每位 1 只处理一次。",
        ],
        "位运算",
        code_notes=[
            "count = 0 — 1 的个数计数器。",
            "while n: — n 为 0 时结束。",
            "n &= n - 1 — 清除最低位 1，比逐位检查更高效。",
            "count += 1 — 每清除一次计一个 1。",
            "也可 n & 1 与 n >>= 1 逐位统计，本实现为 BK 算法。",
        ],
        complexity="时间 O(k)，k 为 1 的个数；最坏 O(32)。",
    ),
    "foundations/bit_manipulation.py::reverse_bits": _m(
        "190",
        "颠倒二进制位",
        "颠倒给定的 32 位无符号整数的二进制位，高位补 0 至 32 位。\n\n约束：输入为 32 位无符号整数；高位补 0 至 32 位。",
        [
            "示例：n = 43261596 → 964176192",
            "示例：n = 1 → 2147483648（32 位反转）",
        ],
        [
            "result 初始为 0，循环 32 次处理每一位。",
            "每次 result 左移一位，空出最低位。",
            "将 n 的最低位 (n & 1) 或到 result 上。",
            "n 右移一位，继续处理下一位。",
            "32 次后 result 即为颠倒后的值。",
        ],
        "位运算",
        code_notes=[
            "result = 0 — 结果累加器。",
            "for _ in range(32) — 固定处理 32 位。",
            "result = (result << 1) | (n & 1) — 左移并填入 n 的最低位。",
            "n >>= 1 — n 右移，取下一位。",
            "无需字符串转换，纯位操作 O(32)。",
        ],
        complexity="时间 O(1)（固定 32 次），空间 O(1)。",
    ),
    "foundations/bit_manipulation.py::trailing_zeros": _m(
        "172",
        "阶乘后的零",
        "给定整数 n，返回 n! 结果中尾随零的个数。\n\n约束：0 ≤ n ≤ 10⁴；统计 n! 尾随零个数。",
        [
            "示例 1：n = 3 → 0（3! = 6）",
            "示例 2：n = 5 → 1（5! = 120）",
            "示例 3：n = 0 → 0",
        ],
        [
            "尾随零由因子 10 = 2×5 产生，2 的个数总是多于 5，故只需统计因子 5 的个数。",
            "每出现一个 5 贡献至少一个零；25 贡献两个（5²），125 贡献三个，依此类推。",
            "循环 n //= 5，累加 count += n，直到 n < 5。",
            "count 即为 n! 尾随零的个数。",
        ],
        "位运算",
        code_notes=[
            "count = 0 — 尾随零计数。",
            "while n >= 5: — 至少有一个因子 5 才继续。",
            "n //= 5 — 统计当前层有多少个 5 的倍数。",
            "count += n — 累加 5、25、125… 的贡献。",
            "LeetCode 分类为数学/位运算，本质是数论而非逐位操作。",
        ],
        complexity="时间 O(log n)，空间 O(1)。",
    ),
    "foundations/sorting.py::quick_sort": _m(
        "",
        "快速排序",
        "对整数数组 array 的闭区间 [left, right] 原地升序排序。\n\n约束：对闭区间 [left, right] 原地升序排序；平均 O(n log n)，最坏 O(n²)。采用挖坑填数（Lomuto 变体）分区，再递归排序左右子区间。",
        [
            "示例：array = [2,4,1,5,7,3,8,2], left = 0, right = 7 → [1,2,2,3,4,5,7,8]",
            "示例：array = [3,1,2], left = 0, right = 2 → [1,2,3]",
        ],
        [
            "若 left >= right，区间为空或单元素，直接返回。",
            "选取 array[low] 作为 pivot（key），双指针 left、right 从区间两端向中间移动。",
            "right 左移直到 array[right] < key，将 array[right] 填到 array[left]（挖坑填数）。",
            "left 右移直到 array[left] > key，将 array[left] 填到 array[right]。",
            "重复直到 left >= right，将 key 放到 array[right] 作为 pivot 最终位置。",
            "递归 quick_sort(array, low, left-1) 与 quick_sort(array, left+1, high) 排序左右子区间。",
        ],
        "排序",
        code_notes=[
            "if left >= right: return — 递归基线。",
            "key = array[low] — 取区间左端为基准值。",
            "while left < right — 双指针向中间靠拢。",
            "while left < right and array[right] > key: right -= 1 — 找第一个 ≤ key 的元素。",
            "array[left] = array[right] — 右端元素填到左坑。",
            "while left < right and array[left] <= key: left += 1 — 找第一个 > key 的元素。",
            "array[right] = key — pivot 归位；再递归左右子区间。",
        ],
        complexity="平均时间 O(n log n)，最坏 O(n²)；空间 O(log n) 递归栈。",
    ),
}

