from meta.helpers import _m

PROBLEMS = {
    'data_structures/tree/tree.py::preorder_traversal': _m(
        '144',
        '二叉树的前序遍历',
        "给你一棵二叉树的根节点 root，返回它节点值的「前序遍历」结果。\n\n前序遍历的顺序为：根节点 → 左子树 → 右子树。你可以用递归或迭代完成；本实现采用颜色标记栈的迭代写法，空间复杂度为 O(h)。\n\n节点总数在 [0, 100] 范围内，节点值可能为负数。",
        [
            "示例 1：root = [1,null,2,3] → 输出 [1,2,3]",
        "示例 2：root = [] → 输出 []",
        ],
        [
            "使用栈 stack，元素为 (color, node) 二元组；WHITE=0 表示首次访问，GRAY=1 表示子树已处理完毕。",
        "弹出栈顶 (color, node)；若 node 为空则 continue。",
        "若 color 为 WHITE：按前序顺序将 (WHITE, right)、(WHITE, left)、(GRAY, node) 依次压栈（右先左后，出栈即根-左-右）。",
        "若 color 为 GRAY：将 node.val 追加到 result。",
        "栈空时返回 result。",
        ],
        '二叉树',
        code_notes=[
            "_iterative_order(root, 'pre') 封装 WHITE/GRAY 双态栈遍历逻辑，三种序共用一套框架。",
            "WHITE 节点首次入栈时按序压入左右子 WHITE 与自身 GRAY，GRAY 出栈时才访问节点值。",
            "前序压栈顺序：(WHITE, right), (WHITE, left), (GRAY, node)，保证 pop 顺序为根-左-右。",
            "空节点直接 continue，无需额外判空 root。",
            "result: list[int] 按访问顺序收集节点值。",
            "相比递归，迭代避免 Python 递归深度限制，适合极深树。",
            "时间 O(n)，额外空间 O(h) 为栈深度。",
        ],
        complexity='时间 O(n)，空间 O(h)，h 为树高。',
    ),
    'data_structures/tree/tree.py::inorder_traversal': _m(
        '94',
        '二叉树的中序遍历',
        "给你一棵二叉树的根节点 root，返回它节点值的「中序遍历」结果。\n\n中序遍历顺序为：左子树 → 根节点 → 右子树。对二叉搜索树而言，中序遍历得到升序序列。\n\n本实现采用 WHITE/GRAY 颜色标记栈迭代，无需递归。",
        [
            "示例 1：root = [1,null,2,3] → 输出 [1,3,2]",
        "示例 2：root = [] → 输出 []",
        ],
        [
            "调用 _iterative_order(root, 'in')，使用双态栈模拟中序。",
        "WHITE 节点首次处理：压栈 (WHITE, right), (GRAY, node), (WHITE, left)，使左子树最先被完整遍历。",
        "GRAY 节点出栈时将 val 写入 result。",
        "空指针跳过，栈空结束。",
        ],
        '二叉树',
        code_notes=[
            "中序压栈顺序：(WHITE, right), (GRAY, node), (WHITE, left)。",
            "GRAY 阶段才输出节点值，保证左子树全部访问完毕后再访问根。",
            "BST 相关题（第 K 小、验证 BST）可复用同一套中序框架。",
            "WHITE/GRAY 与 Morris 遍历是两种主流 O(1) 空间替代方案，此处选颜色栈更易读。",
            "result 为 flat list[int]，非按层分组。",
            "与 preorder/postorder 仅压栈顺序不同，共用 _iterative_order。",
            "时间 O(n)，空间 O(h)。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::postorder_traversal': _m(
        '145',
        '二叉树的后序遍历',
        "给你一棵二叉树的根节点 root，返回它节点值的「后序遍历」结果。\n\n后序遍历顺序为：左子树 → 右子树 → 根节点。常用于需要先处理子树再处理父节点的场景（如删除树、计算 subtree 信息）。\n\n本实现采用 WHITE/GRAY 颜色标记栈迭代。",
        [
            "示例 1：root = [1,null,2,3] → 输出 [3,2,1]",
        "示例 2：root = [1] → 输出 [1]",
        ],
        [
            "调用 _iterative_order(root, 'post')。",
        "WHITE 节点：压栈 (GRAY, node), (WHITE, right), (WHITE, left)，确保左右子树均处理完才访问根。",
        "GRAY 出栈时 append node.val。",
        "栈空返回 result。",
        ],
        '二叉树',
        code_notes=[
            "后序压栈：(GRAY, node), (WHITE, right), (WHITE, left)。",
            "GRAY 先于子节点 WHITE 入栈，但 GRAY 后于子节点出栈，实现左右根顺序。",
            "与递归后序「先递归左右再处理根」语义一致。",
            "空树返回 []。",
            "三种遍历共享 _iterative_order，仅 order 参数不同。",
            "迭代后序比「双栈反转前序」写法更统一。",
            "时间 O(n)，空间 O(h)。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::level_order': _m(
        '102',
        '二叉树的层序遍历',
        "给你二叉树的根节点 root，返回其节点值的层序遍历结果（即逐层从左到右访问）。\n\n每一层节点放在一个列表中，最终返回由这些列表组成的二维列表。空树返回空列表。\n\n经典 BFS 按层扩展，用队列维护当前层所有节点。",
        [
            "示例 1：root = [3,9,20,null,null,15,7] → [[3],[9,20],[15,7]]",
        "示例 2：root = [1] → [[1]]",
        "示例 3：root = [] → []",
        ],
        [
            "若 root 为空直接返回 []。",
        "初始化 deque 队列 queue = [root]，result 为空二维列表。",
        "while queue 非空：记录 len(queue) 为当前层节点数，新建 level 列表。",
        "循环当前层次数：popleft 取节点，append val 到 level，非空左右子入队。",
        "将 level 追加到 result；全部层处理完返回 result。",
        ],
        '二叉树',
        code_notes=[
            "collections.deque 作为 FIFO 队列，popleft O(1)。",
            "for _ in range(len(queue)) 固定一层宽度，避免混入下一层节点。",
            "level: list[int] 收集同层节点值，再 append 到 result。",
            "BFS 天然按层推进，是右视图、最左下角等题的基础。",
            "不修改树结构，只读遍历。",
            "节点数 n 时每个节点入队出队各一次。",
            "时间 O(n)，空间 O(w) 为队列最大宽度。",
        ],
        complexity='时间 O(n)，空间 O(w)，w 为最大层宽。',
    ),
    'data_structures/tree/tree.py::right_side_view': _m(
        '199',
        '二叉树的右视图',
        "给定一棵二叉树的根节点 root，想象自己站在它的右侧，返回从右侧能看到的节点值列表。\n\n同一层中，最右边的节点会被看到；若该层只有一个节点，则该节点可见。\n\n本实现复用 level_order，取每层最后一个元素。",
        [
            "示例 1：root = [1,2,3,null,5,null,4] → [1,3,4]",
        "示例 2：root = [1,null,3] → [1,3]",
        "示例 3：root = [] → []",
        ],
        [
            "调用 level_order(root) 得到按层分组的二维列表 levels。",
        "对 levels 中每一层 level，取 level[-1]（该层最右节点值）。",
        "列表推导 [level[-1] for level in levels] 即为右视图。",
        "空树时 level_order 返回 []，右视图也为 []。",
        ],
        '二叉树',
        code_notes=[
            "直接复用 BFS 层序，无需额外 DFS。",
            "level[-1] 即层内最后一个被 BFS 访问的节点，等价于最右节点。",
            "也可 BFS 时只记录每层首次出现的节点（从左），但取 [-1] 更简洁。",
            "时间复杂度与 level_order 相同 O(n)。",
            "若需 O(h) 空间，可改为 DFS 优先访问右子并记录深度首次出现。",
            "levels 为空列表时推导结果为空，无需特判 root。",
            "返回值 list[int] 长度等于树深度。",
        ],
        complexity='时间 O(n)，空间 O(w)。',
    ),
    'data_structures/tree/tree.py::kth_smallest': _m(
        '230',
        '二叉搜索树中第 K 小的元素',
        "给定一个二叉搜索树的根节点 root 和整数 k，返回其中第 k 小的元素（1-indexed）。\n\nBST 中序遍历为升序，第 k 个被访问的节点即为答案。本题用 WHITE/GRAY 栈实现迭代中序，无需构建完整序列。\n\n保证 k 在有效范围内。",
        [
            "示例 1：root = [3,1,4,null,2], k = 1 → 1",
        "示例 2：root = [5,3,6,2,4,null,null,1], k = 3 → 3",
        ],
        [
            "初始化 stack = [(WHITE, root)]，模拟中序：WHITE 时压 (WHITE, right), (GRAY, node), (WHITE, left)。",
        "GRAY 出栈表示该节点应被「访问」：k -= 1。",
        "若 k == 0，立即返回 node.val。",
        "栈空仍未返回则 raise ValueError（k 越界）。",
        ],
        '二叉搜索树',
        code_notes=[
            "与 is_valid_bst 等题共用 WHITE/GRAY 中序栈框架。",
            "不在 GRAY 阶段提前减 k，保证访问顺序与中序一致。",
            "找到答案后可立即 return，无需遍历剩余节点。",
            "k 为 1-indexed，第一次 GRAY 出栈时 k 从原值减到 0 即第 k 小。",
            "迭代避免 BST 退化为链时的递归栈溢出。",
            "空树且 k>=1 会抛 ValueError。",
            "时间 O(h+k) 最坏 O(n)，空间 O(h)。",
        ],
        complexity='时间 O(n) 最坏，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::invert_tree': _m(
        '226',
        '翻转二叉树',
        "给你一棵二叉树的根节点 root，翻转这棵二叉树，并返回其根节点。\n\n翻转即交换每个节点的左右子节点。可以递归自底向上交换，也可以 BFS/DFS 逐节点交换。\n\n本实现为后序式递归：先递归翻转左右子树，再交换 root.left 与 root.right。",
        [
            "示例 1：root = [4,2,7,1,3,6,9] → [4,7,2,9,6,3,1]",
        "示例 2：root = [2,1,3] → [2,3,1]",
        "示例 3：root = [] → []",
        ],
        [
            "若 root 为 None，返回 None。",
        "递归 invert_tree(root.right) 与 invert_tree(root.left) 得到翻转后的左右子树。",
        "交换赋值：root.left, root.right = 翻转后的右子、翻转后的左子。",
        "返回 root（原根节点，结构已翻转）。",
        ],
        '二叉树',
        code_notes=[
            "Python 多重赋值一行完成左右子交换。",
            "先递归再交换，保证子树内部已完成翻转。",
            "原地修改 TreeNode 引用，不新建根（除子树递归返回的同一节点）。",
            "空树返回 None，单节点树交换后不变。",
            "时间 O(n) 每个节点访问一次。",
            "递归深度 O(h)，极深树需注意栈限制。",
            "与 mirror 对称判断是互逆操作。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::tree_to_string': _m(
        '',
        '树转字符串',
        "将二叉树转换为 LeetCode 风格的嵌套括号字符串：节点值后接左子树括号，再接右子树括号；空子树省略对应括号。\n\n若只有左子无右子，格式为 val(left)；若只有右子，仍写 val()(right)；叶节点仅输出数字字符串。\n\n本实现为前序式递归拼接。",
        [
            "示例：root = [1,2,3,null,4] → \"1(2(4))(3)\"",
        "示例：root = [1] → \"1\"",
        ],
        [
            "空节点返回空字符串 \"\"。",
        "递归得到 left = tree_to_string(root.left)，right = tree_to_string(root.right)。",
        "若 right 非空：return f\"{root.val}({left})({right})\"。",
        "若 right 空但 left 非空：return f\"{root.val}({left})\"。",
        "否则为叶节点：return str(root.val)。",
        ],
        '二叉树',
        code_notes=[
            "right 优先判断：有右子则左右括号都输出，left 可为空串。",
            "仅 left 存在时只输出一层括号，符合 LeetCode 序列化惯例。",
            "叶节点不输出空括号。",
            "递归深度 O(h)，字符串总长度 O(n)。",
            "f-string 拼接，无 StringBuilder。",
            "与 build_tree 系列互为逆操作思路。",
            "空树返回 \"\" 而非 \"null\"。",
        ],
        complexity='时间 O(n)，空间 O(n) 含递归栈与结果串。',
    ),
    'data_structures/tree/tree.py::is_symmetric': _m(
        '101',
        '对称二叉树',
        "给你一个二叉树的根节点 root，检查它是否轴对称（镜像对称）。\n\n空树视为对称。对称意味着左子树是右子树的镜像：对应节点值相等，且左的左与右的右、左的右与右的左分别对称。\n\n本实现定义 mirror(left, right) 递归比较两棵子树是否互为镜像。",
        [
            "示例 1：root = [1,2,2,3,4,4,3] → True",
        "示例 2：root = [1,2,2,null,3,null,3] → False",
        ],
        [
            "若 root 为空返回 True；否则调用 mirror(root.left, root.right)。",
        "mirror：双空返回 True；一空一非空或值不等返回 False。",
        "递归 mirror(left.left, right.right) 与 mirror(left.right, right.left)。",
        "两递归均 True 则对称。",
        ],
        '二叉树',
        code_notes=[
            "内嵌函数 mirror 封装双指针同步 DFS。",
            "比较的是「位置对称」的两节点，而非同一棵树的两次遍历。",
            "也可改 BFS 成对入队 (left, right)，逻辑等价。",
            "短路：值不等立即 False，无需继续递归。",
            "not root or mirror(...) 一行处理空树。",
            "时间 O(n)，空间 O(h)。",
            "与 invert_tree 结合可验证 invert 后是否等于原结构。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::max_depth': _m(
        '104',
        '二叉树的最大深度',
        "给定一个二叉树 root，返回其最大深度（从根到最远叶节点的最长路径上的节点数）。\n\n空树深度为 0。单节点深度为 1。\n\n本实现为经典递归：1 + max(左深度, 右深度)。",
        [
            "示例 1：root = [3,9,20,null,null,15,7] → 3",
        "示例 2：root = [1,null,2] → 2",
        ],
        [
            "若 root 为 None，返回 0。",
        "递归计算 left = max_depth(root.left)，right = max_depth(root.right)。",
        "当前深度 = 1 + max(left, right)。",
        "返回该值。",
        ],
        '二叉树',
        code_notes=[
            "后序递归：先知道子树深度再决定当前深度。",
            "空节点贡献深度 0，使叶节点公式为 1+max(0,0)=1。",
            "也可 BFS 层数计数或 DFS 带 depth 参数取 max。",
            "时间 O(n) 每个节点一次。",
            "递归栈 O(h)， skew 树 h=n。",
            "与 min_depth 对比：最大深度任意空子树按 0 计。",
            "是许多树 DP 题（平衡、直径）的基础子问题。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::min_depth': _m(
        '111',
        '二叉树的最小深度',
        "给定一个二叉树 root，返回其最小深度（从根到最近叶节点的最短路径上的节点数）。\n\n叶节点指无左右孩子的节点。仅有一条子树时，最小深度沿有子的一侧计算，不能把空子树深度当 0 与有子一侧取 min。\n\n本实现递归分三种情况处理空左、空右、双非空。",
        [
            "示例 1：root = [3,9,20,null,null,15,7] → 2",
        "示例 2：root = [2,null,3,null,4] → 3（须到叶节点 4）",
        ],
        [
            "空节点返回 0。",
        "若无左子：return 1 + min_depth(root.right)（只能走右）。",
        "若无右子：return 1 + min_depth(root.left)。",
        "左右都有：return 1 + min(min_depth(left), min_depth(right))。",
        ],
        '二叉树',
        code_notes=[
            "与 max_depth 不同：单支树不能取 min(0, depth) 得 0。",
            "必须先判 not root.left / not root.right 再递归。",
            "BFS 层序找第一个叶节点更直观，但本实现为 DFS。",
            "叶节点定义：左右皆空，深度 1。",
            "skew 树最小深度等于节点数。",
            "时间 O(n)，空间 O(h)。",
            "易错点：直接 1+min(left,right) 会把「无左子」算成深度 1。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::count_nodes': _m(
        '222',
        '完全二叉树的节点个数',
        "给你一棵完全二叉树的根节点 root，求其节点个数。\n\n完全二叉树除最后一层外均满，最后一层从左连续填充。可在 O(log²n) 内利用满二叉树公式 2^d-1 优化，无需 O(n) 逐个计数。\n\n本实现：沿左右最深路径求 depth，若最左最右同深则为满树，否则递归左右相加。",
        [
            "示例 1：root = [1,2,3,4,5,6] → 6",
        "示例 2：root = [] → 0",
        "示例 3：root = [1] → 1",
        ],
        [
            "空树返回 0。",
        "从 root 沿 left、right 各走到底，统计 depth（层数差）。",
        "若 left 与 right 同时到底（均为 None），说明是满完全树，返回 2^(depth+1)-1。",
        "否则 return 1 + count_nodes(left) + count_nodes(right) 分治。",
        ],
        '二叉树',
        code_notes=[
            "while left and right 同步下探，每步 depth+=1。",
            "满树判定：最左链与最右链等深，节点数 2^(depth+1)-1。",
            "非满时在某一高度拆成左右两棵完全树递归。",
            "每次递归至少排除一层满树或减半规模，复杂度 O(log²n)。",
            "比普通 DFS O(n) 更优，但仅适用于完全二叉树假设。",
            "2 ** (depth + 1) - 1 用位运算或幂均可。",
            "若题目非完全树，应改用普通 count DFS。",
        ],
        complexity='时间 O(log²n)，空间 O(log n) 递归栈。',
    ),
    'data_structures/tree/tree.py::is_balanced': _m(
        '110',
        '平衡二叉树',
        "给定一个二叉树 root，判断它是否是高度平衡二叉树：每个节点的左右子树高度差绝对值不超过 1，且左右子树也平衡。\n\n本实现自底向上一次 DFS：height(node) 返回子树高度，不平衡时返回 -1 作哨兵。",
        [
            "示例 1：root = [3,9,20,null,null,15,7] → True",
        "示例 2：root = [1,2,2,3,3,null,null,4,4] → False",
        ],
        [
            "内嵌 height(node)：空返回 0。",
        "递归 left = height(node.left)；若 left == -1 直接返回 -1。",
        "递归 right = height(node.right)；若 right == -1 或 abs(left-right)>1 返回 -1。",
        "否则返回 1 + max(left, right)。",
        "主函数 return height(root) != -1。",
        ],
        '二叉树',
        code_notes=[
            "-1 哨兵表示以该节点为根的子树已不平衡，向上传播剪枝。",
            "比「分别求 max_depth 再比较」少重复遍历，每个节点 height 只算一次。",
            "abs(left - right) > 1 即 AVL 违反条件。",
            "空树 height=0，单节点 height=1，is_balanced 为 True。",
            "也可存储 (balanced, height) 元组，语义相同。",
            "时间 O(n)，空间 O(h)。",
            "与直径题类似，后序汇总子树信息。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::binary_tree_paths': _m(
        '257',
        '二叉树的所有路径',
        "给定一个二叉树的根节点 root，返回所有从根到叶节点的路径，每条路径以字符串 \"1->2->5\" 形式表示。\n\n叶节点指无左右孩子。空树返回空列表。\n\n本实现用栈迭代 DFS，栈元素为 (node, path_str)。",
        [
            "示例：root = [1,2,3,null,5] → [\"1->2->5\",\"1->3\"]",
        "示例：root = [1] → [\"1\"]",
        ],
        [
            "空 root 返回 []。",
        "stack = [(root, str(root.val))]，paths 收集结果。",
        "pop (node, path)；若 node 为叶（无左右子），append path 到 paths。",
        "非叶：先压右再压左（保证左先处理），path 扩展为 f\"{path}->{child.val}\"。",
        "栈空返回 paths。",
        ],
        '二叉树',
        code_notes=[
            "迭代 DFS 避免递归拼接字符串的开销。",
            "先右后左压栈使出栈顺序为左先右后（与前序一致）。",
            "叶判定：not node.left and not node.right。",
            "path 在栈中随节点传递，无需回溯 pop。",
            "也可递归 backtracking，逻辑等价。",
            "字符串拼接总长度 O(n·h) 最坏。",
            "时间 O(n)，空间 O(h) 栈深。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::sum_of_left_leaves': _m(
        '404',
        '左叶子之和',
        "给定二叉树的根节点 root，返回所有左叶子之和。左叶子指某节点左子节点且该左子为叶节点。\n\n右叶子不计入。需区分「是左孩子」与「是叶节点」两个条件。\n\n本实现递归 DFS，在父节点处判断左子是否为叶。",
        [
            "示例 1：root = [3,9,20,null,null,15,7] → 24（仅 9 和 15 为左叶）",
        "示例 2：root = [1] → 0",
        ],
        [
            "空树返回 0。",
        "total = 0；若 root.left 存在且无孙节点（左子为叶），total += root.left.val。",
        "递归累加 sum_of_left_leaves(left) + sum_of_left_leaves(right)。",
        "返回 total。",
        ],
        '二叉树',
        code_notes=[
            "在父节点判断 left leaf，而非在左子节点自判「我是左叶」。",
            "叶条件：not root.left.left and not root.left.right。",
            "右子树上的左叶会在递归 right 时被统计。",
            "也可 BFS 带 parent 方向标记。",
            "单节点无左子，返回 0。",
            "时间 O(n)，空间 O(h)。",
            "易错：把「所有叶节点」或「左子树所有节点」计入。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::find_bottom_left_value': _m(
        '513',
        '找树左下角的值',
        "给定二叉树的根节点 root，返回其最底层最左边节点的值。\n\n若最底层仅一个节点，即该节点。保证二叉树非空。\n\n本实现复用 level_order，取最后一层的第一个元素。",
        [
            "示例 1：root = [2,1,3] → 1",
        "示例 2：root = [1,2,3,4,null,5,6,null,null,null,7] → 7",
        ],
        [
            "空树 raise ValueError。",
        "result 初始为 root.val。",
        "遍历 level_order 每层 level，令 result = level[0]（该层最左）。",
        "最后一层循环结束后 result 即为答案。",
        ],
        '二叉树',
        code_notes=[
            "BFS 层序保证最后处理的 level 是最底层。",
            "每层更新 result = level[0]，最终保留最深层的 level[0]。",
            "比 DFS 记录 (depth, val) 取 max depth 再比左更简单。",
            "依赖 level_order 返回非空层列表。",
            "空树抛 ValueError 与题设非空可二选一。",
            "时间 O(n)，空间 O(w)。",
            "若同层多节点，仅 level[0] 参与最终答案。",
        ],
        complexity='时间 O(n)，空间 O(w)。',
    ),
    'data_structures/tree/tree.py::has_path_sum': _m(
        '112',
        '路径总和',
        "给你二叉树的根节点 root 和一个整数 targetSum，判断是否存在从根到叶的路径，使得路径上节点值之和等于 targetSum。\n\n叶节点指无左右子。路径必须到叶才算完整。\n\n本实现 DFS：从根开始，remain = targetSum - root.val，递归时传入子节点 remain - child.val。",
        [
            "示例 1：root = [5,4,8,11,null,13,4,7,2,null,null,null,1], targetSum = 22 → True",
        "示例 2：root = [1,2,3], targetSum = 5 → False",
        ],
        [
            "空树返回 False。",
        "定义 dfs(node, remain)：若 node 为叶，返回 remain == 0。",
        "若有左子且 dfs(left, remain - left.val) 为 True，返回 True。",
        "同理检查右子；均失败返回 False。",
        "入口 dfs(root, targetSum - root.val)。",
        ],
        '二叉树',
        code_notes=[
            "入口已减去根值，叶节点判 remain==0 而非 remain==node.val。",
            "必须到叶：非叶即使 remain==0 也不算（题目通常无此情况）。",
            "短路：左或右有一条 True 即返回。",
            "也可迭代 stack 存 (node, remain)。",
            "空树不含路径，False。",
            "时间 O(n)，空间 O(h)。",
            "与 path_sum 区别：只判存在性不收集路径。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::path_sum': _m(
        '113',
        '路径总和 II',
        "给你二叉树的根节点 root 和一个整数 targetSum，找出所有从根到叶且节点和等于 targetSum 的路径，每条路径以节点值列表表示。\n\n返回顺序不限。路径必须到叶节点结束。\n\n本实现回溯 DFS：path 列表维护当前路径，到叶且 remain==0 时拷贝加入 result。",
        [
            "示例：root = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22 → [[5,4,11,2],[5,8,4,5]]",
        ],
        [
            "result 为空；若 root 空直接返回。",
        "dfs(node, path, remain)：空节点 return。",
        "叶节点且 remain==0：result.append(path[:]) 拷贝当前路径。",
        "扩展左/右：path.append(child.val)，dfs 后 path.pop() 回溯。",
        "调用 dfs(root, [root.val], targetSum - root.val)。",
        ],
        '二叉树',
        code_notes=[
            "path[:] 拷贝避免后续 pop 影响已收集路径。",
            "经典回溯：选择-递归-撤销。",
            "入口 path 含根值，remain 已减根。",
            "叶判定同 has_path_sum。",
            "也可返回路径列表的 DFS 不传 path 而用前缀和，但回溯更直观。",
            "时间 O(n) 最坏路径数指数，空间 O(h) 栈+路径。",
            "与 path_sum_3 区别：路径必须从根开始。",
        ],
        complexity='时间 O(n²) 最坏（路径拷贝），空间 O(h)。',
    ),
    'data_structures/tree/tree.py::path_sum_3': _m(
        '437',
        '路径总和 III',
        "给定二叉树 root 和整数 targetSum，返回路径和等于 targetSum 的路径数目。\n\n路径可从任意节点开始、向下到任意节点（不要求到叶），方向只能向下。\n\n本实现前缀和 + DFS：prefix[acc] 记录当前根到 node 路径上各前缀和出现次数，以 acc - targetSum 查匹配。",
        [
            "示例：root = [10,5,-3,3,2,null,11,3,-2,null,1], targetSum = 8 → 3",
        ],
        [
            "prefix = defaultdict(int)，prefix[0] = 1 表示空前缀。",
        "dfs(node, acc)：空返回 0；acc += node.val。",
        "count = prefix[acc - targetSum]（以当前节点结尾的路径数）。",
        "prefix[acc] += 1；累加左右 dfs 结果；prefix[acc] -= 1 回溯。",
        "返回 dfs(root, 0)。",
        ],
        '二叉树',
        code_notes=[
            "prefix[0]=1 处理「从当前节点单独成路径」等边界。",
            "进入子树前 prefix[acc]+=1，返回前 -=1，保证前缀表只含祖先路径。",
            "acc - targetSum 对应某祖先到当前的路径和为 targetSum。",
            "与数组 subarray sum=k 同模型，树化后为根到当前路径。",
            "不要求到叶，故每个节点都可能是路径终点。",
            "时间 O(n)，空间 O(h) 哈希表+栈。",
            "比暴力 O(n²) 枚举起点优。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::sum_numbers': _m(
        '129',
        '求根到叶子节点数字之和',
        "给你一个二叉树的根节点 root，每条从根到叶的路径可看作一个整数（节点值拼接），返回所有根到叶数字之和。\n\n例如路径 1→2→3 表示数字 123。叶节点无左右子。\n\n本实现 DFS 传递当前累积值 value，到叶时累加进 total。",
        [
            "示例：root = [4,9,0,5,1] → 1026（495+491+40）",
        "示例：root = [1,2] → 12",
        ],
        [
            "total = 0，定义 dfs(node, value)。",
        "空节点 return；value = value * 10 + node.val。",
        "若叶节点：total += value 并 return。",
        "递归 dfs(left) 与 dfs(right) 同一 value。",
        "dfs(root, 0) 后返回 total。",
        ],
        '二叉树',
        code_notes=[
            "nonlocal total 在闭包中累加，也可 dfs 返回 int 求和。",
            "value * 10 + node.val 等价于字符串拼接再 int。",
            "仅叶节点贡献答案，中间节点只传递 value。",
            "注意节点值 0 合法，value 可能含前导零语义（数值上无影响）。",
            "DFS 深度 O(h)，数值可能很大需注意语言整数范围。",
            "与 path_sum 类似但累加的是十进制数而非节点和。",
            "时间 O(n)，空间 O(h)。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::build_tree_pre_in': _m(
        '105',
        '从前序与中序遍历序列构造二叉树',
        "给定两个整数数组 preorder 和 inorder，其中 preorder 是二叉树的前序遍历，inorder 是同一棵树的中序遍历，构造并返回这棵二叉树。\n\n假设树无重复值。前序首元素为根，在中序中找到根位置 split，左侧为左子树中序、右侧为右子树中序，再递归切分前序。\n\n本实现递归：root_val = preorder[0]，split = inorder.index(root_val)。",
        [
            "示例：preorder = [3,9,20,15,7], inorder = [9,3,15,20,7] → 还原树 [3,9,20,null,15,7]",
        ],
        [
            "preorder 空返回 None。",
        "root_val = preorder[0]；split = inorder.index(root_val)。",
        "创建 TreeNode(root_val)。",
        "左子：build(preorder[1:1+split], inorder[:split])。",
        "右子：build(preorder[1+split:], inorder[split+1:])。",
        "返回 root。",
        ],
        '二叉树',
        code_notes=[
            "inorder.index  O(n) 可优化为哈希表存值→下标。",
            "左子树大小 split 决定 preorder 切分点 1+split。",
            "切片创建新列表，简洁但增加 O(n) 拷贝；面试可用索引边界。",
            "前序确定根，中序划分左右子树元素集合。",
            "无重复值保证 index 唯一。",
            "与 build_tree_in_post 对称，一个用后序尾作根。",
            "时间 O(n²) 最坏（index+切片），空间 O(n)。",
        ],
        complexity='时间 O(n²) 最坏，空间 O(n)。',
    ),
    'data_structures/tree/tree.py::build_tree_in_post': _m(
        '106',
        '从中序与后序遍历序列构造二叉树',
        "给定 inorder 和 postorder，分别为同一棵二叉树的中序与后序遍历，构造该二叉树。\n\n后序最后一个元素为根。在中序中找到根下标 split，左侧为左子树、右侧为右子树，再对应切分后序数组。\n\n本实现递归：root_val = postorder[-1]。",
        [
            "示例：inorder = [9,3,15,20,7], postorder = [9,15,7,20,3] → 同上树结构",
        ],
        [
            "postorder 空返回 None。",
        "root_val = postorder[-1]；split = inorder.index(root_val)。",
        "root = TreeNode(root_val)。",
        "左：build(inorder[:split], postorder[:split])。",
        "右：build(inorder[split+1:], postorder[split:-1])。",
        "返回 root。",
        ],
        '二叉树',
        code_notes=[
            "后序尾元素为根，与 preorder[0] 对称。",
            "右子 postorder 为 postorder[split:-1]，去掉根元素。",
            "左子 postorder 长度等于 split。",
            "同样可用哈希表优化 index 查找。",
            "三序遍历任意两种（含中序）可唯一确定二叉树。",
            "切片写法与 pre_in 版结构平行。",
            "时间 O(n²) 最坏，空间 O(n)。",
        ],
        complexity='时间 O(n²) 最坏，空间 O(n)。',
    ),
    'data_structures/tree/tree.py::merge_trees': _m(
        '617',
        '合并二叉树',
        "给定两棵二叉树 root1 和 root2，合并成一棵新二叉树：重叠节点值相加，仅在一棵树出现的子树直接接到结果上。\n\n合并规则：t1 与 t2 都非空则新节点值为 t1.val+t2.val，递归合并左右；一方为空则返回另一方。\n\n本实现递归同步遍历两棵树。",
        [
            "示例 1：root1 = [1,3,null,5,3], root2 = [2,1,null,3,null,7] → [3,4,null,8,3,7]",
        "示例 2：root1 = [1], root2 = [1,2] → [2,2]",
        ],
        [
            "若 root1 空返回 root2；root2 空返回 root1。",
        "创建 TreeNode(root1.val + root2.val)。",
        "root.left = merge_trees(root1.left, root2.left)。",
        "root.right = merge_trees(root1.right, root2.right)。",
        "返回 root。",
        ],
        '二叉树',
        code_notes=[
            "新建节点而非修改原树（也可原地改 t1）。",
            "空树短路：return 另一棵子树指针，不再递归。",
            "两树高度不同时，深一侧多出的节点在对方为 None 时被原样返回。",
            "同步 DFS，访问节点数 O(min(n1,n2)) 到 O(n1+n2)。",
            "与链表 merge 两指针类似。",
            "值相加可能溢出需注意（题目通常忽略）。",
            "时间 O(min(n,m))，空间 O(h)。",
        ],
        complexity='时间 O(min(n,m))，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::search_bst': _m(
        '700',
        '二叉搜索树中的搜索',
        "给定二叉搜索树 root 和整数 val，在 BST 中查找值为 val 的节点，存在则返回该节点，否则返回 null。\n\nBST 性质：左子树所有值 < 根 < 右子树所有值。\n\n本实现迭代 while 循环，按 val 与 root.val 比较向左或向右走。",
        [
            "示例 1：root = [4,2,7,1,3], val = 2 → 节点 2",
        "示例 2：root = [4,2,7,1,3], val = 5 → null",
        ],
        [
            "while root 且 root.val != val。",
        "若 val < root.val，root = root.left；否则 root = root.right。",
        "循环结束：root 为 None 则未找到，否则 root 即为目标节点。",
        "return root。",
        ],
        '二叉搜索树',
        code_notes=[
            "迭代比递归更省栈，O(h) 步。",
            "利用 BST 有序性每次排除一半搜索空间。",
            "找到时 root.val == val，退出 while 后返回。",
            "也可写成递归 search_bst(root.left) if val<root.val else ...",
            "平均 O(log n)，最坏 skew O(n)。",
            "返回 TreeNode 引用而非 bool。",
            "与 insert/delete 共用同一比较方向。",
        ],
        complexity='时间 O(h)，空间 O(1)。',
    ),
    'data_structures/tree/tree.py::is_valid_bst': _m(
        '98',
        '验证二叉搜索树',
        "给定一个二叉树 root，判断其是否是有效的二叉搜索树。\n\n有效 BST 定义：中序遍历严格递增；等价地中序相邻节点 prev < curr。\n\n本实现 WHITE/GRAY 栈迭代中序，用 prev 记录上一个访问节点值。",
        [
            "示例 1：root = [2,1,3] → True",
        "示例 2：root = [5,1,4,null,null,3,6] → False（4 在 5 右子但小于 5）",
        ],
        [
            "prev = -inf；stack 中序遍历框架同 kth_smallest。",
        "GRAY 出栈时：若 node.val <= prev 返回 False。",
        "否则 prev = node.val，继续。",
        "遍历完成无违反返回 True。",
        ],
        '二叉搜索树',
        code_notes=[
            "必须严格递增，相等也非法：node.val <= prev。",
            "prev 初值 -inf 保证第一个节点可通过。",
            "范围法 (min,max) 递归亦可，中序更贴合实现风格。",
            "Integer.MIN_VALUE 作叶节点时 prev 初值需用 -inf 而非 0。",
            "发现 False 立即 return，不继续遍历。",
            "迭代避免递归栈。",
            "时间 O(n)，空间 O(h)。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::get_minimum_difference': _m(
        '530',
        '二叉搜索树的最小绝对差',
        "给定 BST 的根节点 root，返回树中任意两节点值之间的最小绝对差。\n\nBST 中序为升序，最小差必出现在中序相邻元素之间。\n\n本实现迭代中序，prev 指向上一个节点，best 维护最小差。",
        [
            "示例：root = [4,2,6,1,3] → 1（相邻 1 与 2 或 2 与 3）",
        "示例：root = [1,0,48,null,null,12,49] → 1",
        ],
        [
            "prev = None，best = inf，中序 WHITE/GRAY 栈。",
        "GRAY 出栈：若 prev 非空，best = min(best, node.val - prev.val)。",
        "prev = node（存节点引用便于 .val）。",
        "遍历结束 return best。",
        ],
        '二叉搜索树',
        code_notes=[
            "只需相邻中序节点，无需比较所有 O(n²) 对。",
            "prev 存 TreeNode 而非 int，与 find_mode 一致。",
            "首个 GRAY 节点无 prev，跳过差值更新。",
            "best 初值 inf，单节点树返回 inf 需题设保证至少两节点或特判。",
            "与 783 在数组上求最小差同理，BST 中序即排序数组。",
            "时间 O(n)，空间 O(h)。",
            "浮点 -inf 用于 prev 初值亦可，此处用 Optional 节点。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::find_mode': _m(
        '501',
        '二叉搜索树中的众数',
        "给定含Duplicates 的 BST 根节点，返回所有众数（出现次数最多的值），顺序不限。\n\nBST 中序遍历中相同值连续出现，可一趟扫描统计频次。\n\n本实现迭代中序，维护 prev、count、max_count、result。",
        [
            "示例：root = [1,null,2,2] → [2]",
        "示例：root = [0,null,1,null,2,null,2] → [2]",
        ],
        [
            "中序 GRAY 出栈时：若 prev 空或 prev.val != node.val，count=1；否则 count+=1。",
        "若 count == max_count，result.append(node.val)。",
        "若 count > max_count，max_count=count，result=[node.val] 重置。",
        "prev = node；遍历结束 return result。",
        ],
        '二叉搜索树',
        code_notes=[
            "相同值在中序中相邻，换值则 count 重置为 1。",
            "count > max_count 时 result 清空重建，非 append。",
            "count == max_count 时追加多个众数。",
            "可用 Counter 但中序 O(n) 更利用 BST 性质。",
            "prev 为 TreeNode 引用比较 .val。",
            "时间 O(n)，空间 O(h)+结果。",
            "与数组 find duplicates 连续段统计类似。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::sorted_array_to_bst': _m(
        '108',
        '将有序数组转换为二叉搜索树',
        "给你一个整数数组 nums（严格递增），将其转换为高度平衡 BST：每个节点左右两个子树高度差不超过 1。\n\n选取中点作根可保证平衡。递归构造左右子数组对应的子树。\n\n本实现：mid = len(nums)//2，根为 nums[mid]。",
        [
            "示例：nums = [-10,-3,0,5,9] → 高度平衡 BST（根 0，左 -3/-10，右 5/9 等）",
        "示例：nums = [1,3] → 根 3 或 1 取决于 mid 取法",
        ],
        [
            "nums 空返回 None。",
        "mid = len(nums) // 2；root = TreeNode(nums[mid])。",
        "root.left = sorted_array_to_bst(nums[:mid])。",
        "root.right = sorted_array_to_bst(nums[mid+1:])。",
        "返回 root。",
        ],
        '二叉搜索树',
        code_notes=[
            "中点分割保证左右子树规模差至多 1，树高 O(log n)。",
            "切片 nums[:mid] 创建新列表，可用 l,r 索引优化空间。",
            "严格递增数组中序即自身，前序/层序不唯一。",
            "与 build_tree 不同：仅一种中序给定，选 mid 定结构。",
            "空数组 None 终止递归。",
            "时间 O(n log n) 因切片，索引版 O(n)。",
            "平衡 BST 查找 O(log n)。",
        ],
        complexity='时间 O(n log n) 切片版，空间 O(n log n) 切片；索引版 O(n) 时间 O(log n) 栈。',
    ),
    'data_structures/tree/tree.py::lowest_common_ancestor': _m(
        '236',
        '二叉树的最近公共祖先',
        "给定二叉树 root 和两个节点 p、q，返回它们的最近公共祖先 LCA。\n\nLCA 定义为两节点在树中共同祖先中深度最大的节点（节点可以是自身祖先）。\n\n本实现后序递归：若 root 为 p 或 q 或 None，返回 root；否则看左右子树是否各含目标，都非空则 root 为 LCA，否则返回非空一侧。",
        [
            "示例：root = [3,5,1,6,2,0,8,null,null,7,4], p=5, q=1 → 3",
        "示例：p=5, q=4 → 5",
        ],
        [
            "若 not root 或 root is p 或 root is q，return root。",
        "left = LCA(root.left, p, q)；right = LCA(root.right, p, q)。",
        "若 left 且 right 均非空，return root（p,q 分居两侧）。",
        "return left or right（向上传递已找到的那个）。",
        ],
        '二叉树',
        code_notes=[
            "root in (p, q) 用 is 比较节点引用，题目保证 p,q 存在于树中。",
            "left and right 同时非空说明 p,q 分属左右子树，当前根即 LCA。",
            "仅一侧非空说明 LCA 在该侧或就是 p/q 本身。",
            "后序：先递归子树再处理当前，符合「自下而上」信息汇总。",
            "适用于普通二叉树，非 BST 性质。",
            "时间 O(n)，空间 O(h)。",
            "与 BST 版 O(h) 迭代不同。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::lowest_common_ancestor_bst': _m(
        '235',
        '二叉搜索树的最近公共祖先',
        "给定 BST 的 root 和节点 p、q，求 LCA。所有节点值唯一，p、q 均存在于树中。\n\n利用 BST 性质：若 p、q 都小于 root，LCA 在左子树；都大于 root 则在右子树；否则当前 root 即为 LCA（分叉点）。\n\n本实现迭代 while root。",
        [
            "示例：root = [6,2,8,0,4,7,9,null,null,3,5], p=2, q=8 → 6",
        "示例：p=2, q=4 → 2",
        ],
        [
            "while root：若 root.val > p.val 且 > q.val，root = root.left。",
        "elif root.val < p.val 且 < q.val，root = root.right。",
        "else return root（p,q 分居两侧或其一即为 root）。",
        "循环外 return None（题设保证存在则不会到达）。",
        ],
        '二叉搜索树',
        code_notes=[
            "比较 val 而非节点引用，因 BST 按值有序。",
            "分叉条件：一大一小相对 root.val，或 root 等于 p 或 q 的值。",
            "O(h) 时间，无需遍历整树。",
            "迭代写法比递归更简洁。",
            "p、q 无序：都小于或都大于才移动，否则停。",
            "与 236 对比：利用有序性剪枝。",
            "保证 p,q 存在，else 分支必触发 return。",
        ],
        complexity='时间 O(h)，空间 O(1)。',
    ),
    'data_structures/tree/tree.py::insert_into_bst': _m(
        '701',
        '二叉搜索树中的插入操作',
        "给定 BST 根节点 root 和值 val，向 BST 插入 val，返回根。保证 val 不在原树中。\n\n按 BST 性质找位置：小于当前走左，大于走右，空位创建新节点。\n\n本实现递归插入。",
        [
            "示例：root = [4,2,7,1,3], val = 5 → [4,2,7,1,3,5]",
        "示例：root = [40,20,60,10,30,50,70], val = 25 → 25 插在 20 与 30 之间",
        ],
        [
            "若 root 为 None，return TreeNode(val) 作为新叶。",
        "若 val < root.val，root.left = insert_into_bst(root.left, val)。",
        "否则 root.right = insert_into_bst(root.right, val)。",
        "return root。",
        ],
        '二叉搜索树',
        code_notes=[
            "递归沿搜索路径下探，回溯时挂接返回值。",
            "题设无重复，val 等于 root.val 的分支走 right（或 either）。",
            "也可迭代 cur 走指针直到 None 再挂叶。",
            "新节点总是叶节点。",
            "返回 root 保证根不变（除非原树空）。",
            "时间 O(h)，空间 O(h) 递归栈。",
            "与 search_bst 路径相同，多一步创建节点。",
        ],
        complexity='时间 O(h)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::delete_node': _m(
        '450',
        '删除二叉搜索树中的节点',
        "给定 BST 根 root 和 key，删除值为 key 的节点，返回根。保证 key 存在于树中。\n\n删除分三种：无子/单子直接替换；双子找右子树最小节点（中序后继）替换根值再删后继。\n\n本实现：后继为 root.right 最左节点 successor，用其替换 root 后递归删 successor。",
        [
            "示例：root = [5,3,6,2,4,null,7], key = 3 → 用 4 替换 3 或类似结构",
        "示例：key = 0 → 无变化若不存在",
        ],
        [
            "空返回 None；key < root.val 递归左；key > root.val 递归右。",
        "key == root.val：若缺左或右，return root.left or root.right。",
        "双子：successor = root.right，while successor.left: successor = successor.left。",
        "successor.right = delete_node(root.right, successor.val)；successor.left = root.left；return successor。",
        ],
        '二叉搜索树',
        code_notes=[
            "中序后继 = 右子树最左，保证替换后 BST 性质。",
            "先删 successor 于右子树（successor 最多一个右子），再 successor 接管 root 位置。",
            "也可找前驱（左子最右），对称实现。",
            "delete_node(root.right, successor.val) 删除重复值节点。",
            "单子删除直接 or 连接，O(1) 指针调整。",
            "时间 O(h)，空间 O(h)。",
            "LeetCode 要求返回新根，successor 可能成为新根若删原根。",
        ],
        complexity='时间 O(h)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::trim_bst': _m(
        '669',
        '修剪二叉搜索树',
        "给定 BST 根 root 和整数 low、high，修剪树使所有节点值在 [low, high] 内，返回修剪后的新根。\n\n小于 low 整棵丢弃走右；大于 high 整棵丢弃走左；在范围内则递归修剪左右。\n\n本实现递归后序式修剪。",
        [
            "示例：root = [1,0,2], low=1, high=2 → [1,null,2]",
        "示例：root = [3,0,4,null,2,null,null,1], low=1, high=3 → [3,2,null,1]",
        ],
        [
            "空返回 None。",
        "若 root.val < low，return trim_bst(root.right, low, high)（左子树全小，丢弃）。",
        "若 root.val > high，return trim_bst(root.left, low, high)。",
        "否则 root.left/right = trim 左右；return root。",
        ],
        '二叉搜索树',
        code_notes=[
            "剪枝时可能改变根：return 子树递归结果赋给上层指针。",
            "val < low 时整个左子树不必单独 trim，因 BST 左均更小。",
            "在 [low,high] 内节点保留，但子树仍可能含越界节点需递归。",
            "与 delete 不同：按范围批量删除而非单 key。",
            "时间 O(n) 最坏 visit 每节点，均摊 O(h) 路径。",
            "返回新根处理根被剪情况。",
            "空间 O(h) 栈。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::convert_bst': _m(
        '538',
        '把二叉搜索树转换为累加树',
        "给出 BST 根 root，将其转换为 Greater Tree：每个 node.val 变为原值加上所有大于它的节点值之和。\n\n即中序逆序（右-根-左）累加，最大节点不变，次大加最大，以此类推。\n\n本实现 WHITE/GRAY 栈，压栈顺序为 (WHITE,left),(GRAY,node),(WHITE,right) 实现反中序。",
        [
            "示例：root = [4,1,6,0,2,5,7,null,null,null,3,null,null,null,8] → 累加后各节点值递增累加",
        ],
        [
            "total = 0；初始化 stack = [(WHITE, root)]，反中序 WHITE 阶段压 (WHITE,left), (GRAY,node), (WHITE,right)。",
            "GRAY 出栈：total += node.val；node.val = total（原地改值，当前节点变为「自身+所有更大值之和」）。",
            "空节点 continue；栈空时所有节点已按从大到小完成累加赋值。",
            "遍历完 return root（结构不变，仅节点值更新）。",
        ],
        '二叉搜索树',
        code_notes=[
            "反中序先访问右子树，保证 total 已含所有更大值。",
            "原地修改 node.val，不新建树。",
            "与 1038 题相同；total 为全局累加器。",
            "压栈顺序与 inorder 左右对调实现 reverse inorder。",
            "也可递归 def dfs(node): dfs(right); node.val+=total; total=node.val; dfs(left)。",
            "时间 O(n)，空间 O(h)。",
            "初值 total=0，最大节点 val 不变（加 0）。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::prune_tree': _m(
        '814',
        '二叉树剪枝',
        "给定二叉树 root，删除所有不包含 1 的子树，返回修剪后的根。\n\n若某子树不含 1，则整棵子树删除（父指针置 null）。\n\n本实现后序递归：先 prune 左右，再若当前为叶且 val==0 则返回 None。",
        [
            "示例：root = [1,null,0,0,1] → [1,null,0,null,1]",
        "示例：root = [1,0,1,0,0,0,1] → [1,null,1,null,1]",
        ],
        [
            "空返回 None。",
        "root.left = prune_tree(root.left)；root.right = prune_tree(root.right)。",
        "若当前无子且 val==0，return None 删除该叶。",
        "否则 return root。",
        ],
        '二叉树',
        code_notes=[
            "后序：先知道子树 prune 结果再决定当前节点去留。",
            "仅 val==0 且为叶时删除；有 1 子树的 0 节点保留。",
            "子树被删后父节点可能变叶且 val==0，同一轮后序已处理（因先递归子）。",
            "需多轮或后序一次即可：子先 prune，当前再判。",
            "与 trim_bst 不同：按值 0/1 非范围。",
            "时间 O(n)，空间 O(h)。",
            "返回 None 使父 left/right 断开连接。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::generate_trees': _m(
        '95',
        '不同的二叉搜索树',
        "给定整数 n，生成所有由 1..n 为节点值且结构不同的 BST，返回根节点列表。\n\n卡特兰数 C_n 棵。分治：选 i 为根，左子树由 [start,i-1] 生成，右子树由 [i+1,end] 生成，左右笛卡尔积组合。\n\n本实现 build(start,end) 递归，start>end 返回 [None]。",
        [
            "示例：n = 3 → 5 棵不同 BST",
        "示例：n = 1 → 单节点 1",
        ],
        [
            "n==0 返回 []；调用 build(1,n)。",
        "build：若 start>end  return [None]（空子树占位）。",
        "对每个 root_val in [start,end]：left_trees=build(start, root_val-1)，right_trees=build(root_val+1,end)。",
        "笛卡尔积：对每个 left,right 创建 TreeNode(root_val,left,right) 加入 trees。",
        "返回 trees 列表。",
        ],
        '二叉树',
        code_notes=[
            "空树用 [None] 表示一种选择，便于笛卡尔积（None 作空指针）。",
            "三重循环：根值 × 左组合 × 右组合。",
            "卡特兰数增长快，n=8 已 1430 棵。",
            "与 unique BST count DP 相关，此为显式构造。",
            "build(1,n) 返回 list[Optional[TreeNode]] 可能含多根。",
            "时间 O(C_n · n)，空间 O(C_n · n) 存所有树。",
            "经典分治+笛卡尔积模板。",
        ],
        complexity='时间 O(4^n / n^(3/2)) 量级，空间同阶。',
    ),
    'data_structures/tree/tree.py::min_camera_cover': _m(
        '968',
        '监控二叉树',
        "在二叉树每个相机监控其父、自身、直接子节点，求覆盖所有节点的最少相机数。\n\n相机不能重复计算。贪心+树形 DP：每个节点三态——未覆盖、已覆盖无相机、本节点有相机。\n\n本实现后序 DFS 返回子树状态，UNWATCHED=0, WATCHED=1, CAMERA=2。",
        [
            "示例：root = [0,0,null,0,0] → 1",
        "示例：root = [0,0,null,0,null,0] → 2",
        "示例：root = [0,null,0,null,0,null,null,0] → 2",
        ],
        [
            "dfs 空节点返回 WATCHED（空不需要监控，视为已覆盖）。",
        "left=dfs(left), right=dfs(right)。",
        "若任子 UNWATCHED，当前必须放相机 cameras+=1，return CAMERA。",
        "若任子 CAMERA，return WATCHED；否则 return UNWATCHED。",
        "根 dfs 后若 UNWATCHED，根上方需再加相机 cameras+=1。",
        ],
        '二叉树',
        code_notes=[
            "空子树返回 WATCHED 是经典 trick，避免叶子强制父放相机。",
            "子 UNWATCHED 强制当前放相机覆盖该子。",
            "子有 CAMERA 则当前已被覆盖，状态 WATCHED。",
            "两子 WATCHED 则当前 UNWATCHED，可能由祖先相机覆盖。",
            "根 UNWATCHED 时无父节点，需额外 cameras+=1。",
            "后序保证先知道子状态再决策当前。",
            "时间 O(n)，空间 O(h)。",
        ],
        complexity='时间 O(n)，空间 O(h)。',
    ),
    'data_structures/tree/tree.py::vertical_traversal': _m(
        '987',
        '二叉树的垂序遍历',
        "给定二叉树 root，按垂线列从上到下、同列同行从左到右、同行同列按值升序输出。\n\n坐标：根 (0,0)，左子 (x-1,y+1)，右子 (x+1,y+1)。按 x 升序列，同 x 按 y 升序，同 (x,y) 按值排序。\n\n本实现 DFS 收集 columns[x][y] 列表，最后排序输出。",
        [
            "示例：root = [3,9,20,null,null,15,7] → [[9],[3,15],[20],[7]]",
        "示例：root = [1,2,3,4,5,6,7] → 多列按规则合并",
        ],
        [
            "columns: dict[x -> dict[y -> list[val]]]，DFS(node,x,y) 收集。",
        "dfs：空 return；columns[x][y].append(val)；递归左 (x-1,y+1)、右 (x+1,y+1)。",
        "for x in sorted(columns)：for y in sorted(columns[x])：level.extend(sorted(columns[x][y]))。",
        "append level 到 result；return result。",
        ],
        '二叉树',
        code_notes=[
            "defaultdict(lambda: defaultdict(list)) 自动嵌套。",
            "同 (x,y) 多节点需 sorted(values) 满足题意 987。",
            "x 负表示根左偏，sorted(columns) 从左列到右列。",
            "同行 y 相同，extend 后同列自上而下。",
            "也可 BFS 带坐标，DFS 更简洁。",
            "时间 O(n log n) 排序主导，空间 O(n)。",
            "与 314 竖直遍历（无同行排序）略有不同。",
        ],
        complexity='时间 O(n log n)，空间 O(n)。',
    ),
}
